// Copyright (c) Alexander Nachtmann
// SPDX-License-Identifier: Apache-2.0

extern alias analyzers;

using System.Collections.Immutable;
using System.Text;
using SemconvMigrationCatalog = analyzers::Qyl.Telemetry.SemanticConventions.Analyzers.SemconvMigrationCatalog;
using SemconvMigrationCatalogEntry = analyzers::Qyl.Telemetry.SemanticConventions.Analyzers.SemconvMigrationCatalogEntry;
using SemconvMigrationItemKind = analyzers::Qyl.Telemetry.SemanticConventions.Analyzers.SemconvMigrationItemKind;
using SemconvMigrationKind = analyzers::Qyl.Telemetry.SemanticConventions.Analyzers.SemconvMigrationKind;

namespace Qyl.Telemetry.SemanticConventions.Analyzers.DocsGenerator;

/// <summary>
///   Renders <c>docs/migration-catalog.md</c>: qyl-specific tables that supplement the
///   live-metadata story told by the per-rule pages. Owns the curated inventory, the
///   supplemental attribute-value fallback, the version × domain coverage matrix, and
///   the completion audit. Live <c>[Obsolete]</c> metadata from the referenced
///   <c>OpenTelemetry.SemanticConventions</c> package remains the primary source of
///   truth — the rows here exist only where live metadata is insufficient or absent.
/// </summary>
internal static class MigrationCatalogRenderer
{
    public static string Render(CatalogStatistics stats)
    {
        var sb = new StringBuilder();
        var sections = new Action<StringBuilder, CatalogStatistics>[]
        {
            (b, _) => WriteCatalogHeader(b),
            WriteCuratedSummary,
            WriteCompletionAudit,
            WriteVersionDomainTable,
            WriteCuratedInventory,
            WriteSupplementalValues,
            (b, _) => MarkdownFormatting.WriteGeneratedFile(b),
        };

        foreach (var section in sections)
        {
            if (sb.Length > 0) sb.AppendLine();
            section(sb, stats);
        }

        return sb.ToString().ReplaceLineEndings("\n");
    }

    private static void WriteCatalogHeader(StringBuilder sb)
    {
        sb.AppendLine("# Migration catalog");
        sb.AppendLine();
        sb.AppendLine($"<!-- <auto-generated /> This file is generated by {RepoLayout.ProjectRelativePath}. -->");
        sb.AppendLine();
        sb.AppendLine($"qyl-specific tables that supplement the [{RepoLayout.PackageName} index]({RepoLayout.PackageName}.md). Live `[Obsolete]` metadata from the referenced OpenTelemetry.SemanticConventions package remains the primary source of truth; the supplemental rows below are used only when live metadata is absent.");
    }

    private static void WriteCuratedSummary(StringBuilder sb, CatalogStatistics stats)
    {
        sb.AppendLine("## Curated Migration Inventory Summary");
        sb.AppendLine();
        sb.AppendLine($"Curated changelog mentions: {stats.Entries.Length}. Rows expected to have live metadata: {stats.Metadata}. Catalog fallback rows: {stats.Supplemental}. Exact fallback replacements: {stats.Exact}. Manual/context-sensitive fallback rows: {stats.Manual}. Removed/no-replacement fallback rows: {stats.Removed}. Guidance-only rows: {stats.Guidance}.");
        sb.AppendLine($"Supplemental attribute-value fallback rows: {stats.ValueEntries.Length}. Exact value replacements: {stats.ExactValue}. Manual value rows: {stats.ManualValue}. Removed/no-replacement value rows: {stats.RemovedValue}. These rows are used only when the same key/value is not covered by live `[Obsolete]` metadata from the referenced package.");
    }

    private static void WriteCompletionAudit(StringBuilder sb, CatalogStatistics stats)
    {
        sb.AppendLine("## Completion Audit");
        sb.AppendLine();
        sb.AppendLine("This section is generated from the analyzer descriptors and migration catalog. It is intended to make the package-level completion claim reviewable without hand-counting the catalog.");
        sb.AppendLine();
        sb.AppendLine("| Requirement | Current generated evidence |");
        sb.AppendLine("| -- | -- |");
        sb.AppendLine($"| Preserve the curated changelog-entry scope | `SemconvMigrationCatalog.Validate()` requires exactly `{SemconvMigrationCatalog.ExpectedCuratedMentionCount}` curated rows; current generated count is `{stats.Entries.Length}`. |");
        sb.AppendLine($"| Prefer live `[Obsolete]` metadata where available | `{stats.Metadata}` of `{stats.Entries.Length}` curated rows are classified as `DeprecatedButGenerated`; `QYL0003`, `QYL0005`, and `QYL0007` own those findings when referenced metadata is present. |");
        sb.AppendLine($"| Fall back to the catalog when metadata is absent | `{stats.Supplemental}` curated rows are eligible catalog diagnostics: `{stats.Exact}` exact replacement, `{stats.Manual}` manual/context-sensitive, `{stats.Removed}` removed/no-replacement, `{stats.Guidance}` guidance-only. |");
        sb.AppendLine($"| Keep attribute-value fallback separate from the curated name/key/event/metric count | `{stats.ValueEntries.Length}` supplemental attribute-value rows are outside the {stats.Entries.Length}-entry inventory and are used only when live value metadata is absent. |");
        sb.AppendLine("| Keep severity evidence-based | `QYL0009` is an exact production-emission replacement; `QYL0010` is a manual-review warning. Generated code is excluded by Roslyn. |");
        sb.AppendLine("| Keep code fixes exact-only | `LiveSemconvMetadataCodeFixProvider` registers fixes only when live `[Obsolete]` metadata exposes an exact replacement; `SupplementalSemconvMigrationCodeFixProvider` registers fixes only when diagnostic properties mark an exact replacement and provide one terminal replacement literal. |");
        sb.AppendLine();
        sb.AppendLine("| Migration kind | Curated count |");
        sb.AppendLine("| -- | --: |");
        foreach (var g in stats.Entries
            .GroupBy(e => e.MigrationKind)
            .OrderBy(g => g.Key.ToString(), StringComparer.Ordinal))
        {
            sb.AppendLine($"| {g.Key} | {g.Count()} |");
        }
        sb.AppendLine();
        sb.AppendLine("| Item kind | Curated count |");
        sb.AppendLine("| -- | --: |");
        foreach (var g in stats.Entries
            .GroupBy(e => e.Kind)
            .OrderBy(g => g.Key.ToString(), StringComparer.Ordinal))
        {
            sb.AppendLine($"| {g.Key} | {g.Count()} |");
        }
        sb.AppendLine();
        sb.AppendLine("| Production surface | Analyzer coverage evidence |");
        sb.AppendLine("| -- | -- |");
        sb.AppendLine("| `Activity.SetTag` / `AddTag` and baggage-like calls | Shared payload detection covers known tag setters plus `SetBaggage`/`AddBaggage` for live metadata and supplemental catalog checks. |");
        sb.AppendLine("| `TagList` / `ActivityTagsCollection` | `Add` payloads and `ActivityTagsCollection` indexer writes are recognized. |");
        sb.AppendLine("| Inline and local attribute payload collections | Arrays, object/collection initializers, C# collection expressions, `KeyValuePair<string, object?>`, local dictionary initializers, and local mutable dictionary `Add`/indexer writes are recognized when they visibly flow to telemetry APIs. |");
        sb.AppendLine("| Span/event/link/resource payloads | `ActivitySource.StartActivity(tags:)`, `ActivityEvent` tags, `ActivityLink` tags, and `ResourceBuilder.AddAttributes` are recognized. |");
        sb.AppendLine("| Metric payloads and names | `Counter<T>.Add`, `Histogram<T>.Record`, `UpDownCounter<T>.Add`, `Measurement<T>` tags, and `Meter.CreateCounter/Histogram/Gauge/Observable*` names are recognized. |");
        sb.AppendLine("| Logging payloads | Visible `ILogger.Log` state and `ILogger.BeginScope` state payloads are recognized when the key/value is statically visible. |");
    }

    private static void WriteVersionDomainTable(StringBuilder sb, CatalogStatistics stats)
    {
        sb.AppendLine("## Coverage by Version × Domain");
        sb.AppendLine();
        sb.AppendLine("Rows whose Version is `unknown` lack `Version` metadata in `SemconvMigrationCatalog.BuildEntries()`. This affects documentation attribution only; analyzer behavior remains unchanged.");
        sb.AppendLine();
        sb.AppendLine("| Version | Domain | Total | Expected live metadata | Fallback eligible | Exact fallback | Manual/context | Removed/no replacement |");
        sb.AppendLine("| -- | -- | --: | --: | --: | --: | --: | --: |");
        foreach (var g in stats.Entries
            .GroupBy(e => (e.Version, e.Domain))
            .OrderByDescending(g => VersionSortKey(g.Key.Version), StringComparer.Ordinal)
            .ThenBy(g => g.Key.Domain, StringComparer.Ordinal))
        {
            var rows = g.ToArray();
            var live = rows.Count(e => e.MigrationKind == SemconvMigrationKind.DeprecatedButGenerated);
            var supp = rows.Count(SemconvMigrationCatalog.IsSupplementalDiagnosticEntry);
            var exact = rows.Count(e => SemconvMigrationCatalog.IsSupplementalDiagnosticEntry(e)
                && e.HasExactReplacement);
            var manual = rows.Count(e => SemconvMigrationCatalog.IsSupplementalDiagnosticEntry(e)
                && e.MigrationKind is SemconvMigrationKind.ContextSensitive or SemconvMigrationKind.ManualReview);
            var removed = rows.Count(e => SemconvMigrationCatalog.IsSupplementalDiagnosticEntry(e)
                && e.MigrationKind == SemconvMigrationKind.RemovedNoReplacement);
            sb.AppendLine($"| {g.Key.Version} | {g.Key.Domain} | {rows.Length} | {live} | {supp} | {exact} | {manual} | {removed} |");
        }
    }

    private static void WriteCuratedInventory(StringBuilder sb, CatalogStatistics stats)
    {
        sb.AppendLine("## Curated Migration Inventory");
        sb.AppendLine();
        sb.AppendLine("| Old name | Kind | Signal | Domain | Since | Migration | Replacement | Evidence |");
        sb.AppendLine("| -- | -- | -- | -- | -- | -- | -- | -- |");
        foreach (var e in stats.Entries
            .OrderBy(x => x.Domain, StringComparer.Ordinal)
            .ThenBy(x => x.OldName, StringComparer.Ordinal))
        {
            var since = MarkdownFormatting.Escape(e.Version);
            var replacement = MarkdownFormatting.FormatReplacement(e.ReplacementNames);
            sb.AppendLine($"| `{e.OldName}` | {e.Kind} | {e.Signal} | {e.Domain} | {since} | {e.MigrationKind} | {replacement} | {MarkdownFormatting.Escape(e.ChangelogEvidence)} |");
        }
    }

    private static void WriteSupplementalValues(StringBuilder sb, CatalogStatistics stats)
    {
        sb.AppendLine("## Supplemental Attribute Value Fallback");
        sb.AppendLine();
        sb.AppendLine($"These value rows are intentionally separate from the {stats.Entries.Length}-entry name/key/event/metric inventory. `QYL0007` remains primary when the referenced package exposes `[Obsolete]` value constants; the supplemental analyzer uses this table only when live value metadata is absent.");
        sb.AppendLine();
        sb.AppendLine("| Old value | Signal | Domain | Migration | Replacement | Evidence |");
        sb.AppendLine("| -- | -- | -- | -- | -- | -- |");
        foreach (var e in stats.ValueEntries
            .OrderBy(x => x.Domain, StringComparer.Ordinal)
            .ThenBy(x => x.OldName, StringComparer.Ordinal))
        {
            var replacement = MarkdownFormatting.FormatReplacement(e.ReplacementNames);
            sb.AppendLine($"| `{e.OldName}` | {e.Signal} | {e.Domain} | {e.MigrationKind} | {replacement} | {MarkdownFormatting.Escape(e.ChangelogEvidence)} |");
        }
    }


    private static string VersionSortKey(string version) =>
        version is "unknown" ? "0.0.0" : version;
}

/// <summary>
///   Computed view of <c>SemconvMigrationCatalog</c> — the catalog itself is the source
///   of truth; this record is a tagged snapshot for the renderer + the <c>--audit</c>
///   mode so neither has to re-run the LINQ shape every time. <c>Compute</c> also calls
///   <c>SemconvMigrationCatalog.Validate()</c> so any contract drift fails before we
///   start writing files.
/// </summary>
internal readonly record struct CatalogStatistics(
    ImmutableArray<SemconvMigrationCatalogEntry> Entries,
    ImmutableArray<SemconvMigrationCatalogEntry> ValueEntries,
    int Metadata,
    int Supplemental,
    int Exact,
    int Manual,
    int Removed,
    int Guidance,
    int ExactValue,
    int ManualValue,
    int RemovedValue)
{
    public static CatalogStatistics Compute()
    {
        SemconvMigrationCatalog.Validate();
        var entries = SemconvMigrationCatalog.Entries;
        var valueEntries = SemconvMigrationCatalog.SupplementalAttributeValueEntries;
        var supplemental = entries.Where(SemconvMigrationCatalog.IsSupplementalDiagnosticEntry).ToArray();

        return new CatalogStatistics(
            Entries: entries,
            ValueEntries: valueEntries,
            Metadata: entries.Count(e => e.MigrationKind == SemconvMigrationKind.DeprecatedButGenerated),
            Supplemental: supplemental.Length,
            Exact: supplemental.Count(e => e.HasExactReplacement),
            Manual: supplemental.Count(e => e.MigrationKind is SemconvMigrationKind.ContextSensitive or SemconvMigrationKind.ManualReview),
            Removed: supplemental.Count(e => e.MigrationKind == SemconvMigrationKind.RemovedNoReplacement),
            Guidance: entries.Count(e => e.Kind == SemconvMigrationItemKind.GuidanceOnly),
            ExactValue: valueEntries.Count(e => e.MigrationKind == SemconvMigrationKind.ExactValueRename),
            ManualValue: valueEntries.Count(e => e.MigrationKind == SemconvMigrationKind.ManualReview),
            RemovedValue: valueEntries.Count(e => e.MigrationKind == SemconvMigrationKind.RemovedNoReplacement));
    }

    public string RenderAudit()
    {
        var sb = new StringBuilder();
        sb.AppendLine("OpenTelemetry semantic-convention migration audit");
        sb.AppendLine($"Curated changelog mentions: {Entries.Length}");
        sb.AppendLine($"Live [Obsolete] metadata rows: {Metadata}");
        sb.AppendLine($"Supplemental diagnostic rows: {Supplemental}");
        sb.AppendLine($"Exact supplemental replacements: {Exact}");
        sb.AppendLine($"Manual/context-sensitive supplemental rows: {Manual}");
        sb.AppendLine($"Removed/no-replacement supplemental rows: {Removed}");
        sb.AppendLine($"Guidance-only rows: {Guidance}");
        sb.AppendLine($"Supplemental attribute-value fallback rows outside the curated count: {ValueEntries.Length}");
        return sb.ToString();
    }
}
