// Copyright (c) Alexander Nachtmann
// SPDX-License-Identifier: Apache-2.0

using System.Text;
using Microsoft.CodeAnalysis;

namespace Qyl.Telemetry.SemanticConventions.Analyzers.DocsGenerator;

/// <summary>
///   Emits one markdown page per rule, keyed by id + symbolic name. Each page is
///   small (header + property table + description + see-also) so IDE Quick-Fix
///   "Show error help" links resolve onto a focused page rather than the
///   multi-thousand-line aggregate. Examples live in the analyzer test fixtures,
///   not here — keeping per-rule pages content-light is intentional so they don't
///   silently rot relative to the analyzer.
/// </summary>
internal static class RulePageRenderer
{
    public static string Render(
        DiagnosticDescriptor descriptor,
        string className,
        HashSet<string> fixableIds)
    {
        var sb = new StringBuilder();
        var title = MarkdownFormatting.Escape(descriptor.Title.ToString());
        var description = MarkdownFormatting.Escape(descriptor.Description.ToString());
        var codeFix = GetCodeFixLabel(descriptor.Id, fixableIds);
        var sourceBasename = SymbolicNaming.FileBasenameForClass(className);

        sb.AppendLine($"# {descriptor.Id}: {title}");
        sb.AppendLine();
        sb.AppendLine($"<!-- <auto-generated /> This file is generated by {RepoLayout.ProjectRelativePath}. -->");
        sb.AppendLine();
        sb.AppendLine("| Property | Value |");
        sb.AppendLine("| -- | -- |");
        sb.AppendLine($"| Severity | {descriptor.DefaultSeverity} |");
        sb.AppendLine($"| Category | `{descriptor.Category}` |");
        sb.AppendLine($"| Code fix | {codeFix} |");
        sb.AppendLine($"| Analyzer | `{className}` |");
        sb.AppendLine($"| Enabled by default | {(descriptor.IsEnabledByDefault ? "Yes" : "No")} |");
        sb.AppendLine();
        sb.AppendLine("## Description");
        sb.AppendLine();
        sb.AppendLine(description);
        sb.AppendLine();
        sb.AppendLine("## See also");
        sb.AppendLine();
        sb.AppendLine($"- [Rule index](../{RepoLayout.PackageName}.md)");
        sb.AppendLine("- [Migration catalog](../migration-catalog.md)");
        sb.AppendLine($"- [Source: `{sourceBasename}.cs`](../../src/{RepoLayout.PackageName}/{sourceBasename}.cs)");
        return sb.ToString().ReplaceLineEndings("\n");
    }

    /// <summary>
    ///   QYL0009/QYL0010 share <c>SupplementalSemconvMigrationCodeFixProvider</c>,
    ///   which gates registration via <c>IsExactReplacement</c>
    ///   (<c>MigrationKind == ExactRename / ExactValueRename / DeprecatedButGenerated</c>)
    ///   per-diagnostic, not by
    ///   ID. Reflect that contract in docs.
    /// </summary>
    public static string GetCodeFixLabel(string diagnosticId, HashSet<string> fixableIds)
    {
        if (!fixableIds.Contains(diagnosticId))
            return "No";

        return diagnosticId is "QYL0009" or "QYL0010"
            ? "Exact replacements only"
            : "Yes";
    }
}
