// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@89aae438b3b3b0a8dd33003c9d70592baf7dbd0d
// Schema: https://opentelemetry.io/schemas/1.43.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

#nullable enable

namespace Qyl.Telemetry.SemanticConventions.Incubating.Attributes.Webengine;

/// <summary>Webengine Attributes (incubating).</summary>
public static class WebengineAttributes
{
    /// <summary>
    /// Additional description of the web engine (e.g. detailed version and edition information).
    /// </summary>
    public const string Description = "webengine.description";

    /// <summary>
    /// The name of the web engine.
    /// </summary>
    public const string Name = "webengine.name";

    /// <summary>
    /// The version of the web engine.
    /// </summary>
    public const string Version = "webengine.version";
}
