#!/usr/bin/env python3
"""Emit the public incubating registry resources from resolved-registry.json."""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from emit_common import csharp_string  # noqa: E402


SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parents[2]
DEFAULT_REGISTRY = SCRIPT_DIR.parent / "Resources" / "resolved-registry.json"
DEFAULT_PROJECT = REPO_ROOT / "src" / "Qyl.Telemetry.SemanticConventions.Incubating"
GENERATED_SOURCE = Path("Registry") / "SemanticConventionRegistry.g.cs"
SCHEMA_DIRECTORY = Path("schemas") / "gen-ai"
RESOURCE_PREFIX = "Qyl.Telemetry.SemanticConventions.Incubating"


def source_for(registry: dict, schemas: list[dict]) -> str:
    genai_source = next(source for source in registry["sources"] if source["source_registry"] == "genai")
    mappings: list[tuple[str, str]] = []
    for schema in schemas:
        resource_name = f"{RESOURCE_PREFIX}.schemas.gen-ai.{Path(schema['path']).name}"
        mappings.extend((attribute_key, resource_name) for attribute_key in schema["attribute_keys"])
    mappings.sort()

    lines = [
        "// <auto-generated/>",
        f"// Generated from open-telemetry/semantic-conventions-genai@{genai_source['source_commit']}.",
        "// Regenerate with scripts/emit_registry_resources.py; do not edit by hand.",
        "// </auto-generated>",
        "",
        "#nullable enable",
        "",
        "using System.Collections.Generic;",
        "using System.Collections.ObjectModel;",
        "using System.IO;",
        "",
        "namespace Qyl.Telemetry.SemanticConventions.Incubating.Registry;",
        "",
        "/// <summary>",
        "/// Opens the complete pinned semantic-convention registry and the authoritative JSON Schemas",
        "/// referenced by structured GenAI attributes.",
        "/// </summary>",
        "public static class SemanticConventionRegistry",
        "{",
        "    private const string ResolvedRegistryResourceName =",
        f"        {csharp_string(RESOURCE_PREFIX + '.registry.resolved-registry.json')};",
        "",
        "    private static readonly IReadOnlyDictionary<string, string> PayloadSchemaResources =",
        "        new ReadOnlyDictionary<string, string>(new Dictionary<string, string>(System.StringComparer.Ordinal)",
        "        {",
    ]
    for attribute_key, resource_name in mappings:
        lines.append(f"            [{csharp_string(attribute_key)}] = {csharp_string(resource_name)},")
    lines.extend([
        "        });",
        "",
        "    /// <summary>The core OpenTelemetry schema URL represented by the registry.</summary>",
        f"    public const string CoreSchemaUrl = {csharp_string(registry['schema_url'])};",
        "",
        "    /// <summary>The development GenAI schema label declared by the pinned GenAI manifest.</summary>",
        f"    public const string GenAiSchemaUrl = {csharp_string(registry['genai_schema_url'])};",
        "",
        "    /// <summary>Gets the structured GenAI attribute keys that have an upstream JSON Schema.</summary>",
        "    public static IEnumerable<string> PayloadAttributeKeys => PayloadSchemaResources.Keys;",
        "",
        "    /// <summary>Opens the complete merged, source-attributed registry projection.</summary>",
        "    /// <returns>A new readable stream. The caller owns the stream.</returns>",
        "    public static Stream OpenResolvedRegistry() => OpenRequiredResource(ResolvedRegistryResourceName);",
        "",
        "    /// <summary>Opens the upstream JSON Schema associated with a structured GenAI attribute.</summary>",
        "    /// <param name=\"attributeKey\">The exact semantic-convention attribute key.</param>",
        "    /// <param name=\"schema\">A new readable stream when the key has a schema; otherwise <see langword=\"null\"/>.</param>",
        "    /// <returns><see langword=\"true\"/> when the registry associates a schema with the key.</returns>",
        "    public static bool TryOpenPayloadSchema(string attributeKey, out Stream? schema)",
        "    {",
        "        if (!PayloadSchemaResources.TryGetValue(attributeKey, out var resourceName))",
        "        {",
        "            schema = null;",
        "            return false;",
        "        }",
        "",
        "        schema = OpenRequiredResource(resourceName);",
        "        return true;",
        "    }",
        "",
        "    private static Stream OpenRequiredResource(string resourceName) =>",
        "        typeof(SemanticConventionRegistry).Assembly.GetManifestResourceStream(resourceName)",
        "        ?? throw new InvalidOperationException($\"Embedded semantic-convention resource '{resourceName}' was not found.\");",
        "}",
        "",
    ])
    return "\n".join(lines)


def expected_files(registry: dict, project_dir: Path) -> dict[Path, str]:
    schemas = sorted(
        (schema for schema in registry.get("json_schemas", []) if schema.get("source_registry") == "genai"),
        key=lambda schema: schema["path"],
    )
    if not schemas:
        raise ValueError("resolved registry contains no GenAI JSON Schemas")

    expected = {project_dir / GENERATED_SOURCE: source_for(registry, schemas)}
    for schema in schemas:
        expected[project_dir / SCHEMA_DIRECTORY / Path(schema["path"]).name] = schema["content"]
    return expected


def check(expected: dict[Path, str], project_dir: Path) -> int:
    failures: list[str] = []
    for path, content in expected.items():
        if not path.is_file():
            failures.append(f"missing generated file: {path}")
        elif path.read_text() != content:
            failures.append(f"stale generated file: {path}")

    schema_dir = project_dir / SCHEMA_DIRECTORY
    expected_schema_paths = {path for path in expected if path.parent == schema_dir}
    actual_schema_paths = set(schema_dir.glob("*.json")) if schema_dir.is_dir() else set()
    for path in sorted(actual_schema_paths - expected_schema_paths):
        failures.append(f"stale generated schema: {path}")

    if failures:
        print("\n".join(failures), file=sys.stderr)
        return 1
    return 0


def write(expected: dict[Path, str], project_dir: Path) -> None:
    schema_dir = project_dir / SCHEMA_DIRECTORY
    schema_dir.mkdir(parents=True, exist_ok=True)
    expected_schema_paths = {path for path in expected if path.parent == schema_dir}
    for path in schema_dir.glob("*.json"):
        if path not in expected_schema_paths:
            path.unlink()

    for path, content in expected.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--registry", type=Path, default=DEFAULT_REGISTRY)
    parser.add_argument("--project", type=Path, default=DEFAULT_PROJECT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    registry = json.loads(args.registry.read_text())
    expected = expected_files(registry, args.project)
    if args.check:
        return check(expected, args.project)

    write(expected, args.project)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
