// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@89aae438b3b3b0a8dd33003c9d70592baf7dbd0d
// Schema: https://opentelemetry.io/schemas/1.43.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

#nullable enable

namespace Qyl.Telemetry.SemanticConventions.Attributes.Url;

/// <summary>Url Attributes.</summary>
public static class UrlAttributes
{
    /// <summary>
    /// The <a href="https://www.rfc-editor.org/rfc/rfc3986#section-3.5">URI fragment</a> component
    /// </summary>
    public const string Fragment = "url.fragment";

    /// <summary>
    /// Absolute URL describing a network resource according to <a href="https://www.rfc-editor.org/rfc/rfc3986">RFC3986</a>
    /// </summary>
    /// <remarks>
    /// For network calls, URL usually has <c>scheme://host[:port][path][?query][#fragment]</c> format, where the fragment
    /// is not transmitted over HTTP, but if it is known, it SHOULD be included nevertheless.
    /// <para/>
    /// <c>url.full</c> MUST NOT contain credentials passed via URL in form of <c>https://username:password@www.example.com/</c>.
    /// In such case username and password SHOULD be redacted and attribute's value SHOULD be <c>https://REDACTED:REDACTED@www.example.com/</c>.
    /// <para/>
    /// <c>url.full</c> SHOULD capture the absolute URL when it is available (or can be reconstructed).
    /// <para/>
    /// Sensitive content provided in <c>url.full</c> SHOULD be scrubbed when instrumentations can identify it.
    /// <para/>
    /// Development
    /// Query string values for the following keys SHOULD be redacted by default and replaced by the
    /// value <c>REDACTED</c>:
    /// <para/>
    /// * <a href="https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_sigv-authentication-methods.html">`X-Amz-Signature`</a>
    /// * <a href="https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_sigv-authentication-methods.html">`X-Amz-Credential`</a>
    /// * <a href="https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_sigv-authentication-methods.html">`X-Amz-Security-Token`</a>
    /// * <a href="https://learn.microsoft.com/azure/storage/common/storage-sas-overview#sas-token">`sig`</a>
    /// * <a href="https://cloud.google.com/storage/docs/access-control/signed-urls">`X-Goog-Signature`</a>
    /// <para/>
    /// This list is subject to change over time.
    /// <para/>
    /// Matching of query parameter keys against the sensitive list SHOULD be case-sensitive.
    /// <para/>
    /// Development
    /// Instrumentation MAY provide a way to override this list via declarative configuration.
    /// If so, it SHOULD use the <c>sensitive_query_parameters</c> property
    /// (an array of case-sensitive strings with minimum items 0) under
    /// <c>.instrumentation/development.general.sanitization.url</c>.
    /// This list is a full override of the default sensitive query parameter keys,
    /// it is not a list of keys in addition to the defaults.
    /// <para/>
    /// When a query string value is redacted, the query string key SHOULD still be preserved, e.g.
    /// <c>https://www.example.com/path?color=blue&amp;sig=REDACTED</c>.
    /// </remarks>
    public const string Full = "url.full";

    /// <summary>
    /// The <a href="https://www.rfc-editor.org/rfc/rfc3986#section-3.3">URI path</a> component
    /// </summary>
    /// <remarks>
    /// Sensitive content provided in <c>url.path</c> SHOULD be scrubbed when instrumentations can identify it.
    /// </remarks>
    public const string Path = "url.path";

    /// <summary>
    /// The <a href="https://www.rfc-editor.org/rfc/rfc3986#section-3.4">URI query</a> component
    /// </summary>
    /// <remarks>
    /// Sensitive content provided in <c>url.query</c> SHOULD be scrubbed when instrumentations can identify it.
    /// <para/>
    /// Development
    /// Query string values for the following keys SHOULD be redacted by default and replaced by the value <c>REDACTED</c>:
    /// <para/>
    /// * <a href="https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_sigv-authentication-methods.html">`X-Amz-Signature`</a>
    /// * <a href="https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_sigv-authentication-methods.html">`X-Amz-Credential`</a>
    /// * <a href="https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_sigv-authentication-methods.html">`X-Amz-Security-Token`</a>
    /// * <a href="https://learn.microsoft.com/azure/storage/common/storage-sas-overview#sas-token">`sig`</a>
    /// * <a href="https://cloud.google.com/storage/docs/access-control/signed-urls">`X-Goog-Signature`</a>
    /// <para/>
    /// This list is subject to change over time.
    /// <para/>
    /// Matching of query parameter keys against the sensitive list SHOULD be case-sensitive.
    /// <para/>
    /// Instrumentation MAY provide a way to override this list via declarative configuration.
    /// If so, it SHOULD use the <c>sensitive_query_parameters</c> property
    /// (an array of case-sensitive strings with minimum items 0) under
    /// <c>.instrumentation/development.general.sanitization.url</c>.
    /// This list is a full override of the default sensitive query parameter keys,
    /// it is not a list of keys in addition to the defaults.
    /// <para/>
    /// When a query string value is redacted, the query string key SHOULD still be preserved, e.g.
    /// <c>q=OpenTelemetry&amp;sig=REDACTED</c>.
    /// </remarks>
    public const string Query = "url.query";

    /// <summary>
    /// The <a href="https://www.rfc-editor.org/rfc/rfc3986#section-3.1">URI scheme</a> component identifying the used protocol.
    /// </summary>
    public const string Scheme = "url.scheme";
}
