namespace Qyl.OpenTelemetry.SemanticConventions.SourceGeneration.Emitters;

/// <summary>
/// Builds the post-initialization source for a semantic-convention marker attribute.
/// Every marker attribute has the identical shape — an <c>internal sealed</c>
/// <c>[Conditional("QYL_SEMCONV_USAGES")]</c> attribute with a single
/// <c>(string prefix)</c> constructor — so all five surfaces (and their incubating
/// variants) share this one template instead of ten hand-maintained const strings.
/// Output is byte-identical to the per-generator strings it replaced.
/// </summary>
internal static class MarkerAttributeSource
{
    public static string For(string attributeClassName) => $$"""
        // <auto-generated/>
        #nullable enable
        namespace Qyl.OpenTelemetry.SemanticConventions.SourceGeneration;

        [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
        [global::System.Diagnostics.Conditional("QYL_SEMCONV_USAGES")]
        internal sealed class {{attributeClassName}} : global::System.Attribute
        {
            public {{attributeClassName}}(string prefix)
            {
                Prefix = prefix;
            }

            public string Prefix { get; }
        }
        """;
}
