using System.Text;
using Qyl.OpenTelemetry.SemanticConventions.SourceGeneration.Models;

namespace Qyl.OpenTelemetry.SemanticConventions.SourceGeneration.Emitters;

/// <summary>
/// Shared text-emission primitives for every SemConv emitter (attributes, metrics,
/// events, meters, activities). Each method is byte-identical to the per-emitter
/// helper it replaced — the byte-identity snapshot tests gate any drift, so changes
/// here are observable across all five surfaces at once.
/// </summary>
/// <remarks>
/// Two deliberate distinctions are preserved as separate members rather than
/// collapsed:
/// <list type="bullet">
///   <item><see cref="EscapeAttribute"/> collapses newlines to a space (attribute
///   arguments, and the meter emitter's unit/description literals);
///   <see cref="EscapeLiteral"/> turns them into <c>\n</c> (metric/event const
///   literals).</item>
///   <item><see cref="WriteObsolete"/> emits <c>[Obsolete]</c> only when a
///   deprecation model is present; <see cref="WriteStabilityObsolete"/> also emits
///   when the row's stability tier is itself <see cref="StabilityModel.Deprecated"/>.</item>
/// </list>
/// </remarks>
internal static class SourceWriter
{
    public static void WriteHeader(StringBuilder builder)
    {
        builder.AppendLine("// <auto-generated>This file has been auto generated from 'Qyl.OpenTelemetry.SemanticConventions.SourceGeneration'.</auto-generated>");
        builder.AppendLine();
        builder.AppendLine(GeneratedCodeHelpers.NullableEnable);
        builder.AppendLine();
        builder.AppendLine("#pragma warning disable CS1570 // XML comment has badly formed XML");
        builder.AppendLine();
    }

    public static void WriteNamespace(StringBuilder builder, string ns)
    {
        if (!string.IsNullOrEmpty(ns))
        {
            builder.Append("namespace ").Append(ns).AppendLine(";");
            builder.AppendLine();
        }
    }

    public static void WriteSummaryComment(StringBuilder builder, string text, int indent)
    {
        var pad = new string(' ', indent);
        builder.Append(pad).AppendLine("/// <summary>");
        foreach (var line in SplitLines(text))
            AppendDocLine(builder, pad, line);
        builder.Append(pad).AppendLine("/// </summary>");
    }

    public static void WriteRemarksComment(StringBuilder builder, string text, int indent)
    {
        var pad = new string(' ', indent);
        builder.Append(pad).AppendLine("/// <remarks>");
        foreach (var line in SplitLines(text))
            AppendDocLine(builder, pad, line);
        builder.Append(pad).AppendLine("/// </remarks>");
    }

    public static void WriteExamplesComment(StringBuilder builder, EquatableArray<string> examples, int indent)
    {
        if (examples.Length == 0)
            return;

        var pad = new string(' ', indent);
        builder.Append(pad).AppendLine("/// <remarks>");
        builder.Append(pad).AppendLine("/// Examples:");
        foreach (var example in examples)
            AppendDocLine(builder, pad, "- " + example);
        builder.Append(pad).AppendLine("/// </remarks>");
    }

    public static void AppendDocLine(StringBuilder builder, string pad, string line)
    {
        builder.Append(pad).Append("///");
        if (!string.IsNullOrEmpty(line))
            builder.Append(' ').Append(line);
        builder.AppendLine();
    }

    /// <summary>Emits <c>[Obsolete]</c> iff <paramref name="deprecated"/> is present.</summary>
    public static void WriteObsolete(StringBuilder builder, DeprecatedModel? deprecated, int indent)
    {
        if (deprecated is null) return;
        AppendObsolete(builder, deprecated, indent);
    }

    /// <summary>
    /// Emits <c>[Obsolete]</c> when the row carries a deprecation model OR when its
    /// stability tier is itself <see cref="StabilityModel.Deprecated"/> (the meters
    /// and activities surfaces propagate stability=deprecated as an obsolete symbol).
    /// </summary>
    public static void WriteStabilityObsolete(
        StringBuilder builder,
        StabilityModel stability,
        DeprecatedModel? deprecated,
        int indent)
    {
        if (stability != StabilityModel.Deprecated && deprecated is null) return;
        AppendObsolete(builder, deprecated, indent);
    }

    private static void AppendObsolete(StringBuilder builder, DeprecatedModel? deprecated, int indent)
    {
        var pad = new string(' ', indent);
        builder.Append(pad).Append("[global::System.Obsolete(\"")
               .Append(EscapeAttribute(DeprecatedMessage(deprecated))).AppendLine("\")]");
    }

    public static string DeprecatedMessage(DeprecatedModel? deprecated) => deprecated switch
    {
        DeprecatedModel.Renamed r => $"Replaced by {r.RenamedTo}.",
        DeprecatedModel.Obsoleted => "Removed, no replacement.",
        DeprecatedModel.Uncategorized u => string.IsNullOrEmpty(u.Note) ? "Deprecated." : u.Note,
        _ => "Deprecated."
    };

    public static string RequirementLevelName(RequirementLevelKind kind) => kind switch
    {
        RequirementLevelKind.Required => "required",
        RequirementLevelKind.Recommended => "recommended",
        RequirementLevelKind.OptIn => "opt_in",
        RequirementLevelKind.ConditionallyRequired => "conditionally_required",
        _ => "unspecified"
    };

    public static string ToPascalCase(string value)
    {
        if (string.IsNullOrEmpty(value)) return string.Empty;

        var builder = new StringBuilder(value.Length);
        var upperNext = true;
        foreach (var ch in value)
        {
            if (ch is '.' or '_' or '-' or ' ')
            {
                upperNext = true;
                continue;
            }

            if (upperNext)
            {
                builder.Append(char.ToUpperInvariant(ch));
                upperNext = false;
            }
            else
            {
                builder.Append(ch);
            }
        }
        return builder.ToString();
    }

    public static IEnumerable<string> SplitLines(string text)
    {
        if (string.IsNullOrEmpty(text)) yield break;

        foreach (var line in text.Split('\n'))
            yield return line.TrimEnd('\r');
    }

    /// <summary>Escapes for a string literal where newlines collapse to a space (attribute args; meter unit/description).</summary>
    public static string EscapeAttribute(string text)
        => text.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", " ").Replace("\r", string.Empty);

    /// <summary>Escapes for a string literal where newlines become <c>\n</c> (metric/event const literals).</summary>
    public static string EscapeLiteral(string text)
        => text.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", string.Empty);
}
