// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@e10a930844c6951757a43b849d364f7d056ac32b
// Schema: https://opentelemetry.io/schemas/1.44.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

#nullable enable

namespace Qyl.Telemetry.SemanticConventions.Incubating.Attributes.OracleCloud;

/// <summary>OracleCloud Attributes (incubating).</summary>
public static class OracleCloudAttributes
{
    /// <summary>
    /// The OCI realm identifier that indicates the isolated partition in which the tenancy and its resources reside.
    /// </summary>
    /// <remarks>
    /// See <a href="https://docs.oracle.com/iaas/Content/General/Concepts/regions.htm">OCI documentation on realms</a>
    /// </remarks>
    public const string Realm = "oracle_cloud.realm";
}
