// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@89aae438b3b3b0a8dd33003c9d70592baf7dbd0d
// Schema: https://opentelemetry.io/schemas/1.43.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

#nullable enable

namespace Qyl.Telemetry.SemanticConventions.Incubating.Attributes.Signalr;

/// <summary>Signalr Attributes (incubating).</summary>
public static class SignalrAttributes
{
    /// <summary>
    /// SignalR HTTP connection closure status.
    /// </summary>
    public const string ConnectionStatus = "signalr.connection.status";

    /// <summary>
    /// Values for the <c>ConnectionStatus</c> attribute.
    /// </summary>
    public static class ConnectionStatusValues
    {
        /// <summary>
        /// The connection was closed because the app is shutting down.
        /// </summary>
        public const string AppShutdown = "app_shutdown";

        /// <summary>
        /// The connection was closed normally.
        /// </summary>
        public const string NormalClosure = "normal_closure";

        /// <summary>
        /// The connection was closed due to a timeout.
        /// </summary>
        public const string Timeout = "timeout";
    }

    /// <summary>
    /// <a href="https://github.com/dotnet/aspnetcore/blob/main/src/SignalR/docs/specs/TransportProtocols.md">SignalR transport type</a>
    /// </summary>
    public const string Transport = "signalr.transport";

    /// <summary>
    /// Values for the <c>Transport</c> attribute.
    /// </summary>
    public static class TransportValues
    {
        /// <summary>
        /// LongPolling protocol.
        /// </summary>
        public const string LongPolling = "long_polling";

        /// <summary>
        /// ServerSentEvents protocol.
        /// </summary>
        public const string ServerSentEvents = "server_sent_events";

        /// <summary>
        /// WebSockets protocol.
        /// </summary>
        public const string WebSockets = "web_sockets";
    }
}
