// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@89aae438b3b3b0a8dd33003c9d70592baf7dbd0d
// Schema: https://opentelemetry.io/schemas/1.43.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

#nullable enable

namespace Qyl.Telemetry.SemanticConventions.Incubating.Attributes.Android;

/// <summary>Android Attributes (incubating).</summary>
public static class AndroidAttributes
{
    /// <summary>
    /// This attribute represents the state of the application.
    /// </summary>
    /// <remarks>
    /// The Android lifecycle states are defined in <a href="https://developer.android.com/guide/components/activities/activity-lifecycle#lifecycle-callbacks">Activity lifecycle callbacks</a>, and from which the <c>OS identifiers</c> are derived.
    /// </remarks>
    public const string AppState = "android.app.state";

    /// <summary>
    /// Values for the <c>AppState</c> attribute.
    /// </summary>
    public static class AppStateValues
    {
        /// <summary>
        /// Any time after Activity.onPause() or, if the app has no Activity, Context.stopService() has been called when the app was in the foreground state.
        /// </summary>
        public const string Background = "background";

        /// <summary>
        /// Any time before Activity.onResume() or, if the app has no Activity, Context.startService() has been called in the app for the first time.
        /// </summary>
        public const string Created = "created";

        /// <summary>
        /// Any time after Activity.onResume() or, if the app has no Activity, Context.startService() has been called when the app was in either the created or background states.
        /// </summary>
        public const string Foreground = "foreground";
    }

    /// <summary>
    /// Uniquely identifies the framework API revision offered by a version (<c>os.version</c>) of the android operating system. More information can be found in the <a href="https://developer.android.com/guide/topics/manifest/uses-sdk-element#ApiLevels">Android API levels documentation</a>.
    /// </summary>
    public const string OsApiLevel = "android.os.api_level";

    /// <summary>
    /// Deprecated. Use <c>android.app.state</c> attribute instead.
    /// </summary>
    [global::System.Obsolete("Replaced by android.app.state.", false)]
    public const string State = "android.state";

    /// <summary>
    /// Values for the <c>State</c> attribute.
    /// </summary>
    public static class StateValues
    {
        /// <summary>
        /// Any time after Activity.onPause() or, if the app has no Activity, Context.stopService() has been called when the app was in the foreground state.
        /// </summary>
        public const string Background = "background";

        /// <summary>
        /// Any time before Activity.onResume() or, if the app has no Activity, Context.startService() has been called in the app for the first time.
        /// </summary>
        public const string Created = "created";

        /// <summary>
        /// Any time after Activity.onResume() or, if the app has no Activity, Context.startService() has been called when the app was in either the created or background states.
        /// </summary>
        public const string Foreground = "foreground";
    }
}
