#!/usr/bin/env python3
"""TypeSpec projection of the semconv attribute keys (otel-keys.gen.tsp).

Reads the embedded resolved-registry.json (core + genai merge produced by
generate.sh) and emits the TypeSpec key-constant file consumed by
qyl-api-schema (`generated/otel-keys.gen.tsp`).

This is the successor to the frozen `@ancplua/typespec-otel-semconv@1.41.0-2`
npm package, whose source repo (and Weaver pipeline) was archived and deleted;
the projection is regenerated from THIS repo's pipeline instead. Output shape
is faithful to that package's `lib/otel-keys.gen.tsp`:

    namespace ANcpLua.OpenTelemetry.SemanticConventions.Keys.<PascalRoot> {
      /** <one-line brief> */
      #deprecated "<message>"          // only when the attribute is deprecated
      const <PascalRest>: string = "<dotted.key>";
    }

Rules (mirroring emit_attributes.py where they overlap):
  * full surface — every catalog attribute, all stabilities, deprecated kept
    (a deprecated key is still a valid wire key on old telemetry);
  * namespace = PascalCase of the first dot-segment of the key; const name =
    PascalCase of the remainder; `.`<->`_` PascalCase collisions resolved by
    preferring the non-deprecated entry (resolve_collisions);
  * briefs are collapsed to one line; `*/` cannot appear inside a TypeSpec
    doc comment and is asserted absent;
  * deprecation message wording comes from deprecated_message() so the
    TypeSpec and C# surfaces agree.

CLI:
    emit_typespec_keys.py --stdout
    emit_typespec_keys.py --write <path/to/otel-keys.gen.tsp>
"""
from __future__ import annotations

import json
import sys

from emit_attributes import (
    JSON_PATH,
    _collapse_ws,
    deprecated_message,
    resolve_collisions,
    to_pascal,
)

KEYS_NAMESPACE = "ANcpLua.OpenTelemetry.SemanticConventions.Keys"


def tsp_string(value: str) -> str:
    # TypeSpec "..." literals are single-line; notes from the registry can be
    # multi-line markdown, so collapse whitespace before escaping.
    return _collapse_ws(value).replace("\\", "\\\\").replace('"', '\\"')


def doc_line(brief: str) -> str | None:
    text = _collapse_ws(brief or "")
    if not text:
        return None
    if "*/" in text:
        raise SystemExit(f"error: brief contains '*/', cannot emit doc comment: {text!r}")
    return f"/** {text} */"


def split_key(key: str) -> tuple[str, str]:
    root, dot, rest = key.partition(".")
    if not dot or not rest:
        # Dot-less key (e.g. the deprecated bare `state`): mirror the C# emitter,
        # which roots it in its own namespace with the const named after the root.
        return root, root
    return root, rest


def header(registry: dict) -> list[str]:
    lines = [
        "// <auto-generated/>",
        "// Generated by qyl's Weaver pipeline (emit_typespec_keys.py) from:",
    ]
    for source in registry.get("sources", []):
        slug = {
            "core": "open-telemetry/semantic-conventions",
            "genai": "open-telemetry/semantic-conventions-genai",
        }.get(source.get("source_registry", ""), source.get("source_registry", "?"))
        lines.append(
            f"//   {slug} {source.get('source_ref', '?')} ({source.get('source_commit', '?')})"
        )
    lines += [
        f"// Schema: {registry.get('schema_url', '')}",
        f"// GenAI schema: {registry.get('genai_schema_url', '')}",
        "// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)",
        "// </auto-generated>",
        "//",
        "// DO NOT EDIT THIS FILE.",
        "// Regenerate: Qyl.OpenTelemetry.SemanticConventions repo →",
        "//   src/…SourceGeneration/scripts/generate.sh   (refresh resolved-registry.json)",
        "//   src/…SourceGeneration/scripts/emit_typespec_keys.py --write <this file>",
        "",
    ]
    return lines


def emit(registry: dict) -> str:
    by_root: dict[str, list[dict]] = {}
    for attr in registry["catalog"]:
        root, rest = split_key(attr["key"])
        entry = dict(attr)
        entry["_const"] = to_pascal(rest)
        by_root.setdefault(to_pascal(root), []).append(entry)

    lines = header(registry)
    for namespace in sorted(by_root):
        kept, _drops = resolve_collisions(
            by_root[namespace],
            ident_fn=lambda e: e["_const"],
            sort_key_fn=lambda e: e["key"],
        )
        lines.append(f"namespace {KEYS_NAMESPACE}.{namespace} {{")
        for attr in sorted(kept, key=lambda e: e["_const"]):
            doc = doc_line(attr.get("brief", ""))
            if doc:
                lines.append(f"  {doc}")
            dep = attr.get("deprecated")
            if dep is not None:
                lines.append(f'  #deprecated "{tsp_string(deprecated_message(dep))}"')
            lines.append(f'  const {attr["_const"]}: string = "{tsp_string(attr["key"])}";')
        lines.append("}")
    return "\n".join(lines) + "\n"


def main(argv: list[str]) -> None:
    registry = json.load(open(JSON_PATH))
    output = emit(registry)
    if len(argv) == 2 and argv[1] == "--stdout":
        sys.stdout.write(output)
    elif len(argv) == 3 and argv[1] == "--write":
        with open(argv[2], "w") as handle:
            handle.write(output)
        sys.stderr.write(f"Wrote {argv[2]}\n")
    else:
        sys.stderr.write(__doc__)
        sys.exit(2)


if __name__ == "__main__":
    main(sys.argv)
