// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@89aae438b3b3b0a8dd33003c9d70592baf7dbd0d
// Schema: https://opentelemetry.io/schemas/1.43.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

#nullable enable

namespace Qyl.Telemetry.SemanticConventions.Incubating.Attributes.Session;

/// <summary>Session Attributes (incubating).</summary>
public static class SessionAttributes
{
    /// <summary>
    /// A unique id to identify a session.
    /// </summary>
    public const string Id = "session.id";

    /// <summary>
    /// The previous <c>session.id</c> for this user, when known.
    /// </summary>
    public const string PreviousId = "session.previous_id";
}
