using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Qyl.OpenTelemetry.SemanticConventions.SourceGeneration.Emitters;
using Qyl.OpenTelemetry.SemanticConventions.SourceGeneration.Extractors;

namespace Qyl.OpenTelemetry.SemanticConventions.SourceGeneration;

/// <summary>
///   Roslyn incremental source generator for OpenTelemetry semantic-convention
///   event descriptors and payload record-structs. Triggered by
///   <c>[SemanticConventionEvents("&lt;prefix&gt;")]</c> (stable) or
///   <c>[SemanticConventionIncubatingEvents("&lt;prefix&gt;")]</c> (incubating
///   superset). Emits <c>readonly record struct &lt;EventName&gt;Payload</c>
///   types + emission-target descriptors so consumers can call <c>Logger.LogX</c>
///   or <c>Activity.AddEvent</c> with type-checked semconv payloads.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class SemConvEventsGenerator : IIncrementalGenerator
{
    internal const string StableAttributeFullName =
        "Qyl.OpenTelemetry.SemanticConventions.SourceGeneration.SemanticConventionEventsAttribute";

    internal const string IncubatingAttributeFullName =
        "Qyl.OpenTelemetry.SemanticConventions.SourceGeneration.SemanticConventionIncubatingEventsAttribute";

    internal const string AttributeFullName = StableAttributeFullName;

    private const string IsExternalInitSource = """
        // <auto-generated/>
        #nullable enable
        #if !NET5_0_OR_GREATER
        namespace System.Runtime.CompilerServices
        {
            internal static class IsExternalInit
            {
            }
        }
        #endif
        """;

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource("SemanticConventionEventsAttribute.g.cs",
                MarkerAttributeSource.For("SemanticConventionEventsAttribute"));
            ctx.AddSource("SemanticConventionIncubatingEventsAttribute.g.cs",
                MarkerAttributeSource.For("SemanticConventionIncubatingEventsAttribute"));
            ctx.AddSource("SemanticConventionEvents.IsExternalInit.g.cs", IsExternalInitSource);
        });

        var stableMarkers = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                StableAttributeFullName,
                static (node, _) => node is ClassDeclarationSyntax,
                static (ctx, ct) => MarkerExtractor.Extract(ctx, StabilityFilter.StableOnly, ct))
            .WhereNotNull();

        var incubatingMarkers = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                IncubatingAttributeFullName,
                static (node, _) => node is ClassDeclarationSyntax,
                static (ctx, ct) => MarkerExtractor.Extract(ctx, StabilityFilter.AllStabilities, ct))
            .WhereNotNull();

        context.RegisterSourceOutput(stableMarkers, static (spc, marker) =>
        {
            var file = EventsEmitter.Generate(marker, RegistryLoader.Instruments);
            if (!file.IsEmpty)
                spc.AddSource(file.Name, file.Text);
        });

        context.RegisterSourceOutput(incubatingMarkers, static (spc, marker) =>
        {
            var file = EventsEmitter.Generate(marker, RegistryLoader.Instruments);
            if (!file.IsEmpty)
                spc.AddSource(file.Name, file.Text);
        });
    }
}
