using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Qyl.OpenTelemetry.SemanticConventions.SourceGeneration.Emitters;
using Qyl.OpenTelemetry.SemanticConventions.SourceGeneration.Extractors;
using Qyl.OpenTelemetry.SemanticConventions.SourceGeneration.Models;

namespace Qyl.OpenTelemetry.SemanticConventions.SourceGeneration;

/// <summary>
///   Roslyn incremental source generator for OpenTelemetry semantic-convention
///   event descriptors and payload record-structs. Triggered by
///   <c>[SemanticConventionEvents("&lt;prefix&gt;")]</c> (stable) or
///   <c>[SemanticConventionIncubatingEvents("&lt;prefix&gt;")]</c> (incubating
///   superset). Emits <c>readonly record struct &lt;EventName&gt;Payload</c>
///   types + emission-target descriptors so consumers can call <c>Logger.LogX</c>
///   or <c>Activity.AddEvent</c> with type-checked semconv payloads.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class SemConvEventsGenerator : IIncrementalGenerator
{
    internal const string StableAttributeFullName =
        "Qyl.OpenTelemetry.SemanticConventions.SourceGeneration.SemanticConventionEventsAttribute";

    internal const string IncubatingAttributeFullName =
        "Qyl.OpenTelemetry.SemanticConventions.SourceGeneration.SemanticConventionIncubatingEventsAttribute";

    internal const string AttributeFullName = StableAttributeFullName;

    private const string StableAttributeSource = """
        // <auto-generated/>
        #nullable enable
        namespace Qyl.OpenTelemetry.SemanticConventions.SourceGeneration;

        [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
        [global::System.Diagnostics.Conditional("QYL_SEMCONV_USAGES")]
        internal sealed class SemanticConventionEventsAttribute : global::System.Attribute
        {
            public SemanticConventionEventsAttribute(string prefix)
            {
                Prefix = prefix;
            }

            public string Prefix { get; }
        }
        """;

    private const string IncubatingAttributeSource = """
        // <auto-generated/>
        #nullable enable
        namespace Qyl.OpenTelemetry.SemanticConventions.SourceGeneration;

        [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
        [global::System.Diagnostics.Conditional("QYL_SEMCONV_USAGES")]
        internal sealed class SemanticConventionIncubatingEventsAttribute : global::System.Attribute
        {
            public SemanticConventionIncubatingEventsAttribute(string prefix)
            {
                Prefix = prefix;
            }

            public string Prefix { get; }
        }
        """;

    private const string IsExternalInitSource = """
        // <auto-generated/>
        #nullable enable
        #if !NET5_0_OR_GREATER
        namespace System.Runtime.CompilerServices
        {
            internal static class IsExternalInit
            {
            }
        }
        #endif
        """;

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource("SemanticConventionEventsAttribute.g.cs", StableAttributeSource);
            ctx.AddSource("SemanticConventionIncubatingEventsAttribute.g.cs", IncubatingAttributeSource);
            ctx.AddSource("SemanticConventionEvents.IsExternalInit.g.cs", IsExternalInitSource);
        });

        var stableMarkers = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                StableAttributeFullName,
                static (node, _) => node is ClassDeclarationSyntax,
                static (ctx, ct) => ExtractMarker(ctx, StabilityFilter.StableOnly, ct))
            .WhereNotNull();

        var incubatingMarkers = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                IncubatingAttributeFullName,
                static (node, _) => node is ClassDeclarationSyntax,
                static (ctx, ct) => ExtractMarker(ctx, StabilityFilter.AllStabilities, ct))
            .WhereNotNull();

        context.RegisterSourceOutput(stableMarkers, static (spc, marker) =>
        {
            var file = EventsEmitter.Generate(marker, RegistryLoader.Instruments);
            if (!file.IsEmpty)
                spc.AddSource(file.Name, file.Text);
        });

        context.RegisterSourceOutput(incubatingMarkers, static (spc, marker) =>
        {
            var file = EventsEmitter.Generate(marker, RegistryLoader.Instruments);
            if (!file.IsEmpty)
                spc.AddSource(file.Name, file.Text);
        });
    }

    private static EventsMarkerModel? ExtractMarker(
        GeneratorAttributeSyntaxContext context,
        StabilityFilter filter,
        CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();

        if (context.TargetSymbol is not INamedTypeSymbol typeSymbol)
            return null;

        var attributeData = context.Attributes.FirstOrDefault();
        if (attributeData is null || attributeData.ConstructorArguments.Length == 0)
            return null;

        if (attributeData.ConstructorArguments[0].Value is not string prefix)
            return null;

        if (string.IsNullOrWhiteSpace(prefix))
            return null;

        var ns = typeSymbol.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : typeSymbol.ContainingNamespace.ToDisplayString();

        return new EventsMarkerModel(ns, typeSymbol.Name, prefix, filter);
    }
}
