namespace Qyl.Telemetry.SemanticConventions.SourceGeneration.Emitters;

/// <summary>
/// Post-initialization source for the first-class metric-definition runtime types —
/// the single metric surface of the library. A semantic-convention metric is a typed
/// object: the canonical name is one property, the instrument is a marker TYPE (so an
/// instrument/definition mismatch is a compile error), and unit, stability, entity
/// references, attribute references, and structured deprecation all travel with it.
/// BCL-only, allocation-light, NativeAOT/trim safe (no reflection).
/// </summary>
internal static class MetricDefinitionSupportSource
{
    public const string FileName = "MetricDefinition.Support.g.cs";

    public const string Source = """
        // <auto-generated/>
        #nullable enable
        namespace Qyl.Telemetry.SemanticConventions;

        using global::System.Collections.Generic;

        /// <summary>The kind of change that deprecated a semantic convention.</summary>
        public enum MigrationKind { None, Renamed, Obsoleted, Uncategorized }

        /// <summary>
        /// Structured deprecation projected verbatim from the upstream Weaver model
        /// (<c>reason: renamed</c> with <c>renamed_to</c>, <c>obsoleted</c>, or an
        /// uncategorized note). <see cref="Replacement"/> is null unless the upstream
        /// data gives an exact rename target — a deprecation does not imply a successor.
        /// </summary>
        public sealed class Deprecation
        {
            private Deprecation(MigrationKind kind, string? replacement, string? note)
            {
                Kind = kind; Replacement = replacement; Note = note;
            }

            /// <summary>The convention is current; not deprecated.</summary>
            public static readonly Deprecation None = new(MigrationKind.None, null, null);

            /// <summary>Renamed with an exact 1:1 successor that is safe to auto-map.</summary>
            public static Deprecation Renamed(string replacement) => new(MigrationKind.Renamed, replacement, null);

            /// <summary>Removed with no replacement at this time.</summary>
            public static readonly Deprecation Obsoleted = new(MigrationKind.Obsoleted, null, null);

            /// <summary>Deprecated for an upstream-uncategorized reason; no machine-readable target.</summary>
            public static Deprecation Uncategorized(string note) => new(MigrationKind.Uncategorized, null, note);

            public MigrationKind Kind { get; }

            /// <summary>The exact rename target, or null when none exists (obsoleted/uncategorized).</summary>
            public string? Replacement { get; }

            /// <summary>Free-text upstream note for uncategorized deprecations, else null.</summary>
            public string? Note { get; }

            /// <summary>True unless this is <see cref="None"/>.</summary>
            public bool IsDeprecated => Kind != MigrationKind.None;
        }

        /// <summary>Stability tier of a semantic convention.</summary>
        public enum Stability { Stable, ReleaseCandidate, Beta, Alpha, Development, Deprecated }

        /// <summary>Requirement level of an attribute on a signal.</summary>
        public enum RequirementLevel { Unspecified, Required, Recommended, OptIn, ConditionallyRequired }

        /// <summary>
        /// A reference to an attribute carried by a metric, preserving the upstream
        /// requirement level and whether the attribute itself is deprecated.
        /// </summary>
        public sealed class AttributeRef
        {
            public AttributeRef(string name, string type, RequirementLevel requirementLevel, bool isDeprecated)
            {
                Name = name; Type = type; RequirementLevel = requirementLevel; IsDeprecated = isDeprecated;
            }

            /// <summary>The attribute key (e.g. <c>disk.io.direction</c>).</summary>
            public string Name { get; }

            /// <summary>The attribute value type (<c>string</c>, <c>int</c>, <c>enum</c>, <c>template</c>, …).</summary>
            public string Type { get; }

            public RequirementLevel RequirementLevel { get; }

            public bool IsDeprecated { get; }
        }

        /// <summary>
        /// A reference to an entity a metric is associated with. Carries the entity type
        /// name from the registry; the full entity definition (its identity attributes)
        /// lives with the entity conventions.
        /// </summary>
        public sealed class EntityRef
        {
            public EntityRef(string type) => Type = type;

            /// <summary>The entity type name (e.g. <c>process</c>, <c>host</c>).</summary>
            public string Type { get; }

            public override string ToString() => Type;
        }

        /// <summary>
        /// Marker types for the metric instrument. A metric definition is generic over one
        /// of these, so an API that only accepts <c>MetricDefinition&lt;Counter&gt;</c>
        /// rejects a gauge definition at compile time.
        /// </summary>
        public interface IInstrument { static abstract string Kind { get; } }
        public readonly struct Counter : IInstrument { public static string Kind => "counter"; }
        public readonly struct UpDownCounter : IInstrument { public static string Kind => "updowncounter"; }
        public readonly struct Gauge : IInstrument { public static string Kind => "gauge"; }
        public readonly struct Histogram : IInstrument { public static string Kind => "histogram"; }

        /// <summary>
        /// A semantic-convention metric as a first-class object: the canonical name is a
        /// property, and the instrument, unit, entity references, attribute references,
        /// stability, brief, and structured deprecation travel with it. Generic over the
        /// instrument marker type for compile-time instrument safety.
        /// </summary>
        public sealed class MetricDefinition<TInstrument> where TInstrument : struct, IInstrument
        {
            public MetricDefinition(
                string name, string unit, string brief,
                Stability stability, Deprecation deprecation,
                IReadOnlyList<EntityRef> entities, IReadOnlyList<AttributeRef> attributes)
            {
                Name = name; Unit = unit; Brief = brief;
                Stability = stability; Deprecation = deprecation;
                Entities = entities; Attributes = attributes;
            }

            /// <summary>The canonical OpenTelemetry metric name.</summary>
            public string Name { get; }

            /// <summary>The instrument kind (e.g. <c>counter</c>), from the marker type.</summary>
            public string Instrument => TInstrument.Kind;

            /// <summary>The unit, verbatim from the registry (e.g. <c>{thread}</c>, <c>1</c>).</summary>
            public string Unit { get; }

            /// <summary>Human-readable brief.</summary>
            public string Brief { get; }

            public Stability Stability { get; }

            /// <summary>Structured deprecation; <see cref="Deprecation.None"/> when current.</summary>
            public Deprecation Deprecation { get; }

            /// <summary>Entities this metric is associated with (e.g. <c>process</c>, <c>host</c>).</summary>
            public IReadOnlyList<EntityRef> Entities { get; }

            /// <summary>Attributes this metric carries, with requirement levels.</summary>
            public IReadOnlyList<AttributeRef> Attributes { get; }

            public override string ToString() => Name;
        }
        """;
}
