using Qyl.Telemetry.SemanticConventions.SourceGeneration.Extractors;
using Qyl.Telemetry.SemanticConventions.SourceGeneration.Models;

namespace Qyl.Telemetry.SemanticConventions.SourceGeneration.Emitters;

/// <summary>
/// Emits the compiled-package projection of the <em>qyl-owned</em> instruments: one
/// <c>public static class {Root}MetricAttributes</c> per registry root that owns one, under
/// <c>{package root}.Attributes.{Root}</c>, carrying each instrument's name and its unit as
/// <c>const string</c>.
/// </summary>
/// <remarks>
/// <para>
/// Only rows the registry attributes to qyl are projected. An upstream instrument belongs to
/// OpenTelemetry and reaches a consumer as a <c>MetricDefinition</c> or through the embedded
/// registry; a qyl-owned instrument is qyl's own vocabulary, and the components that create it —
/// the collector included — must not spell it as a literal. That is the same reason
/// <see cref="TelemetryNamesEmitter"/> exists for scope and event names.
/// </para>
/// <para>
/// The class name ends in <c>Attributes</c> and sits under <c>.Attributes.</c> deliberately: the
/// qyl collector may not reference this package family and builds its vocabulary by reflecting
/// over exactly those types' <c>const string</c> members. A name it cannot see is a name it would
/// have to hard-code.
/// </para>
/// </remarks>
internal static class PackageInstrumentsEmitter
{
    private const string Pad = "    ";
    private const string QylSourceRegistry = "qyl";

    public static EquatableArray<FileWithName> Generate(SemConvPackageMarkerModel marker, InstrumentRegistryModel instruments)
    {
        var byRoot = new Dictionary<string, List<MetricDescriptorModel>>(StringComparer.Ordinal);
        foreach (var metric in instruments.Metrics)
        {
            if (metric.SourceRegistry != QylSourceRegistry)
                continue;
            if (!StabilityFiltering.IsIncludedOrDeprecated(metric.Stability, metric.Deprecated, marker.Filter))
                continue;

            var root = RootOf(metric.MetricName);
            if (!byRoot.TryGetValue(root, out var list))
            {
                list = new List<MetricDescriptorModel>();
                byRoot.Add(root, list);
            }
            list.Add(metric);
        }

        var roots = new List<string>(byRoot.Keys);
        roots.Sort(StringComparer.Ordinal);

        var files = new List<FileWithName>(roots.Count);
        foreach (var root in roots)
            files.Add(EmitRoot(marker.RootNamespace, root, byRoot[root]));

        return files.ToEquatableArray();
    }

    private static string RootOf(string metricName)
    {
        var dot = metricName.IndexOf('.');
        return dot < 0 ? metricName : metricName.Substring(0, dot);
    }

    private static string MemberName(string root, string metricName) =>
        SourceWriter.ToPascalCase(metricName.Length > root.Length ? metricName.Substring(root.Length + 1) : metricName);

    private static FileWithName EmitRoot(string rootNamespace, string root, List<MetricDescriptorModel> metrics)
    {
        var pascalRoot = SourceWriter.ToPascalCase(root);
        var className = pascalRoot + "MetricAttributes";
        var ns = rootNamespace + ".Attributes." + pascalRoot;

        metrics.Sort(static (a, b) => StringComparer.Ordinal.Compare(a.MetricName, b.MetricName));

        var w = new PackageSourceWriter();
        w.Line("// <auto-generated/>");
        w.Line("// Generated by qyl's emitter from the qyl-owned registry");
        w.Line("// Source: SourceGeneration/Resources/qyl-registry.json");
        w.Line("// Licensed under Apache-2.0");
        w.Line("// </auto-generated>");
        w.Line();
        w.Line("// Copyright (c) 2025-2026 ancplua");
        w.Line();
        w.Line("#nullable enable");
        w.Line();
        w.Line("namespace " + ns + ";");
        w.Line();
        w.Line("/// <summary>" + pascalRoot + " qyl-owned instrument names and units (incubating).</summary>");
        w.Line("public static class " + className);
        w.Line("{");

        var first = true;
        foreach (var metric in metrics)
        {
            if (!first)
                w.Line();
            first = false;

            var memberName = MemberName(root, metric.MetricName);
            var brief = metric.Brief.TrimEnd('\n');
            w.Summary(Pad, brief.Length > 0 ? PackageDocComments.RenderInline(brief).Split('\n') : Array.Empty<string>());

            var noteLines = PackageDocComments.RenderMarkdown(metric.Note);
            if (noteLines.Count > 0)
                w.Remarks(Pad, noteLines);

            w.Line(Pad + "public const string " + memberName + " = \"" + metric.MetricName + "\";");
            w.Line();
            w.Summary(Pad, new[] { "Unit of the <c>" + SourceWriter.EscapeAttribute(metric.MetricName) + "</c> instrument." });
            w.Line(Pad + "public const string " + memberName + "Unit = \"" + metric.Unit + "\";");
        }

        w.Line("}");

        return new FileWithName(GeneratedSourceNames.ForPartialType(ns, className), w.ToString());
    }
}
