using Qyl.Telemetry.SemanticConventions.SourceGeneration.Models;

namespace Qyl.Telemetry.SemanticConventions.SourceGeneration.Emitters;

/// <summary>
/// Emits the telemetry names the registry knows — the <c>ActivitySource</c>/<c>Meter</c> scope
/// names qyl constructs, the <c>ActivitySource</c> names of the pinned third-party libraries qyl
/// subscribes to, and the qyl-owned <c>Activity</c>/<c>DiagnosticSource</c> event names — as
/// <c>{package root}.Names.QylTelemetryNames</c>. The same registry input drives the QYL0200
/// analyzer allowlist, so a name referenced through these constants is a name the analyzer
/// accepts and the collector recognises.
/// </summary>
/// <remarks>
/// The vendor names are the exact strings the pinned libraries construct their sources with, read
/// from their source at the pinned tag and declared in <c>qyl-registry.json</c>'s vendor models:
/// <c>AddSource</c> and a span processor's source match take them from here rather than repeating
/// a literal.
/// </remarks>
internal static class TelemetryNamesEmitter
{
    private const string ClassName = "QylTelemetryNames";
    private const string Pad = "    ";

    public static EquatableArray<FileWithName> Generate(SemConvPackageMarkerModel marker, RegistryModel registry)
    {
        var ns = marker.RootNamespace + ".Names";
        var scopes = NameMembers(registry.ScopeNames, "scope name");
        var vendorSources = NameMembers(registry.VendorScopeNames, "vendor activity source name");
        var events = NameMembers(registry.EventNames, "event name");

        var w = new PackageSourceWriter();
        w.Line("// <auto-generated/>");
        w.Line("// Generated by qyl's emitter from the qyl-owned registry");
        w.Line("// Source: SourceGeneration/Resources/qyl-registry.json");
        w.Line("// Licensed under Apache-2.0");
        w.Line("// </auto-generated>");
        w.Line();
        w.Line("// Copyright (c) 2025-2026 ancplua");
        w.Line();
        w.Line("#nullable enable");
        w.Line();
        w.Line("namespace " + ns + ";");
        w.Line();
        w.Line("/// <summary>qyl-owned telemetry names.</summary>");
        w.Line("/// <remarks>");
        w.Line("/// The same registry input drives the QYL0200 analyzer allowlist, so a name");
        w.Line("/// referenced through these constants is a name the analyzer accepts and the");
        w.Line("/// collector recognises.");
        w.Line("/// </remarks>");
        w.Line("public static class " + ClassName);
        w.Line("{");

        WriteGroup(w, "Scopes", "Names of the <c>ActivitySource</c> and <c>Meter</c> scopes qyl constructs.", "telemetry scope", scopes);
        w.Line();
        WriteGroup(
            w,
            "VendorActivitySources",
            "Names of the <c>ActivitySource</c>s of the pinned third-party libraries qyl subscribes to.",
            "vendor activity source",
            vendorSources);
        w.Line();
        WriteGroup(w, "Events", "Names of qyl-owned <c>Activity</c> and <c>DiagnosticSource</c> events.", "telemetry event", events);

        w.Line("}");

        var file = new FileWithName(GeneratedSourceNames.ForPartialType(ns, ClassName), w.ToString());
        return new[] { file }.ToEquatableArray();
    }

    private static void WriteGroup(
        PackageSourceWriter w,
        string className,
        string summary,
        string kind,
        List<(string Identifier, string Value)> members)
    {
        var innerPad = Pad + Pad;
        w.Summary(Pad, new[] { summary });
        w.Line(Pad + "public static class " + className);
        w.Line(Pad + "{");
        var first = true;
        foreach (var (identifier, value) in members)
        {
            if (!first)
                w.Line();
            first = false;
            w.Summary(innerPad, new[] { "The <c>" + SourceWriter.EscapeAttribute(value) + "</c> " + kind + "." });
            w.Line(innerPad + "public const string " + identifier + " = " + PackageSourceWriter.CSharpString(value) + ";");
        }
        w.Line(Pad + "}");
    }

    /// <summary>One PascalCase identifier per distinct name, ordinally sorted; identifiers must be unique.</summary>
    private static List<(string Identifier, string Value)> NameMembers(EquatableArray<string> values, string what)
    {
        var distinct = new SortedSet<string>(StringComparer.Ordinal);
        foreach (var value in values)
            distinct.Add(value);

        var members = new List<(string, string)>(distinct.Count);
        var seen = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (var value in distinct)
        {
            var identifier = SourceWriter.ToPascalCase(value);
            if (seen.TryGetValue(identifier, out var other))
                throw new InvalidOperationException($"{what} '{value}' and '{other}' both map to identifier '{identifier}'.");
            seen.Add(identifier, value);
            members.Add((identifier, value));
        }
        return members;
    }
}
