// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@e10a930844c6951757a43b849d364f7d056ac32b
// Schema: https://opentelemetry.io/schemas/1.44.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

#nullable enable

namespace Qyl.Telemetry.SemanticConventions.Incubating.Attributes.Peer;

/// <summary>Peer Attributes (incubating).</summary>
public static class PeerAttributes
{
    /// <summary>
    /// The <a href="/docs/resource/README.md#service">`service.name`</a> of the remote service. SHOULD be equal to the actual <c>service.name</c> resource attribute of the remote service if any.
    /// </summary>
    /// <remarks>
    /// Examples of <c>peer.service</c> that users may specify:
    /// <para/>
    /// - A Redis cache of auth tokens as <c>peer.service="AuthTokenCache"</c>.
    /// - A gRPC service <c>rpc.service="io.opentelemetry.AuthService"</c> may be hosted in both a gateway, <c>peer.service="ExternalApiService"</c> and a backend, <c>peer.service="AuthService"</c>.
    /// </remarks>
    [global::System.Obsolete("Replaced by service.peer.name.", false)]
    public const string Service = "peer.service";
}
