// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@89aae438b3b3b0a8dd33003c9d70592baf7dbd0d
// Schema: https://opentelemetry.io/schemas/1.43.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

#nullable enable

namespace Qyl.OpenTelemetry.SemanticConventions.Incubating.Attributes.Elasticsearch;

/// <summary>Elasticsearch Attributes (incubating).</summary>
public static class ElasticsearchAttributes
{
    /// <summary>
    /// Represents the human-readable identifier of the node/instance to which a request was routed.
    /// </summary>
    public const string NodeName = "elasticsearch.node.name";
}
