// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@e10a930844c6951757a43b849d364f7d056ac32b
// Schema: https://opentelemetry.io/schemas/1.44.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

#nullable enable

namespace Qyl.Telemetry.SemanticConventions.Incubating.Attributes.Nodejs;

/// <summary>Nodejs Attributes (incubating).</summary>
public static class NodejsAttributes
{
    /// <summary>
    /// The state of event loop time.
    /// </summary>
    public const string EventloopState = "nodejs.eventloop.state";

    /// <summary>
    /// Values for the <c>EventloopState</c> attribute.
    /// </summary>
    public static class EventloopStateValues
    {
        /// <summary>
        /// Active time.
        /// </summary>
        public const string Active = "active";

        /// <summary>
        /// Idle time.
        /// </summary>
        public const string Idle = "idle";
    }
}
