// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@e10a930844c6951757a43b849d364f7d056ac32b
// Schema: https://opentelemetry.io/schemas/1.44.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

#nullable enable

namespace Qyl.Telemetry.SemanticConventions.Incubating.Attributes.Oci;

/// <summary>Oci Attributes (incubating).</summary>
public static class OciAttributes
{
    /// <summary>
    /// The digest of the OCI image manifest. For container images specifically is the digest by which the container image is known.
    /// </summary>
    /// <remarks>
    /// Follows <a href="https://github.com/opencontainers/image-spec/blob/main/manifest.md">OCI Image Manifest Specification</a>, and specifically the <a href="https://github.com/opencontainers/image-spec/blob/main/descriptor.md#digests">Digest property</a>.
    /// An example can be found in <a href="https://github.com/opencontainers/image-spec/blob/main/manifest.md#example-image-manifest">Example Image Manifest</a>.
    /// </remarks>
    public const string ManifestDigest = "oci.manifest.digest";
}
