//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qyl.Telemetry.SemanticConventions.Analyzers {
    using System;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CodeFixResources {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CodeFixResources() {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Qyl.Telemetry.SemanticConventions.Analyzers.CodeFixResources", typeof(CodeFixResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static string QYL0500CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0500CodeFixTitle", resourceCulture);
            }
        }

        internal static string QYL0501CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0501CodeFixTitle", resourceCulture);
            }
        }

        internal static string QYL0102CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0102CodeFixTitle", resourceCulture);
            }
        }

        internal static string QYL0106CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0106CodeFixTitle", resourceCulture);
            }
        }

        internal static string QYL0107CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0107CodeFixTitle", resourceCulture);
            }
        }

        internal static string QYL0108CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0108CodeFixTitle", resourceCulture);
            }
        }

        internal static string QYL0109CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0109CodeFixTitle", resourceCulture);
            }
        }

        internal static string QYL0405CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0405CodeFixTitle", resourceCulture);
            }
        }
    }
}
