// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@e10a930844c6951757a43b849d364f7d056ac32b
// Schema: https://opentelemetry.io/schemas/1.44.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

#nullable enable

namespace Qyl.Telemetry.SemanticConventions.Attributes.Telemetry;

/// <summary>Telemetry Attributes.</summary>
public static class TelemetryAttributes
{
    /// <summary>
    /// The name of the auto instrumentation agent or distribution, if used.
    /// </summary>
    /// <remarks>
    /// Official auto instrumentation agents and distributions SHOULD set the <c>telemetry.distro.name</c> attribute to
    /// a string starting with <c>opentelemetry-</c>, e.g. <c>opentelemetry-java-instrumentation</c>.
    /// </remarks>
    public const string DistroName = "telemetry.distro.name";

    /// <summary>
    /// The version string of the auto instrumentation agent or distribution, if used.
    /// </summary>
    public const string DistroVersion = "telemetry.distro.version";

    /// <summary>
    /// The language of the telemetry SDK.
    /// </summary>
    public const string SdkLanguage = "telemetry.sdk.language";

    /// <summary>
    /// Values for the <c>SdkLanguage</c> attribute.
    /// </summary>
    public static class SdkLanguageValues
    {
        /// <summary>
        /// <a href="https://opentelemetry.io/docs/languages/cpp/">C++</a>.
        /// </summary>
        public const string Cpp = "cpp";

        /// <summary>
        /// <a href="https://opentelemetry.io/docs/languages/dotnet/">.NET</a>.
        /// </summary>
        public const string Dotnet = "dotnet";

        /// <summary>
        /// <a href="https://opentelemetry.io/docs/languages/erlang/">Erlang/Elixir</a>.
        /// </summary>
        public const string Erlang = "erlang";

        /// <summary>
        /// <a href="https://opentelemetry.io/docs/languages/go/">Go</a>.
        /// </summary>
        public const string Go = "go";

        /// <summary>
        /// <a href="https://opentelemetry.io/docs/languages/java/">Java</a>.
        /// </summary>
        public const string Java = "java";

        /// <summary>
        /// <a href="https://opentelemetry.io/docs/languages/kotlin/">Kotlin</a>.
        /// </summary>
        public const string Kotlin = "kotlin";

        /// <summary>
        /// <a href="https://opentelemetry.io/docs/languages/js/">Node.js</a>.
        /// </summary>
        public const string Nodejs = "nodejs";

        /// <summary>
        /// <a href="https://opentelemetry.io/docs/languages/php/">PHP</a>.
        /// </summary>
        public const string Php = "php";

        /// <summary>
        /// <a href="https://opentelemetry.io/docs/languages/python/">Python</a>.
        /// </summary>
        public const string Python = "python";

        /// <summary>
        /// <a href="https://opentelemetry.io/docs/languages/ruby/">Ruby</a>.
        /// </summary>
        public const string Ruby = "ruby";

        /// <summary>
        /// <a href="https://opentelemetry.io/docs/languages/rust/">Rust</a>.
        /// </summary>
        public const string Rust = "rust";

        /// <summary>
        /// <a href="https://opentelemetry.io/docs/languages/swift/">Swift</a>.
        /// </summary>
        public const string Swift = "swift";

        /// <summary>
        /// <a href="https://opentelemetry.io/docs/languages/js/">Browser</a>.
        /// </summary>
        public const string Webjs = "webjs";
    }

    /// <summary>
    /// The name of the telemetry SDK as defined above.
    /// </summary>
    /// <remarks>
    /// The OpenTelemetry SDK MUST set the <c>telemetry.sdk.name</c> attribute to <c>opentelemetry</c>.
    /// If another SDK, like a fork or a vendor-provided implementation, is used, this SDK MUST set the
    /// <c>telemetry.sdk.name</c> attribute to the fully-qualified class or module name of this SDK's main entry point
    /// or another suitable identifier depending on the language.
    /// The identifier <c>opentelemetry</c> is reserved and MUST NOT be used in this case.
    /// All custom identifiers SHOULD be stable across different versions of an implementation.
    /// </remarks>
    public const string SdkName = "telemetry.sdk.name";

    /// <summary>
    /// The version string of the telemetry SDK.
    /// </summary>
    public const string SdkVersion = "telemetry.sdk.version";
}
