// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@89aae438b3b3b0a8dd33003c9d70592baf7dbd0d
// Schema: https://opentelemetry.io/schemas/1.43.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

#nullable enable

namespace Qyl.OpenTelemetry.SemanticConventions.Incubating.Attributes.Deployment;

/// <summary>Deployment Attributes (incubating).</summary>
public static class DeploymentAttributes
{
    /// <summary>
    /// Deprecated, use <c>deployment.environment.name</c> instead.
    /// </summary>
    [global::System.Obsolete("Replaced by deployment.environment.name.", false)]
    public const string Environment = "deployment.environment";

    /// <summary>
    /// Name of the <a href="https://wikipedia.org/wiki/Deployment_environment">deployment environment</a> (aka deployment tier).
    /// </summary>
    /// <remarks>
    /// <c>deployment.environment.name</c> does not affect the uniqueness constraints defined through
    /// the <c>service.namespace</c>, <c>service.name</c> and <c>service.instance.id</c> resource attributes.
    /// This implies that resources carrying the following attribute combinations MUST be
    /// considered to be identifying the same service:
    /// <para/>
    /// - <c>service.name=frontend</c>, <c>deployment.environment.name=production</c>
    /// - <c>service.name=frontend</c>, <c>deployment.environment.name=staging</c>.
    /// </remarks>
    public const string EnvironmentName = "deployment.environment.name";

    /// <summary>
    /// Values for the <c>EnvironmentName</c> attribute.
    /// </summary>
    public static class EnvironmentNameValues
    {
        /// <summary>
        /// Development environment.
        /// </summary>
        public const string Development = "development";

        /// <summary>
        /// Production environment.
        /// </summary>
        public const string Production = "production";

        /// <summary>
        /// Staging environment.
        /// </summary>
        public const string Staging = "staging";

        /// <summary>
        /// Testing environment.
        /// </summary>
        public const string Test = "test";
    }

    /// <summary>
    /// The id of the deployment.
    /// </summary>
    public const string Id = "deployment.id";

    /// <summary>
    /// The name of the deployment.
    /// </summary>
    public const string Name = "deployment.name";

    /// <summary>
    /// The status of the deployment.
    /// </summary>
    public const string Status = "deployment.status";

    /// <summary>
    /// Values for the <c>Status</c> attribute.
    /// </summary>
    public static class StatusValues
    {
        /// <summary>
        /// failed.
        /// </summary>
        public const string Failed = "failed";

        /// <summary>
        /// succeeded.
        /// </summary>
        public const string Succeeded = "succeeded";
    }
}
