// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@e10a930844c6951757a43b849d364f7d056ac32b
// Schema: https://opentelemetry.io/schemas/1.44.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

#nullable enable

namespace Qyl.Telemetry.SemanticConventions.Incubating.Attributes.App;

/// <summary>App Attributes (incubating).</summary>
public static class AppAttributes
{
    /// <summary>
    /// Unique identifier for a particular build or compilation of the application.
    /// </summary>
    public const string BuildId = "app.build_id";

    /// <summary>
    /// A unique identifier representing an instance of an end user facing app crash.
    /// </summary>
    /// <remarks>
    /// Its value MAY be meaningful and be used as a reference for telemetry and metadata recorded by
    /// the same instrumentation (e.g. it is an ID generated by an external source that captured the crash).
    /// It MAY come from a source external to the instrumentation such that it can be used to look up additional
    /// data from other sources as well as facilitate deduplication.
    /// </remarks>
    public const string CrashId = "app.crash.id";

    /// <summary>
    /// A unique identifier representing the installation of an application on a specific device
    /// </summary>
    /// <remarks>
    /// Its value SHOULD persist across launches of the same application installation, including through application upgrades.
    /// It SHOULD change if the application is uninstalled or if all applications of the vendor are uninstalled.
    /// Additionally, users might be able to reset this value (e.g. by clearing application data).
    /// If an app is installed multiple times on the same device (e.g. in different accounts on Android), each <c>app.installation.id</c> SHOULD have a different value.
    /// If multiple OpenTelemetry SDKs are used within the same application, they SHOULD use the same value for <c>app.installation.id</c>.
    /// Hardware IDs (e.g. serial number, IMEI, MAC address) MUST NOT be used as the <c>app.installation.id</c>.
    /// <para/>
    /// For iOS, this value SHOULD be equal to the <a href="https://developer.apple.com/documentation/uikit/uidevice/identifierforvendor">vendor identifier</a>.
    /// <para/>
    /// For Android, examples of <c>app.installation.id</c> implementations include:
    /// <para/>
    /// - <a href="https://firebase.google.com/docs/projects/manage-installations">Firebase Installation ID</a>.
    /// - A globally unique UUID which is persisted across sessions in your application.
    /// - <a href="https://developer.android.com/identity/app-set-id">App set ID</a>.
    /// - <a href="https://developer.android.com/reference/android/provider/Settings.Secure#ANDROID_ID">`Settings.getString(Settings.Secure.ANDROID_ID)`</a>.
    /// <para/>
    /// More information about Android identifier best practices can be found in the <a href="https://developer.android.com/training/articles/user-data-ids">Android user data IDs guide</a>.
    /// </remarks>
    public const string InstallationId = "app.installation.id";

    /// <summary>
    /// A number of frame renders that experienced jank.
    /// </summary>
    /// <remarks>
    /// Depending on platform limitations, the value provided MAY be approximation.
    /// </remarks>
    public const string JankFrameCount = "app.jank.frame_count";

    /// <summary>
    /// The time period, in seconds, for which this jank is being reported.
    /// </summary>
    public const string JankPeriod = "app.jank.period";

    /// <summary>
    /// The minimum rendering threshold for this jank, in seconds.
    /// </summary>
    public const string JankThreshold = "app.jank.threshold";

    /// <summary>
    /// The x (horizontal) coordinate of a screen coordinate, in screen pixels.
    /// </summary>
    public const string ScreenCoordinateX = "app.screen.coordinate.x";

    /// <summary>
    /// The y (vertical) component of a screen coordinate, in screen pixels.
    /// </summary>
    public const string ScreenCoordinateY = "app.screen.coordinate.y";

    /// <summary>
    /// An identifier that uniquely differentiates this screen from other screens in the same application.
    /// </summary>
    /// <remarks>
    /// A screen represents only the part of the device display drawn by the app. It typically contains multiple widgets or UI components and is larger in scope than individual widgets. Multiple screens can coexist on the same display simultaneously (e.g., split view on tablets).
    /// </remarks>
    public const string ScreenId = "app.screen.id";

    /// <summary>
    /// The name of an application screen.
    /// </summary>
    /// <remarks>
    /// A screen represents only the part of the device display drawn by the app. It typically contains multiple widgets or UI components and is larger in scope than individual widgets. Multiple screens can coexist on the same display simultaneously (e.g., split view on tablets).
    /// </remarks>
    public const string ScreenName = "app.screen.name";

    /// <summary>
    /// An identifier that uniquely differentiates this widget from other widgets in the same application.
    /// </summary>
    /// <remarks>
    /// A widget is an application component, typically an on-screen visual GUI element.
    /// </remarks>
    public const string WidgetId = "app.widget.id";

    /// <summary>
    /// The name of an application widget.
    /// </summary>
    /// <remarks>
    /// A widget is an application component, typically an on-screen visual GUI element.
    /// </remarks>
    public const string WidgetName = "app.widget.name";
}
