// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@e10a930844c6951757a43b849d364f7d056ac32b
// Schema: https://opentelemetry.io/schemas/1.44.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

#nullable enable

namespace Qyl.Telemetry.SemanticConventions.Attributes.Linux;

/// <summary>Linux Attributes.</summary>
public static class LinuxAttributes
{
    /// <summary>
    /// The Linux Slab memory state
    /// </summary>
    [global::System.Obsolete("Replaced by system.memory.linux.slab.state.", false)]
    public const string MemorySlabState = "linux.memory.slab.state";
}
