// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@89aae438b3b3b0a8dd33003c9d70592baf7dbd0d
// Schema: https://opentelemetry.io/schemas/1.43.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

#nullable enable

namespace Qyl.Telemetry.SemanticConventions.Incubating.Attributes.Disk;

/// <summary>Disk Attributes (incubating).</summary>
public static class DiskAttributes
{
    /// <summary>
    /// The disk IO operation direction.
    /// </summary>
    public const string IoDirection = "disk.io.direction";

    /// <summary>
    /// Values for the <c>IoDirection</c> attribute.
    /// </summary>
    public static class IoDirectionValues
    {
        /// <summary>
        /// read.
        /// </summary>
        public const string Read = "read";

        /// <summary>
        /// write.
        /// </summary>
        public const string Write = "write";
    }
}
