// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@89aae438b3b3b0a8dd33003c9d70592baf7dbd0d
// Schema: https://opentelemetry.io/schemas/1.43.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

namespace Qyl.OpenTelemetry.SemanticConventions;

/// <summary>Schema URL for OpenTelemetry Semantic Conventions 1.43.0.</summary>
public static partial class SchemaUrl
{
    /// <summary>The schema URL for OTel semconv 1.43.0.</summary>
    public const string Current = "https://opentelemetry.io/schemas/1.43.0";
}
