// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@e10a930844c6951757a43b849d364f7d056ac32b
// Schema: https://opentelemetry.io/schemas/1.44.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

#nullable enable

namespace Qyl.Telemetry.SemanticConventions.Incubating.Attributes.Enduser;

/// <summary>Enduser Attributes (incubating).</summary>
public static class EnduserAttributes
{
    /// <summary>
    /// Unique identifier of an end user in the system. It maybe a username, email address, or other identifier.
    /// </summary>
    /// <remarks>
    /// Unique identifier of an end user in the system.
    /// <para/>
    /// Warning:
    /// This field contains sensitive (PII) information.
    /// </remarks>
    public const string Id = "enduser.id";

    /// <summary>
    /// Pseudonymous identifier of an end user. This identifier should be a random value that is not directly linked or associated with the end user's actual identity.
    /// </summary>
    /// <remarks>
    /// Pseudonymous identifier of an end user.
    /// <para/>
    /// Warning:
    /// This field contains sensitive (linkable PII) information.
    /// </remarks>
    public const string PseudoId = "enduser.pseudo.id";

    /// <summary>
    /// Deprecated, use <c>user.roles</c> instead.
    /// </summary>
    [global::System.Obsolete("Use `user.roles` instead.", false)]
    public const string Role = "enduser.role";

    /// <summary>
    /// Deprecated, no replacement at this time.
    /// </summary>
    [global::System.Obsolete("Removed, no replacement.", false)]
    public const string Scope = "enduser.scope";
}
