// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@89aae438b3b3b0a8dd33003c9d70592baf7dbd0d
// Schema: https://opentelemetry.io/schemas/1.43.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

#nullable enable

namespace Qyl.OpenTelemetry.SemanticConventions.Incubating.Attributes.Linux;

/// <summary>Linux Attributes (incubating).</summary>
public static class LinuxAttributes
{
    /// <summary>
    /// The Linux Slab memory state
    /// </summary>
    [global::System.Obsolete("Replaced by system.memory.linux.slab.state.", false)]
    public const string MemorySlabState = "linux.memory.slab.state";

    /// <summary>
    /// Values for the <c>MemorySlabState</c> attribute.
    /// </summary>
    public static class MemorySlabStateValues
    {
        /// <summary>
        /// reclaimable.
        /// </summary>
        public const string Reclaimable = "reclaimable";

        /// <summary>
        /// unreclaimable.
        /// </summary>
        public const string Unreclaimable = "unreclaimable";
    }
}
