// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@e10a930844c6951757a43b849d364f7d056ac32b
// Schema: https://opentelemetry.io/schemas/1.44.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

#nullable enable

namespace Qyl.Telemetry.SemanticConventions.Incubating.Attributes.Mainframe;

/// <summary>Mainframe Attributes (incubating).</summary>
public static class MainframeAttributes
{
    /// <summary>
    /// Name of the logical partition that hosts a systems with a mainframe operating system.
    /// </summary>
    public const string LparName = "mainframe.lpar.name";
}
