// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@e10a930844c6951757a43b849d364f7d056ac32b
// Schema: https://opentelemetry.io/schemas/1.44.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

#nullable enable

namespace Qyl.Telemetry.SemanticConventions.Attributes.Vcs;

/// <summary>Vcs Attributes.</summary>
public static class VcsAttributes
{
    /// <summary>
    /// Deprecated, use <c>vcs.change.id</c> instead.
    /// </summary>
    [global::System.Obsolete("Replaced by vcs.change.id.", false)]
    public const string RepositoryChangeId = "vcs.repository.change.id";

    /// <summary>
    /// Deprecated, use <c>vcs.change.title</c> instead.
    /// </summary>
    [global::System.Obsolete("Replaced by vcs.change.title.", false)]
    public const string RepositoryChangeTitle = "vcs.repository.change.title";

    /// <summary>
    /// Deprecated, use <c>vcs.ref.head.name</c> instead.
    /// </summary>
    [global::System.Obsolete("Replaced by vcs.ref.head.name.", false)]
    public const string RepositoryRefName = "vcs.repository.ref.name";

    /// <summary>
    /// Deprecated, use <c>vcs.ref.head.revision</c> instead.
    /// </summary>
    [global::System.Obsolete("Replaced by vcs.ref.head.revision.", false)]
    public const string RepositoryRefRevision = "vcs.repository.ref.revision";

    /// <summary>
    /// Deprecated, use <c>vcs.ref.head.type</c> instead.
    /// </summary>
    [global::System.Obsolete("Replaced by vcs.ref.head.type.", false)]
    public const string RepositoryRefType = "vcs.repository.ref.type";
}
