// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@e10a930844c6951757a43b849d364f7d056ac32b
// Schema: https://opentelemetry.io/schemas/1.44.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

#nullable enable

namespace Qyl.Telemetry.SemanticConventions.Attributes.Enduser;

/// <summary>Enduser Attributes.</summary>
public static class EnduserAttributes
{
    /// <summary>
    /// Deprecated, use <c>user.roles</c> instead.
    /// </summary>
    [global::System.Obsolete("Use `user.roles` instead.", false)]
    public const string Role = "enduser.role";

    /// <summary>
    /// Deprecated, no replacement at this time.
    /// </summary>
    [global::System.Obsolete("Removed, no replacement.", false)]
    public const string Scope = "enduser.scope";
}
