// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@89aae438b3b3b0a8dd33003c9d70592baf7dbd0d
// Schema: https://opentelemetry.io/schemas/1.43.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

#nullable enable

namespace Qyl.Telemetry.SemanticConventions.Incubating.Attributes.Browser;

/// <summary>Browser Attributes (incubating).</summary>
public static class BrowserAttributes
{
    /// <summary>
    /// Array of brand name and version separated by a space
    /// </summary>
    /// <remarks>
    /// This value is intended to be taken from the <a href="https://wicg.github.io/ua-client-hints/#interface">UA client hints API</a> (<c>navigator.userAgentData.brands</c>).
    /// </remarks>
    public const string Brands = "browser.brands";

    /// <summary>
    /// Absolute URL of the current browser document according to <a href="https://www.rfc-editor.org/rfc/rfc3986">RFC3986</a>.
    /// </summary>
    public const string DocumentUrlFull = "browser.document.url.full";

    /// <summary>
    /// Preferred language of the user using the browser
    /// </summary>
    /// <remarks>
    /// This value is intended to be taken from the Navigator API <c>navigator.language</c>.
    /// </remarks>
    public const string Language = "browser.language";

    /// <summary>
    /// A boolean that is true if the browser is running on a mobile device
    /// </summary>
    /// <remarks>
    /// This value is intended to be taken from the <a href="https://wicg.github.io/ua-client-hints/#interface">UA client hints API</a> (<c>navigator.userAgentData.mobile</c>). If unavailable, this attribute SHOULD be left unset.
    /// </remarks>
    public const string Mobile = "browser.mobile";

    /// <summary>
    /// The platform on which the browser is running
    /// </summary>
    /// <remarks>
    /// This value is intended to be taken from the <a href="https://wicg.github.io/ua-client-hints/#interface">UA client hints API</a> (<c>navigator.userAgentData.platform</c>). If unavailable, the legacy <c>navigator.platform</c> API SHOULD NOT be used instead and this attribute SHOULD be left unset in order for the values to be consistent.
    /// The list of possible values is defined in the <a href="https://wicg.github.io/ua-client-hints/#sec-ch-ua-platform">W3C User-Agent Client Hints specification</a>. Note that some (but not all) of these values can overlap with values in the <a href="./os.md">`os.type` and `os.name` attributes</a>. However, for consistency, the values in the <c>browser.platform</c> attribute should capture the exact value that the user agent provides.
    /// </remarks>
    public const string Platform = "browser.platform";
}
