// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@e10a930844c6951757a43b849d364f7d056ac32b
// Schema: https://opentelemetry.io/schemas/1.44.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

#nullable enable

namespace Qyl.Telemetry.SemanticConventions.Incubating.Attributes.Opentracing;

/// <summary>Opentracing Attributes (incubating).</summary>
public static class OpentracingAttributes
{
    /// <summary>
    /// Parent-child Reference type
    /// </summary>
    /// <remarks>
    /// The causal relationship between a child Span and a parent Span.
    /// </remarks>
    public const string RefType = "opentracing.ref_type";

    /// <summary>
    /// Values for the <c>RefType</c> attribute.
    /// </summary>
    public static class RefTypeValues
    {
        /// <summary>
        /// The parent Span depends on the child Span in some capacity.
        /// </summary>
        public const string ChildOf = "child_of";

        /// <summary>
        /// The parent Span doesn't depend in any way on the result of the child Span.
        /// </summary>
        public const string FollowsFrom = "follows_from";
    }
}
