// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@e10a930844c6951757a43b849d364f7d056ac32b
// Schema: https://opentelemetry.io/schemas/1.44.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

#nullable enable

namespace Qyl.Telemetry.SemanticConventions.Incubating.Attributes.User;

/// <summary>User Attributes (incubating).</summary>
public static class UserAttributes
{
    /// <summary>
    /// User email address.
    /// </summary>
    public const string Email = "user.email";

    /// <summary>
    /// User's full name
    /// </summary>
    public const string FullName = "user.full_name";

    /// <summary>
    /// Unique user hash to correlate information for a user in anonymized form.
    /// </summary>
    /// <remarks>
    /// Useful if <c>user.id</c> or <c>user.name</c> contain confidential information and cannot be used.
    /// </remarks>
    public const string Hash = "user.hash";

    /// <summary>
    /// Unique identifier of the user.
    /// </summary>
    public const string Id = "user.id";

    /// <summary>
    /// Short name or login/username of the user.
    /// </summary>
    public const string Name = "user.name";

    /// <summary>
    /// Array of user roles at the time of the event.
    /// </summary>
    public const string Roles = "user.roles";
}
