// <auto-generated/>
#nullable enable
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// <auto-generated />

#nullable enable

#if !NET5_0_OR_GREATER

using System.Diagnostics.CodeAnalysis;

namespace System.Diagnostics.CodeAnalysis;

/// <summary>
///     Indicates that the specified method requires dynamic access to code that is not referenced
///     statically, for example through <see cref="System.Reflection" />.
/// </summary>
[AttributeUsage(AttributeTargets.Method | AttributeTargets.Constructor | AttributeTargets.Class, Inherited = false)]
[ExcludeFromCodeCoverage]
internal sealed class RequiresUnreferencedCodeAttribute : Attribute
{
    /// <summary>
    ///     Initializes a new instance of the <see cref="RequiresUnreferencedCodeAttribute" /> class.
    /// </summary>
    /// <param name="message">A message that contains information about the usage of unreferenced code.</param>
    public RequiresUnreferencedCodeAttribute(string message)
    {
        Message = message;
    }

    /// <summary>Gets a message that contains information about the usage of unreferenced code.</summary>
    public string Message { get; }

    /// <summary>Gets or sets an optional URL that contains more information about the method.</summary>
    public string? Url { get; set; }
}

#endif