// <auto-generated/>
// Generated from open-telemetry/semantic-conventions-genai@eaefa142a94cefe5d199d47e4a73727dfbd825df.
// Regenerate with scripts/emit_registry_resources.py; do not edit by hand.
// </auto-generated>

#nullable enable

using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.IO;

namespace Qyl.Telemetry.SemanticConventions.Incubating.Registry;

/// <summary>
/// Opens the complete pinned semantic-convention registry and the authoritative JSON Schemas
/// referenced by structured GenAI attributes.
/// </summary>
public static class SemanticConventionRegistry
{
    private const string ResolvedRegistryResourceName =
        "Qyl.Telemetry.SemanticConventions.Incubating.registry.resolved-registry.json";

    private static readonly IReadOnlyDictionary<string, string> PayloadSchemaResources =
        new ReadOnlyDictionary<string, string>(new Dictionary<string, string>(System.StringComparer.Ordinal)
        {
            ["gen_ai.input.messages"] = "Qyl.Telemetry.SemanticConventions.Incubating.schemas.gen-ai.gen-ai-input-messages.json",
            ["gen_ai.memory.records"] = "Qyl.Telemetry.SemanticConventions.Incubating.schemas.gen-ai.gen-ai-memory-records.json",
            ["gen_ai.output.messages"] = "Qyl.Telemetry.SemanticConventions.Incubating.schemas.gen-ai.gen-ai-output-messages.json",
            ["gen_ai.retrieval.documents"] = "Qyl.Telemetry.SemanticConventions.Incubating.schemas.gen-ai.gen-ai-retrieval-documents.json",
            ["gen_ai.system_instructions"] = "Qyl.Telemetry.SemanticConventions.Incubating.schemas.gen-ai.gen-ai-system-instructions.json",
            ["gen_ai.tool.call.arguments"] = "Qyl.Telemetry.SemanticConventions.Incubating.schemas.gen-ai.gen-ai-tool-call-arguments.json",
            ["gen_ai.tool.call.result"] = "Qyl.Telemetry.SemanticConventions.Incubating.schemas.gen-ai.gen-ai-tool-call-result.json",
            ["gen_ai.tool.definitions"] = "Qyl.Telemetry.SemanticConventions.Incubating.schemas.gen-ai.gen-ai-tool-definitions.json",
        });

    /// <summary>The core OpenTelemetry schema URL represented by the registry.</summary>
    public const string CoreSchemaUrl = "https://opentelemetry.io/schemas/1.44.0";

    /// <summary>The development GenAI schema label declared by the pinned GenAI manifest.</summary>
    public const string GenAiSchemaUrl = "https://opentelemetry.io/schemas/gen-ai-dev/1.42.0-dev";

    /// <summary>Gets the structured GenAI attribute keys that have an upstream JSON Schema.</summary>
    public static IEnumerable<string> PayloadAttributeKeys => PayloadSchemaResources.Keys;

    /// <summary>Opens the complete merged, source-attributed registry projection.</summary>
    /// <returns>A new readable stream. The caller owns the stream.</returns>
    public static Stream OpenResolvedRegistry() => OpenRequiredResource(ResolvedRegistryResourceName);

    /// <summary>Opens the upstream JSON Schema associated with a structured GenAI attribute.</summary>
    /// <param name="attributeKey">The exact semantic-convention attribute key.</param>
    /// <param name="schema">A new readable stream when the key has a schema; otherwise <see langword="null"/>.</param>
    /// <returns><see langword="true"/> when the registry associates a schema with the key.</returns>
    public static bool TryOpenPayloadSchema(string attributeKey, out Stream? schema)
    {
        if (!PayloadSchemaResources.TryGetValue(attributeKey, out var resourceName))
        {
            schema = null;
            return false;
        }

        schema = OpenRequiredResource(resourceName);
        return true;
    }

    private static Stream OpenRequiredResource(string resourceName) =>
        typeof(SemanticConventionRegistry).Assembly.GetManifestResourceStream(resourceName)
        ?? throw new InvalidOperationException($"Embedded semantic-convention resource '{resourceName}' was not found.");
}
