// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions-genai@c321d7eb4443ae1d1d88c2e24eda849f62049008
// Schema: https://opentelemetry.io/schemas/gen-ai-dev/1.42.0-dev
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

#nullable enable

namespace Qyl.OpenTelemetry.SemanticConventions.Incubating.Attributes.GenAi;

/// <summary>GenAi Attributes (incubating).</summary>
public static class GenAiAttributes
{
    /// <summary>
    /// Free-form description of the GenAI agent provided by the application.
    /// </summary>
    public const string AgentDescription = "gen_ai.agent.description";

    /// <summary>
    /// The unique and stable identifier of the GenAI hosted agent resource.
    /// </summary>
    /// <remarks>
    /// For hosted agents, this SHOULD be the provider-assigned stable identifier of the agent resource such as <a href="https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent_Agent.html">AWS Bedrock agent ARN</a> or <a href="https://docs.cloud.google.com/agent-registry/concepts#agent-identifier">GCP Agent Registry identifier</a>.
    /// It's NOT RECOMMENDED to record in-memory agent instance ids on this attribute due to their transient nature.
    /// </remarks>
    public const string AgentId = "gen_ai.agent.id";

    /// <summary>
    /// Human-readable name of the GenAI agent provided by the application.
    /// </summary>
    public const string AgentName = "gen_ai.agent.name";

    /// <summary>
    /// The version of the GenAI agent.
    /// </summary>
    public const string AgentVersion = "gen_ai.agent.version";

    /// <summary>
    /// Indicates whether the effective conversation context used for this operation is a compacted view of a prior conversation.
    /// </summary>
    /// <remarks>
    /// This attribute is a positive indicator of context compaction. Instrumentations
    /// SHOULD set it to <c>true</c> only when they can reliably determine that context
    /// compaction was applied. Instrumentations SHOULD NOT set it to <c>false</c>; they
    /// SHOULD leave it unset otherwise.
    /// </remarks>
    public const string ConversationCompacted = "gen_ai.conversation.compacted";

    /// <summary>
    /// The unique identifier for a conversation (session, thread), used to store and correlate messages within this conversation.
    /// </summary>
    public const string ConversationId = "gen_ai.conversation.id";

    /// <summary>
    /// The data source identifier.
    /// </summary>
    /// <remarks>
    /// Data sources are used by AI agents and RAG applications to store grounding data. A data source may be an external database, object store, document collection, website, or any other storage system used by the GenAI agent or application. The <c>gen_ai.data_source.id</c> SHOULD match the identifier used by the GenAI system rather than a name specific to the external storage, such as a database or object store. Semantic conventions referencing <c>gen_ai.data_source.id</c> MAY also leverage additional attributes, such as <c>db.*</c>, to further identify and describe the data source.
    /// </remarks>
    public const string DataSourceId = "gen_ai.data_source.id";

    /// <summary>
    /// The number of dimensions the resulting output embeddings should have.
    /// </summary>
    public const string EmbeddingsDimensionCount = "gen_ai.embeddings.dimension.count";

    /// <summary>
    /// A free-form explanation for the assigned score provided by the evaluator.
    /// </summary>
    public const string EvaluationExplanation = "gen_ai.evaluation.explanation";

    /// <summary>
    /// The name of the evaluation metric used for the GenAI response.
    /// </summary>
    public const string EvaluationName = "gen_ai.evaluation.name";

    /// <summary>
    /// Human readable label for evaluation.
    /// </summary>
    /// <remarks>
    /// This attribute provides a human-readable interpretation of the evaluation score produced by an evaluator. For example, a score value of 1 could mean "relevant" in one evaluation system and "not relevant" in another, depending on the scoring range and evaluator. The label SHOULD have low cardinality. Possible values depend on the evaluation metric and evaluator used; implementations SHOULD document the possible values.
    /// </remarks>
    public const string EvaluationScoreLabel = "gen_ai.evaluation.score.label";

    /// <summary>
    /// The evaluation score returned by the evaluator.
    /// </summary>
    public const string EvaluationScoreValue = "gen_ai.evaluation.score.value";

    /// <summary>
    /// The chat history provided to the model as an input.
    /// </summary>
    /// <remarks>
    /// Messages MUST be provided in the order they were sent to the model.
    /// Instrumentations MAY provide a way for users to filter or truncate
    /// input messages.
    /// <para/>
    /// Warning:
    /// This attribute is likely to contain sensitive information including user/PII data.
    /// <para/>
    /// See <a href="/docs/gen-ai/gen-ai-spans.md#recording-content-on-attributes">Recording content on attributes</a>
    /// section for more details.
    /// </remarks>
    public const string InputMessages = "gen_ai.input.messages";

    /// <summary>
    /// The search query used to retrieve memories.
    /// </summary>
    /// <remarks>
    /// Instrumentations SHOULD NOT capture this attribute by default. Capture SHOULD be gated
    /// by an explicit user opt-in, for example <c>OTEL_INSTRUMENTATION_GENAI_CAPTURE_MESSAGE_CONTENT</c>.
    /// <para/>
    /// Warning:
    /// This attribute may contain sensitive information.
    /// </remarks>
    public const string MemoryQueryText = "gen_ai.memory.query.text";

    /// <summary>
    /// The number of memory records relevant to the operation.
    /// </summary>
    /// <remarks>
    /// For <c>search_memory</c> operations, this is the number of memory records returned by the operation. For <c>create_memory</c> operations, this is the number of memory records the operation attempted to create. For <c>update_memory</c> operations, this is the number of memory records the operation attempted to modify. For <c>upsert_memory</c> operations, this is the number of memory records the operation attempted to create or update. For <c>delete_memory</c> operations, this is the number of memory records the operation attempted to delete.
    /// </remarks>
    public const string MemoryRecordCount = "gen_ai.memory.record.count";

    /// <summary>
    /// The unique identifier of the memory record.
    /// </summary>
    public const string MemoryRecordId = "gen_ai.memory.record.id";

    /// <summary>
    /// The memory records stored or retrieved in a memory operation.
    /// </summary>
    /// <remarks>
    /// Instrumentations SHOULD NOT capture this attribute by default. Capture SHOULD be gated
    /// by an explicit user opt-in, for example <c>OTEL_INSTRUMENTATION_GENAI_CAPTURE_MESSAGE_CONTENT</c>.
    /// <para/>
    /// Warning:
    /// This attribute may contain sensitive information including user/PII data.
    /// </remarks>
    public const string MemoryRecords = "gen_ai.memory.records";

    /// <summary>
    /// The unique identifier of the memory store.
    /// </summary>
    /// <remarks>
    /// Semantic conventions for individual components SHOULD document what <c>gen_ai.memory.store.id</c> maps to within the implementation.
    /// </remarks>
    public const string MemoryStoreId = "gen_ai.memory.store.id";

    /// <summary>
    /// The name of the operation being performed.
    /// </summary>
    /// <remarks>
    /// If one of the predefined values applies, but specific system uses a different name it's RECOMMENDED to document it in the semantic conventions for specific GenAI system and use system-specific name in the instrumentation. If a different name is not documented, instrumentation libraries SHOULD use applicable predefined value.
    /// </remarks>
    public const string OperationName = "gen_ai.operation.name";

    /// <summary>
    /// Values for the <c>OperationName</c> attribute.
    /// </summary>
    public static class OperationNameValues
    {
        /// <summary>
        /// Chat completion operation such as <a href="https://platform.openai.com/docs/api-reference/chat">OpenAI Chat API</a>.
        /// </summary>
        public const string Chat = "chat";

        /// <summary>
        /// Create GenAI agent.
        /// </summary>
        public const string CreateAgent = "create_agent";

        /// <summary>
        /// Create new memory records.
        /// </summary>
        public const string CreateMemory = "create_memory";

        /// <summary>
        /// Create or initialize a memory store.
        /// </summary>
        public const string CreateMemoryStore = "create_memory_store";

        /// <summary>
        /// Delete memory records.
        /// </summary>
        public const string DeleteMemory = "delete_memory";

        /// <summary>
        /// Delete or deprovision a memory store.
        /// </summary>
        public const string DeleteMemoryStore = "delete_memory_store";

        /// <summary>
        /// Embeddings operation such as <a href="https://platform.openai.com/docs/api-reference/embeddings/create">OpenAI Create embeddings API</a>.
        /// </summary>
        public const string Embeddings = "embeddings";

        /// <summary>
        /// Execute a tool.
        /// </summary>
        public const string ExecuteTool = "execute_tool";

        /// <summary>
        /// Multimodal content generation operation such as <a href="https://ai.google.dev/api/generate-content">Gemini Generate Content</a>.
        /// </summary>
        public const string GenerateContent = "generate_content";

        /// <summary>
        /// Invoke GenAI agent.
        /// </summary>
        public const string InvokeAgent = "invoke_agent";

        /// <summary>
        /// Invoke GenAI workflow.
        /// </summary>
        public const string InvokeWorkflow = "invoke_workflow";

        /// <summary>
        /// Agent planning or task decomposition phase.
        /// </summary>
        public const string Plan = "plan";

        /// <summary>
        /// Retrieval operation such as <a href="https://platform.openai.com/docs/api-reference/vector-stores/search">OpenAI Search Vector Store API</a>.
        /// </summary>
        public const string Retrieval = "retrieval";

        /// <summary>
        /// Search/query memories from a memory store.
        /// </summary>
        public const string SearchMemory = "search_memory";

        /// <summary>
        /// Text completions operation such as <a href="https://platform.openai.com/docs/api-reference/completions">OpenAI Completions API (Legacy)</a>.
        /// </summary>
        public const string TextCompletion = "text_completion";

        /// <summary>
        /// Update existing memory records.
        /// </summary>
        public const string UpdateMemory = "update_memory";

        /// <summary>
        /// Create or update memory records without the caller choosing which.
        /// </summary>
        public const string UpsertMemory = "upsert_memory";
    }

    /// <summary>
    /// Messages returned by the model where each message represents a specific model response (choice, candidate).
    /// </summary>
    /// <remarks>
    /// Each message represents a single output choice/candidate generated by
    /// the model. Each message corresponds to exactly one generation
    /// (choice/candidate) and vice versa - one choice cannot be split across
    /// multiple messages or one message cannot contain parts from multiple choices.
    /// <para/>
    /// Instrumentations MAY provide a way for users to filter or truncate
    /// output messages.
    /// <para/>
    /// Warning:
    /// This attribute is likely to contain sensitive information including user/PII data.
    /// <para/>
    /// See <a href="/docs/gen-ai/gen-ai-spans.md#recording-content-on-attributes">Recording content on attributes</a>
    /// section for more details.
    /// </remarks>
    public const string OutputMessages = "gen_ai.output.messages";

    /// <summary>
    /// Represents the content type requested by the client.
    /// </summary>
    /// <remarks>
    /// This attribute SHOULD be used when the client requests output of a specific type. The model may return zero or more outputs of this type.
    /// This attribute specifies the output modality and not the actual output format. For example, if an image is requested, the actual output could be a URL pointing to an image file.
    /// Additional output format details may be recorded in the future in the <c>gen_ai.output.{type}.*</c> attributes.
    /// </remarks>
    public const string OutputType = "gen_ai.output.type";

    /// <summary>
    /// Values for the <c>OutputType</c> attribute.
    /// </summary>
    public static class OutputTypeValues
    {
        /// <summary>
        /// Image.
        /// </summary>
        public const string Image = "image";

        /// <summary>
        /// JSON object with known or unknown schema.
        /// </summary>
        public const string Json = "json";

        /// <summary>
        /// Speech.
        /// </summary>
        public const string Speech = "speech";

        /// <summary>
        /// Plain text.
        /// </summary>
        public const string Text = "text";
    }

    /// <summary>
    /// The name of the prompt that uniquely identifies it.
    /// </summary>
    public const string PromptName = "gen_ai.prompt.name";

    /// <summary>
    /// The variables supplied to the prompt template, the <c>&lt;key&gt;</c> being the variable name, the value being the variable value.
    /// </summary>
    /// <remarks>
    /// Prompt templates are parameterized with variables that are filled in
    /// at runtime. This attribute records the variable values passed to the
    /// template. The attribute name defines the variable name, and the
    /// attribute value is the variable value serialized as a string.
    /// <para/>
    /// Examples:
    /// <para/>
    /// - A variable <c>user_name</c> with value <c>Alice</c> SHOULD be recorded as
    ///   the <c>gen_ai.prompt.variable.user_name</c> attribute with value <c>"Alice"</c>.
    /// - A variable <c>language</c> with value <c>French</c> SHOULD be recorded as
    ///   the <c>gen_ai.prompt.variable.language</c> attribute with value <c>"French"</c>.
    /// <para/>
    /// Warning:
    /// This attribute may contain sensitive information.
    /// </remarks>
    public const string PromptVariable = "gen_ai.prompt.variable";

    /// <summary>
    /// The version of the prompt template used.
    /// </summary>
    /// <remarks>
    /// The version string can follow any versioning scheme chosen by the
    /// application (e.g., SemVer, date-based, or platform-specific tags).
    /// When a prompt management system is in use, this SHOULD match the
    /// version identifier used by that system.
    /// </remarks>
    public const string PromptVersion = "gen_ai.prompt.version";

    /// <summary>
    /// The Generative AI provider as identified by the client or server instrumentation.
    /// </summary>
    /// <remarks>
    /// Semantic conventions for individual GenAI operations SHOULD clarify which
    /// kinds of providers (e.g. inference, embeddings, retrieval, memory, hosted
    /// agent providers) apply when it is not clear from context.
    /// <para/>
    /// The attribute SHOULD be set based on the instrumentation's best knowledge
    /// and may differ from the actual upstream provider. For example, a client SDK
    /// may be configured against a proxy or hosting platform that transparently
    /// relays requests to a different provider.
    /// <para/>
    /// The <c>gen_ai.provider.name</c> attribute acts as a discriminator that
    /// identifies the GenAI telemetry format flavor specific to that provider
    /// within GenAI semantic conventions.
    /// It SHOULD be set consistently with provider-specific attributes and signals.
    /// For example, GenAI spans, metrics, and events related to AWS Bedrock
    /// should have the <c>gen_ai.provider.name</c> set to <c>aws.bedrock</c> and include
    /// applicable <c>aws.bedrock.*</c> attributes and are not expected to include
    /// <c>openai.*</c> attributes.
    /// </remarks>
    public const string ProviderName = "gen_ai.provider.name";

    /// <summary>
    /// Values for the <c>ProviderName</c> attribute.
    /// </summary>
    public static class ProviderNameValues
    {
        /// <summary>
        /// <a href="https://www.anthropic.com/">Anthropic</a>.
        /// </summary>
        public const string Anthropic = "anthropic";

        /// <summary>
        /// <a href="https://aws.amazon.com/bedrock">AWS Bedrock</a>.
        /// </summary>
        public const string AwsBedrock = "aws.bedrock";

        /// <summary>
        /// Azure AI Inference.
        /// </summary>
        public const string AzureAiInference = "azure.ai.inference";

        /// <summary>
        /// <a href="https://learn.microsoft.com/en-us/azure/ai-services/openai/overview">Azure OpenAI</a>.
        /// </summary>
        public const string AzureAiOpenai = "azure.ai.openai";

        /// <summary>
        /// <a href="https://cohere.com/">Cohere</a>.
        /// </summary>
        public const string Cohere = "cohere";

        /// <summary>
        /// <a href="https://www.deepseek.com/">DeepSeek</a>.
        /// </summary>
        public const string Deepseek = "deepseek";

        /// <summary>
        /// <a href="https://cloud.google.com/products/gemini">Gemini</a>.
        /// </summary>
        public const string GcpGemini = "gcp.gemini";

        /// <summary>
        /// Any Google generative AI endpoint.
        /// </summary>
        public const string GcpGenAi = "gcp.gen_ai";

        /// <summary>
        /// <a href="https://cloud.google.com/vertex-ai">Vertex AI</a>.
        /// </summary>
        public const string GcpVertexAi = "gcp.vertex_ai";

        /// <summary>
        /// <a href="https://groq.com/">Groq</a>.
        /// </summary>
        public const string Groq = "groq";

        /// <summary>
        /// <a href="https://www.ibm.com/products/watsonx-ai">IBM Watsonx AI</a>.
        /// </summary>
        public const string IbmWatsonxAi = "ibm.watsonx.ai";

        /// <summary>
        /// <a href="https://mistral.ai/">Mistral AI</a>.
        /// </summary>
        public const string MistralAi = "mistral_ai";

        /// <summary>
        /// <a href="https://www.moonshot.ai/">Moonshot AI</a>.
        /// </summary>
        public const string MoonshotAi = "moonshot_ai";

        /// <summary>
        /// <a href="https://openai.com/">OpenAI</a>.
        /// </summary>
        public const string Openai = "openai";

        /// <summary>
        /// <a href="https://www.perplexity.ai/">Perplexity</a>.
        /// </summary>
        public const string Perplexity = "perplexity";

        /// <summary>
        /// <a href="https://x.ai/">xAI</a>.
        /// </summary>
        public const string XAi = "x_ai";
    }

    /// <summary>
    /// The target number of candidate completions to return.
    /// </summary>
    public const string RequestChoiceCount = "gen_ai.request.choice.count";

    /// <summary>
    /// The encoding formats requested in an embeddings operation, if specified.
    /// </summary>
    /// <remarks>
    /// In some GenAI systems the encoding formats are called embedding types. Also, some GenAI systems only accept a single format per request.
    /// </remarks>
    public const string RequestEncodingFormats = "gen_ai.request.encoding_formats";

    /// <summary>
    /// The frequency penalty setting for the GenAI request.
    /// </summary>
    public const string RequestFrequencyPenalty = "gen_ai.request.frequency_penalty";

    /// <summary>
    /// The maximum number of tokens the model generates for a request.
    /// </summary>
    public const string RequestMaxTokens = "gen_ai.request.max_tokens";

    /// <summary>
    /// The name of the GenAI model a request is being made to.
    /// </summary>
    public const string RequestModel = "gen_ai.request.model";

    /// <summary>
    /// The presence penalty setting for the GenAI request.
    /// </summary>
    public const string RequestPresencePenalty = "gen_ai.request.presence_penalty";

    /// <summary>
    /// The reasoning or thinking effort level requested for a GenAI model.
    /// </summary>
    /// <remarks>
    /// The value SHOULD be the exact string value sent to the provider.
    /// Semantic conventions for individual providers SHOULD document which input parameter maps to this attribute.
    /// </remarks>
    public const string RequestReasoningLevel = "gen_ai.request.reasoning.level";

    /// <summary>
    /// Requests with same seed value more likely to return same result.
    /// </summary>
    public const string RequestSeed = "gen_ai.request.seed";

    /// <summary>
    /// List of sequences that the model will use to stop generating further tokens.
    /// </summary>
    public const string RequestStopSequences = "gen_ai.request.stop_sequences";

    /// <summary>
    /// Indicates whether the GenAI request was made in streaming mode.
    /// </summary>
    public const string RequestStream = "gen_ai.request.stream";

    /// <summary>
    /// The temperature setting for the GenAI request.
    /// </summary>
    public const string RequestTemperature = "gen_ai.request.temperature";

    /// <summary>
    /// The top-K sampling setting for the GenAI request: restricts token generation at each step to the K most likely next tokens.
    /// </summary>
    /// <remarks>
    /// This is a decoding/sampling parameter (e.g., Anthropic <c>top_k</c>, Cohere <c>k</c>, Google <c>topK</c>), not an output-shaping parameter. In particular, OpenAI's <c>top_logprobs</c> controls how many per-token log-probabilities are returned in the response and does not change generation; it MUST NOT be reported as <c>gen_ai.request.top_k</c>.
    /// </remarks>
    public const string RequestTopK = "gen_ai.request.top_k";

    /// <summary>
    /// The top_p sampling setting for the GenAI request.
    /// </summary>
    public const string RequestTopP = "gen_ai.request.top_p";

    /// <summary>
    /// Array of reasons the model stopped generating tokens, corresponding to each generation received.
    /// </summary>
    public const string ResponseFinishReasons = "gen_ai.response.finish_reasons";

    /// <summary>
    /// The unique identifier for the completion.
    /// </summary>
    public const string ResponseId = "gen_ai.response.id";

    /// <summary>
    /// The name of the model that generated the response.
    /// </summary>
    public const string ResponseModel = "gen_ai.response.model";

    /// <summary>
    /// Time to first chunk in a streaming response, measured from request issuance, in seconds. The value is measured from when the client issues the generation request to when the first chunk is received in the response stream.
    /// </summary>
    public const string ResponseTimeToFirstChunk = "gen_ai.response.time_to_first_chunk";

    /// <summary>
    /// The documents retrieved.
    /// </summary>
    /// <remarks>
    /// Each document object SHOULD contain at least the following properties:
    /// <c>id</c> (string): A unique identifier for the document, <c>score</c> (double): The relevance score of the document
    /// </remarks>
    public const string RetrievalDocuments = "gen_ai.retrieval.documents";

    /// <summary>
    /// The query text used for retrieval.
    /// </summary>
    /// <remarks>
    /// <blockquote>
    /// Warning:
    /// This attribute may contain sensitive information.</blockquote>
    /// </remarks>
    public const string RetrievalQueryText = "gen_ai.retrieval.query.text";

    /// <summary>
    /// The maximum number of documents the retriever was asked to return for the query (also known as <c>k</c>, <c>limit</c>, or <c>max_num_results</c>).
    /// </summary>
    public const string RetrievalTopK = "gen_ai.retrieval.top_k";

    /// <summary>
    /// The system message or instructions provided to the GenAI model separately from the chat history.
    /// </summary>
    /// <remarks>
    /// This attribute SHOULD be used when the corresponding provider or API
    /// allows to provide system instructions or messages separately from the
    /// chat history.
    /// <para/>
    /// Instructions that are part of the chat history SHOULD be recorded in
    /// <c>gen_ai.input.messages</c> attribute instead.
    /// <para/>
    /// Instrumentations MAY provide a way for users to filter or truncate
    /// system instructions.
    /// <para/>
    /// Warning:
    /// This attribute may contain sensitive information.
    /// <para/>
    /// See <a href="/docs/gen-ai/gen-ai-spans.md#recording-content-on-attributes">Recording content on attributes</a>
    /// section for more details.
    /// </remarks>
    public const string SystemInstructions = "gen_ai.system_instructions";

    /// <summary>
    /// The type of token being counted.
    /// </summary>
    public const string TokenType = "gen_ai.token.type";

    /// <summary>
    /// Values for the <c>TokenType</c> attribute.
    /// </summary>
    public static class TokenTypeValues
    {
        /// <summary>
        /// Input tokens (prompt, input, etc.).
        /// </summary>
        public const string Input = "input";

        /// <summary>
        /// Output tokens (completion, response, etc.).
        /// </summary>
        public const string Output = "output";
    }

    /// <summary>
    /// Parameters passed to the tool call.
    /// </summary>
    /// <remarks>
    /// <blockquote>
    /// Warning:
    /// This attribute may contain sensitive information.</blockquote>
    /// <para/>
    /// It's expected to be an object - in case a serialized string is available
    /// to the instrumentation, the instrumentation SHOULD do the best effort to
    /// deserialize it to an object.
    /// </remarks>
    public const string ToolCallArguments = "gen_ai.tool.call.arguments";

    /// <summary>
    /// The tool call identifier.
    /// </summary>
    public const string ToolCallId = "gen_ai.tool.call.id";

    /// <summary>
    /// The result returned by the tool call (if any and if execution was successful).
    /// </summary>
    /// <remarks>
    /// <blockquote>
    /// Warning:
    /// This attribute may contain sensitive information.</blockquote>
    /// <para/>
    /// It's expected to be an object - in case a serialized string is available
    /// to the instrumentation, the instrumentation SHOULD do the best effort to
    /// deserialize it to an object.
    /// </remarks>
    public const string ToolCallResult = "gen_ai.tool.call.result";

    /// <summary>
    /// The list of tool definitions available to the GenAI agent or model.
    /// </summary>
    /// <remarks>
    /// Since this attribute could be large, it's NOT RECOMMENDED to populate
    /// non-required properties by default. Instrumentations MAY provide a way
    /// to enable populating optional properties.
    /// </remarks>
    public const string ToolDefinitions = "gen_ai.tool.definitions";

    /// <summary>
    /// The tool description.
    /// </summary>
    public const string ToolDescription = "gen_ai.tool.description";

    /// <summary>
    /// Name of the tool utilized by the agent.
    /// </summary>
    public const string ToolName = "gen_ai.tool.name";

    /// <summary>
    /// Type of the tool utilized by the agent
    /// </summary>
    /// <remarks>
    /// Extension: A tool executed on the agent-side to directly call external APIs, bridging the gap between the agent and real-world systems.
    ///   Agent-side operations involve actions that are performed by the agent on the server or within the agent's controlled environment.
    /// Function: A tool executed on the client-side, where the agent generates parameters for a predefined function, and the client executes the logic.
    ///   Client-side operations are actions taken on the user's end or within the client application.
    /// Datastore: A tool used by the agent to access and query structured or unstructured external data for retrieval-augmented tasks or knowledge updates.
    /// </remarks>
    public const string ToolType = "gen_ai.tool.type";

    /// <summary>
    /// The number of input tokens written to a provider-managed cache.
    /// </summary>
    /// <remarks>
    /// The value SHOULD be included in <c>gen_ai.usage.input_tokens</c>.
    /// </remarks>
    public const string UsageCacheCreationInputTokens = "gen_ai.usage.cache_creation.input_tokens";

    /// <summary>
    /// The number of input tokens served from a provider-managed cache.
    /// </summary>
    /// <remarks>
    /// The value SHOULD be included in <c>gen_ai.usage.input_tokens</c>.
    /// </remarks>
    public const string UsageCacheReadInputTokens = "gen_ai.usage.cache_read.input_tokens";

    /// <summary>
    /// The number of tokens used in the GenAI input (prompt).
    /// </summary>
    /// <remarks>
    /// This value SHOULD include all types of input tokens, including cached tokens.
    /// Instrumentations SHOULD make a best effort to populate this value, using a total
    /// provided by the provider when available or, depending on the provider API,
    /// by summing different token types parsed from the provider output.
    /// <para/>
    /// When the provider reports both billed token counts and model-consumed
    /// token counts (for example, Cohere exposes both <c>usage.billed_units</c> and
    /// <c>usage.tokens</c>), instrumentations SHOULD report the billed count so the
    /// value matches the units the customer is charged for.
    /// </remarks>
    public const string UsageInputTokens = "gen_ai.usage.input_tokens";

    /// <summary>
    /// The number of tokens used in the GenAI response (completion).
    /// </summary>
    /// <remarks>
    /// When the provider reports both billed token counts and model-consumed
    /// token counts (for example, Cohere exposes both <c>usage.billed_units</c> and
    /// <c>usage.tokens</c>), instrumentations SHOULD report the billed count so the
    /// value matches the units the customer is charged for.
    /// </remarks>
    public const string UsageOutputTokens = "gen_ai.usage.output_tokens";

    /// <summary>
    /// The number of output tokens used for reasoning (e.g. chain-of-thought, extended thinking).
    /// </summary>
    /// <remarks>
    /// The value SHOULD be included in <c>gen_ai.usage.output_tokens</c>.
    /// </remarks>
    public const string UsageReasoningOutputTokens = "gen_ai.usage.reasoning.output_tokens";

    /// <summary>
    /// Human-readable name of the GenAI workflow provided by the application.
    /// </summary>
    /// <remarks>
    /// This attribute can be populated in different frameworks; for example, as the name of the first chain in LangChain or the name of the crew in CrewAI.
    /// The workflow name is usually provided by the application in a way that is specific to the generative AI framework or library that orchestrates the workflow.
    /// It is usually a static name that is expected to be unique within an application.
    /// <para/>
    /// <c>gen_ai.workflow.name</c> MUST have low cardinality.
    /// Semantic conventions for individual Generative AI frameworks SHOULD document what <c>gen_ai.workflow.name</c> means in the context of that framework.
    /// If there is no low-cardinality workflow name available for a given framework, this attribute MUST NOT be captured by default.
    /// </remarks>
    public const string WorkflowName = "gen_ai.workflow.name";
}
