// <auto-generated/>
#nullable enable
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// <auto-generated />

#nullable enable

#if !NET5_0_OR_GREATER

using System.Diagnostics.CodeAnalysis;

namespace System.Runtime.CompilerServices;

/// <summary>
///     Backport of <see cref="IsExternalInit" /> for .NET Standard 2.0/2.1 and .NET Framework.
/// </summary>
[ExcludeFromCodeCoverage]
internal static class IsExternalInit
{
}

#endif