// <auto-generated/>
#nullable enable
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// <auto-generated />

#nullable enable

#if !NET9_0_OR_GREATER

using System.Diagnostics.CodeAnalysis;

namespace System.Runtime.CompilerServices;

/// <summary>
///     Backport of <see cref="ParamCollectionAttribute" /> for .NET 8 and earlier.
/// </summary>
[AttributeUsage(AttributeTargets.Parameter)]
[ExcludeFromCodeCoverage]
internal sealed class ParamCollectionAttribute : Attribute
{
    /// <summary>
    ///     Initializes a new instance of the <see cref="ParamCollectionAttribute" /> class.
    /// </summary>
    public ParamCollectionAttribute()
    {
    }
}

#endif