// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@e10a930844c6951757a43b849d364f7d056ac32b
// Schema: https://opentelemetry.io/schemas/1.44.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

#nullable enable

namespace Qyl.Telemetry.SemanticConventions.Incubating.Attributes.Graphql;

/// <summary>Graphql Attributes (incubating).</summary>
public static class GraphqlAttributes
{
    /// <summary>
    /// The GraphQL document being executed.
    /// </summary>
    /// <remarks>
    /// If instrumentation can reliably identify and redact sensitive information it SHOULD do it.
    /// </remarks>
    public const string Document = "graphql.document";

    /// <summary>
    /// The name of the operation being executed.
    /// </summary>
    public const string OperationName = "graphql.operation.name";

    /// <summary>
    /// The type of the operation being executed.
    /// </summary>
    public const string OperationType = "graphql.operation.type";

    /// <summary>
    /// Values for the <c>OperationType</c> attribute.
    /// </summary>
    public static class OperationTypeValues
    {
        /// <summary>
        /// GraphQL mutation.
        /// </summary>
        public const string Mutation = "mutation";

        /// <summary>
        /// GraphQL query.
        /// </summary>
        public const string Query = "query";

        /// <summary>
        /// GraphQL subscription.
        /// </summary>
        public const string Subscription = "subscription";
    }
}
