using System.Text.RegularExpressions;
using AwesomeAssertions;
using Qyl.Telemetry.SemanticConventions.Analyzers;
using Xunit;

namespace Qyl.Telemetry.SemanticConventions.Pipeline.Tests;

/// <summary>
/// Cross-verifies <c>OpenTelemetryDeprecatedSemconvCatalog.cs</c> against the registry's own
/// deprecations (<c>SemconvDeprecations.g.cs</c>, generated by Weaver).
/// </summary>
/// <remarks>
/// The catalog is deliberately hand-curated — it carries since-versions, guidance prose, and
/// mappings for keys upstream deleted outright, none of which the registry contains — so it
/// cannot be generated. What can rot silently is the part the registry does know:
/// <list type="number">
///   <item>every attribute the registry renames must appear in the catalog with exactly the
///   registry's replacement;</item>
///   <item>every attribute the registry deprecates without a rename must appear somewhere in
///   the catalog (exact table, context-sensitive table, or prefix rule);</item>
///   <item>every deprecated enum member must appear in the catalog's attribute-value table
///   under the same attribute.</item>
/// </list>
/// Catalog-only entries are fine: the registry cannot vouch either way. This replaces
/// scripts/verify_deprecated_catalog.py.
/// </remarks>
public sealed class DeprecatedSemconvCatalogTests
{
    private static readonly Catalog Parsed = Catalog.Load();

    [Fact]
    public void Every_Registry_Rename_Is_In_The_Catalog_With_The_Registry_Replacement()
    {
        var problems = new List<string>();
        foreach (var (key, renamedTo) in SemconvDeprecations.Renamed)
        {
            if (!Parsed.TryGetReplacement(key, out var known, out var replacement))
            {
                problems.Add($"MISSING rename: registry deprecates '{key}' -> '{renamedTo}', catalog has no entry");
                continue;
            }

            if (known && replacement is not null && !string.Equals(replacement, renamedTo, StringComparison.Ordinal))
                problems.Add($"MISMATCH: catalog maps '{key}' -> '{replacement}' but registry says '{renamedTo}'");
        }

        problems.Should().BeEmpty("the analyzer catalog must agree with the registry on every rename:\n{0}",
            string.Join("\n", problems.Order(StringComparer.Ordinal)));
    }

    [Fact]
    public void Every_Registry_Deprecation_Without_A_Replacement_Is_In_The_Catalog()
    {
        var problems = SemconvDeprecations.DeprecatedWithoutReplacement
            .Where(key => !Parsed.TryGetReplacement(key, out _, out _))
            .Select(key => $"MISSING deprecation: registry deprecates '{key}', catalog has no entry")
            .Order(StringComparer.Ordinal)
            .ToList();

        problems.Should().BeEmpty("the analyzer catalog must know every attribute the registry deprecates:\n{0}",
            string.Join("\n", problems));
    }

    [Fact]
    public void Every_Registry_Enum_Member_Deprecation_Is_In_The_Catalog_Value_Table()
    {
        // The catalog files enum-value deprecations under the current attribute name; if the
        // attribute itself was renamed, the entry may live under either name.
        var renames = SemconvDeprecations.Renamed.ToDictionary(
            static entry => entry.Key, static entry => entry.RenamedTo, StringComparer.Ordinal);

        var problems = SemconvDeprecations.DeprecatedValues
            .Where(entry => !Parsed.Values.Contains((entry.Key, entry.Value))
                            && !(renames.TryGetValue(entry.Key, out var renamed)
                                 && Parsed.Values.Contains((renamed, entry.Value))))
            .Select(entry =>
                $"MISSING enum-value deprecation: '{entry.Key}' member '{entry.Value}' is deprecated in the registry, catalog value-table has no entry")
            .Order(StringComparer.Ordinal)
            .ToList();

        problems.Should().BeEmpty("the analyzer catalog must know every deprecated enum member:\n{0}",
            string.Join("\n", problems));
    }

    /// <summary>The five data tables of the catalog, read out of the C# source by their literal shapes.</summary>
    private sealed class Catalog
    {
        private static readonly Regex PairEntry = new(@"\[""([^""]+)""\] = \(""([^""]*)"", ""[^""]*""\)", RegexOptions.Compiled);
        private static readonly Regex StringEntry = new(@"\[""([^""]+)""\] = ""((?:[^""\\]|\\.)+)""", RegexOptions.Compiled);
        private static readonly Regex ValueTable = new(@"\[""([^""]+)""\] = new\(StringComparer\.OrdinalIgnoreCase\) \{([^}]*)\}", RegexOptions.Compiled | RegexOptions.Singleline);

        private Catalog(
            Dictionary<string, string> exact,
            Dictionary<string, string> prefixes,
            Dictionary<string, string> genAi,
            HashSet<string> context,
            HashSet<(string, string)> values)
        {
            Exact = exact;
            Prefixes = prefixes;
            GenAi = genAi;
            Context = context;
            Values = values;
        }

        private Dictionary<string, string> Exact { get; }
        private Dictionary<string, string> Prefixes { get; }
        private Dictionary<string, string> GenAi { get; }
        private HashSet<string> Context { get; }
        internal HashSet<(string Key, string Value)> Values { get; }

        internal static Catalog Load()
        {
            var text = File.ReadAllText(RepoPath(
                "src", "Qyl.Telemetry.SemanticConventions.Analyzers", "OpenTelemetryDeprecatedSemconvCatalog.cs"));

            var values = new HashSet<(string, string)>();
            foreach (Match table in ValueTable.Matches(Section(text, "s_deprecatedAttributeValues")))
            foreach (Match entry in StringEntry.Matches(table.Groups[2].Value))
                values.Add((table.Groups[1].Value, entry.Groups[1].Value));

            return new Catalog(
                Pairs(Section(text, "s_deprecatedAttributes")),
                Pairs(Section(text, "s_deprecatedAttributePrefixes")),
                Pairs(Section(text, "s_deprecatedGenAiAttributes")),
                StringEntry.Matches(Section(text, "s_contextSensitiveDeprecatedNames"))
                    .Select(static m => m.Groups[1].Value)
                    .ToHashSet(StringComparer.Ordinal),
                values);
        }

        private static Dictionary<string, string> Pairs(string section) =>
            PairEntry.Matches(section).ToDictionary(
                static m => m.Groups[1].Value, static m => m.Groups[2].Value, StringComparer.Ordinal);

        private static string Section(string text, string name)
        {
            var start = text.IndexOf(name, StringComparison.Ordinal);
            start.Should().BeGreaterThan(0, $"the catalog must declare {name}");
            var end = text.IndexOf("};", start, StringComparison.Ordinal);
            return text.Substring(start, end - start);
        }

        /// <summary>Whether the catalog knows the old name, and the replacement it claims.</summary>
        internal bool TryGetReplacement(string old, out bool known, out string? replacement)
        {
            known = true;
            if (Exact.TryGetValue(old, out var exact))
            {
                replacement = exact.Length == 0 ? null : exact;
                return true;
            }

            if (GenAi.TryGetValue(old, out var genAi))
            {
                replacement = genAi;
                return true;
            }

            if (Context.Contains(old))
            {
                // Guidance only: the catalog claims no machine replacement.
                replacement = null;
                return true;
            }

            foreach (var (prefix, replacementPrefix) in Prefixes)
            {
                if (old.StartsWith(prefix, StringComparison.Ordinal))
                {
                    replacement = string.Concat(replacementPrefix, old.AsSpan(prefix.Length));
                    return true;
                }
            }

            known = false;
            replacement = null;
            return false;
        }
    }

    internal static string RepoPath(params string[] parts)
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);
        while (directory is not null && !File.Exists(Path.Combine(directory.FullName, "Qyl.Telemetry.SemanticConventions.slnx")))
            directory = directory.Parent;

        directory.Should().NotBeNull("the test must run inside the repository");
        return Path.Combine(new[] { directory!.FullName }.Concat(parts).ToArray());
    }
}
