// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@89aae438b3b3b0a8dd33003c9d70592baf7dbd0d
// Schema: https://opentelemetry.io/schemas/1.43.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

#nullable enable

namespace Qyl.Telemetry.SemanticConventions.Incubating.Attributes.Log;

/// <summary>Log Attributes (incubating).</summary>
public static class LogAttributes
{
    /// <summary>
    /// The basename of the file.
    /// </summary>
    public const string FileName = "log.file.name";

    /// <summary>
    /// The basename of the file, with symlinks resolved.
    /// </summary>
    public const string FileNameResolved = "log.file.name_resolved";

    /// <summary>
    /// The full path to the file.
    /// </summary>
    public const string FilePath = "log.file.path";

    /// <summary>
    /// The full path to the file, with symlinks resolved.
    /// </summary>
    public const string FilePathResolved = "log.file.path_resolved";

    /// <summary>
    /// The stream associated with the log. See below for a list of well-known values.
    /// </summary>
    public const string Iostream = "log.iostream";

    /// <summary>
    /// Values for the <c>Iostream</c> attribute.
    /// </summary>
    public static class IostreamValues
    {
        /// <summary>
        /// Events from stderr stream.
        /// </summary>
        public const string Stderr = "stderr";

        /// <summary>
        /// Logs from stdout stream.
        /// </summary>
        public const string Stdout = "stdout";
    }

    /// <summary>
    /// The complete original Log Record.
    /// </summary>
    /// <remarks>
    /// This value MAY be added when processing a Log Record which was originally transmitted as a string or equivalent data type AND the Body field of the Log Record does not contain the same value. (e.g. a syslog or a log record read from a file.)
    /// </remarks>
    public const string RecordOriginal = "log.record.original";

    /// <summary>
    /// A unique identifier for the Log Record.
    /// </summary>
    /// <remarks>
    /// If an id is provided, other log records with the same id will be considered duplicates and can be removed safely. This means, that two distinguishable log records MUST have different values.
    /// The id MAY be an <a href="https://github.com/ulid/spec">Universally Unique Lexicographically Sortable Identifier (ULID)</a>, but other identifiers (e.g. UUID) may be used as needed.
    /// </remarks>
    public const string RecordUid = "log.record.uid";
}
