// Copyright (c) Alexander Nachtmann
// SPDX-License-Identifier: Apache-2.0

using System.Text;
using Microsoft.CodeAnalysis;

namespace Qyl.OpenTelemetry.SemanticConventions.Analyzers.DocsGenerator;

/// <summary>
///   Emits the three canonical editorconfig severity profiles consumers can drop into
///   their repo to switch the whole QYL band in one line. Mirrors the MS NetAnalyzers
///   <c>rulesets/</c> + <c>editorconfig/</c> pattern at our scale.
///   <list type="bullet">
///     <item><c>Default.editorconfig</c> — each rule at its descriptor-declared default severity</item>
///     <item><c>AllRulesAsErrors.editorconfig</c> — every rule promoted to error</item>
///     <item><c>AllRulesDisabled.editorconfig</c> — every rule silenced</item>
///   </list>
///   Yields (absolute path, content) pairs so both <c>Generate</c> and <c>Check</c> share
///   the source-of-truth content without re-deriving it.
/// </summary>
internal static class EditorconfigRenderer
{
    public static IEnumerable<(string AbsolutePath, string Content)> EnumerateProfiles(
        string repoRoot,
        IReadOnlyList<DiagnosticDescriptor> descriptors)
    {
        var dir = RepoLayout.EditorconfigDir(repoRoot);

        yield return (Path.Combine(dir, "Default.editorconfig"),
            Render(descriptors, "Each QYL rule at its descriptor-declared default severity.",
                d => SeverityToken(d.DefaultSeverity)));

        yield return (Path.Combine(dir, "AllRulesAsErrors.editorconfig"),
            Render(descriptors, "Every QYL rule promoted to error. Use for strict CI.",
                _ => "error"));

        yield return (Path.Combine(dir, "AllRulesDisabled.editorconfig"),
            Render(descriptors, "Every QYL rule silenced. Use to opt the whole band out.",
                _ => "none"));
    }

    private static string Render(
        IReadOnlyList<DiagnosticDescriptor> descriptors,
        string headerComment,
        Func<DiagnosticDescriptor, string> severityFor)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# <auto-generated /> Edits made by hand will be overwritten by");
        sb.AppendLine($"# {RepoLayout.ProjectRelativePath}. Re-run `./build.sh GenerateDocs` after");
        sb.AppendLine("# changing analyzer descriptors. See docs/" + RepoLayout.PackageName + ".md for rule details.");
        sb.AppendLine($"# {headerComment}");
        sb.AppendLine();
        sb.AppendLine("root = false");
        sb.AppendLine();
        sb.AppendLine("[*.{cs,vb}]");
        foreach (var d in descriptors)
            sb.AppendLine($"dotnet_diagnostic.{d.Id}.severity = {severityFor(d)}");
        return sb.ToString().ReplaceLineEndings("\n");
    }

    private static string SeverityToken(DiagnosticSeverity severity) => severity switch
    {
        DiagnosticSeverity.Error => "error",
        DiagnosticSeverity.Warning => "warning",
        DiagnosticSeverity.Info => "suggestion",
        DiagnosticSeverity.Hidden => "silent",
        _ => "default",
    };
}
