// Copyright (c) Alexander Nachtmann
// SPDX-License-Identifier: Apache-2.0

using System.Text;
using Microsoft.CodeAnalysis;

namespace Qyl.OpenTelemetry.SemanticConventions.Analyzers.DocsGenerator;

/// <summary>
///   Renders the slim <c>docs/Qyl.OpenTelemetry.SemanticConventions.Analyzers.md</c> index
///   page. The page is intentionally an index, not an aggregate — each rule row links to
///   its dedicated <c>docs/rules/{id}_{symbolic}.md</c> page (the descriptor's
///   <c>HelpLinkUri</c> resolves to the same target). Sections are composed via an
///   <c>Action&lt;StringBuilder&gt;[]</c> so new sections plug in by appending to the
///   array — adding a section never touches the rest.
/// </summary>
internal static class IndexDocsRenderer
{
    public static string Render(
        IReadOnlyList<DiagnosticDescriptor> descriptors,
        HashSet<string> fixableIds,
        Dictionary<string, string> idToClass)
    {
        var sb = new StringBuilder();
        var sections = new Action<StringBuilder>[]
        {
            WriteHeader,
            b => WriteDiagnostics(b, descriptors, fixableIds, idToClass),
            WriteConfiguration,
            WritePrecedenceAndSuppression,
            WriteSeverityPolicy,
            WriteRelatedDocs,
            WriteGeneratedFile,
        };

        foreach (var section in sections)
        {
            if (sb.Length > 0) sb.AppendLine();
            section(sb);
        }

        return sb.ToString().ReplaceLineEndings("\n");
    }

    private static void WriteHeader(StringBuilder sb)
    {
        sb.AppendLine($"# {RepoLayout.PackageName}");
        sb.AppendLine();
        sb.AppendLine($"<!-- <auto-generated /> This file is generated by {RepoLayout.ProjectRelativePath}. -->");
        sb.AppendLine();
        sb.AppendLine("This package analyzes OpenTelemetry semantic-convention usage in C# consumers. The consumer's referenced `OpenTelemetry.SemanticConventions` assembly remains the primary source of truth: rules that read `[Obsolete]` metadata report what that package actually generated. The [migration catalog](migration-catalog.md) supplements live-metadata coverage with curated diagnostics for changelog/model entries that are not reliably visible through live metadata.");
        sb.AppendLine();
        sb.AppendLine("## Package family");
        sb.AppendLine();
        sb.AppendLine("- **[Qyl OTel-conventions repo](https://github.com/ANcpLua/Qyl.OpenTelemetry.SemanticConventions)** — this analyzer (`QYL00xx` rules), the stable + incubating attribute-key packages, and the source generator that emits typed `Activity`/`Event`/`Meter`/`Metric` projections.");
        sb.AppendLine("- **[ANcpLua framework](https://www.nuget.org/profiles/ANcpLua)** — upstream Roslyn infrastructure consumed by this package: `ANcpLua.Roslyn.Utilities` (shared helpers + `Guard.*` API), `ANcpLua.Analyzers` (general-purpose `AL00xx` band), `ANcpLua.NET.Sdk` (MSBuild SDK that auto-injects the framework's analyzers + `.editorconfig` defaults), `ANcpLua.Agents` (Microsoft Agent Framework toolkit). `QYL00xx` rules are scoped to OTel-conventions consumers; framework rules live in `ANcpLua.Analyzers`.");
    }

    private static void WriteDiagnostics(
        StringBuilder sb,
        IReadOnlyList<DiagnosticDescriptor> descriptors,
        HashSet<string> fixableIds,
        Dictionary<string, string> idToClass)
    {
        sb.AppendLine("## Diagnostics");
        sb.AppendLine();
        sb.AppendLine("Each ID links to a per-rule page under [`docs/rules/`](rules/) with severity, category, code-fix status, and description. The descriptor's `HelpLinkUri` resolves to the same page, so IDE Quick-Fix \"Show error help\" lands on the focused rule, not on this index.");
        sb.AppendLine();
        sb.AppendLine("| ID | Severity | Title | Code fix |");
        sb.AppendLine("| -- | -- | -- | -- |");
        foreach (var d in descriptors)
        {
            var codeFix = RulePageRenderer.GetCodeFixLabel(d.Id, fixableIds);
            var link = idToClass.TryGetValue(d.Id, out var className)
                ? $"[{d.Id}](rules/{d.Id}_{SymbolicNaming.ToSymbolicName(className)}.md)"
                : d.Id;
            sb.AppendLine($"| {link} | {d.DefaultSeverity} | {MarkdownFormatting.Escape(d.Title.ToString())} | {codeFix} |");
        }
    }

    private static void WriteConfiguration(StringBuilder sb)
    {
        sb.AppendLine("## Configuration");
        sb.AppendLine();
        sb.AppendLine("| Option | Values | Behavior |");
        sb.AppendLine("| -- | -- | -- |");
        sb.AppendLine("| `build_property.OtelSemConvNonAttributesTiers` | `false` (default), `true` | When `true`, extends `QYL0003` beyond `*Attributes` classes to also scan the three other Weaver source-generation tiers (`*Metrics`, `*Meters`, `*Activities`) under the SemConv namespace. Default `false` scans only `*Attributes` classes. |");
    }

    private static void WritePrecedenceAndSuppression(StringBuilder sb)
    {
        sb.AppendLine("## Precedence and Suppression");
        sb.AppendLine();
        sb.AppendLine("**Live metadata wins over the supplemental catalog.** When the consumer's referenced `OpenTelemetry.SemanticConventions` package marks a constant or value `[Obsolete]`, the supplemental catalog diagnostics (`QYL0009`/`QYL0010`) skip that symbol entirely — only the live-metadata rules (`QYL0003`/`QYL0005`/`QYL0007`) fire. When that metadata is absent, the catalog provides the fallback diagnostic. No symbol produces two diagnostics for the same root cause.");
        sb.AppendLine();
        sb.AppendLine("**Multi-hop renames resolve to the terminal symbol.** `SemconvMigrationCatalog.ResolveTerminalReplacement` walks `ExactRename` / `ExactValueRename` chains so a code fix on `http.host → net.host.name → server.address` lands consumers on `server.address`, not on the still-deprecated `net.host.name` mid-state. Cycles and chains over 8 hops bail at the last safe step.");
        sb.AppendLine();
        sb.AppendLine("**Structured provenance per catalog entry.** Each `SemconvMigrationCatalogEntry` carries an optional `SemconvChangelogEvidence` (commit / version / url / quote) pinning the claim to an upstream commit.");
        sb.AppendLine();
    }

    private static void WriteSeverityPolicy(StringBuilder sb)
    {
        sb.AppendLine("## Severity Policy");
        sb.AppendLine();
        sb.AppendLine("- `QYL0003`, `QYL0005`, and `QYL0007` read `[Obsolete]` metadata from the referenced semantic-conventions assembly and keep their descriptor severities.");
        sb.AppendLine("- `QYL0009` is reserved for production telemetry emission where the catalog has an exact one-to-one replacement and live metadata is absent.");
        sb.AppendLine("- `QYL0010` is used for context-sensitive migrations, removed/no-replacement entries, guidance-only cases, and ambiguous payload dictionaries.");
        sb.AppendLine("- Generated source is excluded by Roslyn's generated-code ownership rather than filename, symbol, or project-name inference.");
    }

    private static void WriteRelatedDocs(StringBuilder sb)
    {
        sb.AppendLine("## Consumer-side severity profile (`OtelSemConvAnalysisMode`)");
        sb.AppendLine();
        sb.AppendLine("Set `<OtelSemConvAnalysisMode>` in your csproj to switch the whole `QYL00xx` band in one line instead of dropping editorconfig files:");
        sb.AppendLine();
        sb.AppendLine("```xml");
        sb.AppendLine("<PropertyGroup>");
        sb.AppendLine("  <OtelSemConvAnalysisMode>AllAsErrors</OtelSemConvAnalysisMode>");
        sb.AppendLine("</PropertyGroup>");
        sb.AppendLine("```");
        sb.AppendLine();
        sb.AppendLine("| Value | Behavior |");
        sb.AppendLine("| -- | -- |");
        sb.AppendLine("| `Default` | Every rule at its descriptor-declared default severity. Useful to override an ambient stricter config. |");
        sb.AppendLine("| `AllAsErrors` | Every QYL rule promoted to error. Use for strict CI. |");
        sb.AppendLine("| `Disabled` | Every QYL rule silenced. |");
        sb.AppendLine("| _(unset)_ | No editorconfig injection; descriptor severities apply and any consumer-side editorconfig stays authoritative. |");
        sb.AppendLine();
        sb.AppendLine("The property is exposed via the analyzer NuGet's `buildTransitive/Qyl.OpenTelemetry.SemanticConventions.Analyzers.props`, which appends the matching editorconfig from `buildTransitive/editorconfig/` to `$(EditorConfigFiles)` on consumer restore. The name is deliberately not bare `<AnalysisMode>` — that property is owned by `Microsoft.CodeAnalysis.NetAnalyzers` and clashing would force consumers into one-or-the-other choices.");
        sb.AppendLine();
        sb.AppendLine("## See also");
        sb.AppendLine();
        sb.AppendLine("- [Per-rule pages](rules/) — one markdown file per `QYL00xx` rule with severity, category, code-fix status, and description.");
        sb.AppendLine("- [Migration catalog](migration-catalog.md) — curated migration inventory, supplemental attribute-value rows, and coverage-by-version × domain tables that don't fit per-rule pages.");
        sb.AppendLine("- [Editorconfig profiles](editorconfig/) — three drop-in severity profiles: `Default`, `AllRulesAsErrors`, `AllRulesDisabled`. Same content ships inside the NuGet under `buildTransitive/editorconfig/`.");
        sb.AppendLine($"- [SARIF rule manifest]({RepoLayout.PackageName}.sarif) — SARIF v2.1.0 catalog of every `QYL00xx` rule (id, name, severity, category, helpUri). Consume from Sonar bridges, GitHub Advanced Security uploads, or IDE rule-catalog tools.");
        sb.AppendLine("- [`AnalyzerReleases.Shipped.md`](../src/Qyl.OpenTelemetry.SemanticConventions.Analyzers/AnalyzerReleases.Shipped.md) — release-tracking manifest with `ClassName, [Documentation](url)` attribution per Microsoft NetAnalyzers convention.");
    }

    private static void WriteGeneratedFile(StringBuilder sb)
    {
        sb.AppendLine("## Generated File");
        sb.AppendLine();
        sb.AppendLine("Regenerate with:");
        sb.AppendLine();
        sb.AppendLine("```bash");
        sb.AppendLine("./build.sh GenerateDocs");
        sb.AppendLine("./build.sh CheckDocs    # fails if the committed markdown is stale");
        sb.AppendLine("./build.sh AuditDocs    # prints catalog statistics, no file I/O");
        sb.AppendLine("```");
    }
}
