// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@e10a930844c6951757a43b849d364f7d056ac32b
// Schema: https://opentelemetry.io/schemas/1.44.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

#nullable enable

namespace Qyl.Telemetry.SemanticConventions.Incubating.Attributes.Heroku;

/// <summary>Heroku Attributes (incubating).</summary>
public static class HerokuAttributes
{
    /// <summary>
    /// Unique identifier for the application
    /// </summary>
    public const string AppId = "heroku.app.id";

    /// <summary>
    /// Commit hash for the current release
    /// </summary>
    public const string ReleaseCommit = "heroku.release.commit";

    /// <summary>
    /// Time and date the release was created
    /// </summary>
    public const string ReleaseCreationTimestamp = "heroku.release.creation_timestamp";
}
