// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@e10a930844c6951757a43b849d364f7d056ac32b
// Schema: https://opentelemetry.io/schemas/1.44.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

#nullable enable

namespace Qyl.Telemetry.SemanticConventions.Incubating.Attributes.Cloudevents;

/// <summary>Cloudevents Attributes (incubating).</summary>
public static class CloudeventsAttributes
{
    /// <summary>
    /// The <a href="https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md#id">event_id</a> uniquely identifies the event.
    /// </summary>
    public const string EventId = "cloudevents.event_id";

    /// <summary>
    /// The <a href="https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md#source-1">source</a> identifies the context in which an event happened.
    /// </summary>
    public const string EventSource = "cloudevents.event_source";

    /// <summary>
    /// The <a href="https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md#specversion">version of the CloudEvents specification</a> which the event uses.
    /// </summary>
    public const string EventSpecVersion = "cloudevents.event_spec_version";

    /// <summary>
    /// The <a href="https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md#subject">subject</a> of the event in the context of the event producer (identified by source).
    /// </summary>
    public const string EventSubject = "cloudevents.event_subject";

    /// <summary>
    /// The <a href="https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md#type">event_type</a> contains a value describing the type of event related to the originating occurrence.
    /// </summary>
    public const string EventType = "cloudevents.event_type";
}
