// <auto-generated/>
// Generated by qyl's emitter from the qyl-owned registry
// Source: SourceGeneration/Resources/qyl-registry.json
// Licensed under Apache-2.0
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

#nullable enable

namespace Qyl.Telemetry.SemanticConventions.Incubating.Attributes.Qyl;

/// <summary>Qyl Attributes (incubating).</summary>
public static class QylAttributes
{
    /// <summary>
    /// Stable identifier of the qyl capability that produced the telemetry.
    /// </summary>
    public const string CapabilityId = "qyl.capability.id";

    /// <summary>
    /// Kind of the qyl capability that produced the telemetry.
    /// </summary>
    public const string CapabilityKind = "qyl.capability.kind";

    /// <summary>
    /// Origin of a captured exception inside a qyl process (which capture layer recorded it).
    /// </summary>
    public const string ExceptionSource = "qyl.exception.source";

    /// <summary>
    /// qyl auto-instrumentation domain that emitted the span or metric.
    /// </summary>
    public const string InstrumentationDomain = "qyl.instrumentation.domain";

    /// <summary>
    /// Identifier of the MCP evaluation run. Staging: upstream semconv has no equivalent yet.
    /// </summary>
    public const string McpEvaluationRunId = "qyl.mcp.evaluation_run.id";

    /// <summary>
    /// Identifier of the MCP workbench execution. Staging: upstream semconv has no equivalent yet.
    /// </summary>
    public const string McpExecutionId = "qyl.mcp.execution.id";

    /// <summary>
    /// Identifier of the MCP flow. Staging: upstream semconv has no equivalent yet.
    /// </summary>
    public const string McpFlowId = "qyl.mcp.flow.id";

    /// <summary>
    /// Negotiated MCP protocol era. Derived from the negotiated protocol version, never from envelope presence.
    /// </summary>
    public const string McpProtocolEra = "qyl.mcp.protocol.era";

    /// <summary>
    /// MCP SDK tier observed on the connection. Staging: upstream semconv has no equivalent yet.
    /// </summary>
    public const string McpSdkTier = "qyl.mcp.sdk.tier";

    /// <summary>
    /// Identifier of the MCP server as registered in the qyl workbench. Staging: upstream semconv has no equivalent yet.
    /// </summary>
    public const string McpServerId = "qyl.mcp.server.id";

    /// <summary>
    /// Identifier of the MCP test case. Staging: upstream semconv has no equivalent yet.
    /// </summary>
    public const string McpTestCaseId = "qyl.mcp.test_case.id";

    /// <summary>
    /// Name of the MCP tool the telemetry concerns. Staging: upstream semconv has no equivalent yet.
    /// </summary>
    public const string McpToolName = "qyl.mcp.tool.name";

    /// <summary>
    /// qyl project identifier the telemetry belongs to.
    /// </summary>
    public const string ProjectId = "qyl.project.id";

    /// <summary>
    /// qyl workspace identifier the telemetry belongs to.
    /// </summary>
    public const string WorkspaceId = "qyl.workspace.id";
}
