// <auto-generated/>
// Generated by qyl's emitter from the qyl-owned registry
// Source: SourceGeneration/Resources/qyl-registry.json
// Licensed under Apache-2.0
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

#nullable enable

namespace Qyl.Telemetry.SemanticConventions.Incubating.Attributes.Qyl;

/// <summary>Qyl Attributes (incubating).</summary>
public static class QylAttributes
{
    /// <summary>
    /// Number of machine-readable checks in an agent diagnostic state frame.
    /// </summary>
    public const string AgentDiagnosticCheckCount = "qyl.agent.diagnostic.check.count";

    /// <summary>
    /// Number of failed checks in an agent diagnostic state frame.
    /// </summary>
    public const string AgentDiagnosticCheckFailedCount = "qyl.agent.diagnostic.check.failed_count";

    /// <summary>
    /// Stable discriminator of the machine-readable agent diagnostic extension.
    /// </summary>
    public const string AgentDiagnosticExtensionId = "qyl.agent.diagnostic.extension.id";

    /// <summary>
    /// Version of the machine-readable agent diagnostic state-frame format.
    /// </summary>
    public const string AgentDiagnosticFormatVersion = "qyl.agent.diagnostic.format.version";

    /// <summary>
    /// Deterministically computed aggregate outcome of an agent diagnostic state frame.
    /// </summary>
    public const string AgentDiagnosticOutcome = "qyl.agent.diagnostic.outcome";

    /// <summary>
    /// Values for the <c>AgentDiagnosticOutcome</c> attribute.
    /// </summary>
    public static class AgentDiagnosticOutcomeValues
    {
        /// <summary>
        /// At least one evaluated diagnostic check failed.
        /// </summary>
        public const string Fail = "fail";

        /// <summary>
        /// The state frame contained no diagnostic checks.
        /// </summary>
        public const string NotEvaluated = "not_evaluated";

        /// <summary>
        /// Every evaluated diagnostic check passed.
        /// </summary>
        public const string Pass = "pass";

        /// <summary>
        /// No failed check was observed, but at least one check could not be evaluated.
        /// </summary>
        public const string Unknown = "unknown";
    }

    /// <summary>
    /// Program boundary at which an agent diagnostic state frame was captured.
    /// </summary>
    public const string AgentDiagnosticPhase = "qyl.agent.diagnostic.phase";

    /// <summary>
    /// Values for the <c>AgentDiagnosticPhase</c> attribute.
    /// </summary>
    public static class AgentDiagnosticPhaseValues
    {
        /// <summary>
        /// State captured at an explicit verification checkpoint.
        /// </summary>
        public const string Checkpoint = "checkpoint";

        /// <summary>
        /// State captured on an error path.
        /// </summary>
        public const string Error = "error";

        /// <summary>
        /// State captured before the probed operation.
        /// </summary>
        public const string Input = "input";

        /// <summary>
        /// State captured after the probed operation.
        /// </summary>
        public const string Output = "output";
    }

    /// <summary>
    /// Bounded machine identifier of the diagnostic probe that captured the state frame.
    /// </summary>
    public const string AgentDiagnosticProbeId = "qyl.agent.diagnostic.probe.id";

    /// <summary>
    /// Stable identifier of one immutable agent diagnostic state frame.
    /// </summary>
    public const string AgentDiagnosticSnapshotId = "qyl.agent.diagnostic.snapshot.id";

    /// <summary>
    /// Number of dynamic variables described by an agent diagnostic state frame.
    /// </summary>
    public const string AgentDiagnosticVariableCount = "qyl.agent.diagnostic.variable.count";

    /// <summary>
    /// Stable identifier of the qyl capability that produced the telemetry.
    /// </summary>
    public const string CapabilityId = "qyl.capability.id";

    /// <summary>
    /// Kind of the qyl capability that produced the telemetry.
    /// </summary>
    public const string CapabilityKind = "qyl.capability.kind";

    /// <summary>
    /// Origin of a captured exception inside a qyl process (which capture layer recorded it).
    /// </summary>
    public const string ExceptionSource = "qyl.exception.source";

    /// <summary>
    /// qyl auto-instrumentation domain that emitted the span or metric.
    /// </summary>
    public const string InstrumentationDomain = "qyl.instrumentation.domain";

    /// <summary>
    /// Identifier of the MCP evaluation run. Staging: upstream semconv has no equivalent yet.
    /// </summary>
    public const string McpEvaluationRunId = "qyl.mcp.evaluation_run.id";

    /// <summary>
    /// Identifier of the MCP workbench execution. Staging: upstream semconv has no equivalent yet.
    /// </summary>
    public const string McpExecutionId = "qyl.mcp.execution.id";

    /// <summary>
    /// Identifier of the MCP flow. Staging: upstream semconv has no equivalent yet.
    /// </summary>
    public const string McpFlowId = "qyl.mcp.flow.id";

    /// <summary>
    /// Negotiated MCP protocol era. Derived from the negotiated protocol version, never from envelope presence.
    /// </summary>
    public const string McpProtocolEra = "qyl.mcp.protocol.era";

    /// <summary>
    /// MCP SDK tier observed on the connection. Staging: upstream semconv has no equivalent yet.
    /// </summary>
    public const string McpSdkTier = "qyl.mcp.sdk.tier";

    /// <summary>
    /// Identifier of the MCP server as registered in the qyl workbench. Staging: upstream semconv has no equivalent yet.
    /// </summary>
    public const string McpServerId = "qyl.mcp.server.id";

    /// <summary>
    /// Identifier of the MCP test case. Staging: upstream semconv has no equivalent yet.
    /// </summary>
    public const string McpTestCaseId = "qyl.mcp.test_case.id";

    /// <summary>
    /// Name of the MCP tool the telemetry concerns. Staging: upstream semconv has no equivalent yet.
    /// </summary>
    public const string McpToolName = "qyl.mcp.tool.name";

    /// <summary>
    /// qyl project identifier the telemetry belongs to.
    /// </summary>
    public const string ProjectId = "qyl.project.id";

    /// <summary>
    /// Stable workflow agent identifier mirrored into telemetry for journal correlation.
    /// </summary>
    public const string WorkflowAgentId = "qyl.workflow.agent.id";

    /// <summary>
    /// Stable workflow attempt identifier mirrored into telemetry for journal correlation.
    /// </summary>
    public const string WorkflowAttemptId = "qyl.workflow.attempt.id";

    /// <summary>
    /// Stable immutable workflow journal event identifier mirrored into telemetry for correlation.
    /// </summary>
    public const string WorkflowEventId = "qyl.workflow.event.id";

    /// <summary>
    /// Stable workflow run identifier mirrored into telemetry for journal correlation.
    /// </summary>
    public const string WorkflowRunId = "qyl.workflow.run.id";

    /// <summary>
    /// Stable workflow tool-call identifier mirrored into telemetry for journal correlation.
    /// </summary>
    public const string WorkflowToolCallId = "qyl.workflow.tool_call.id";

    /// <summary>
    /// qyl workspace identifier the telemetry belongs to.
    /// </summary>
    public const string WorkspaceId = "qyl.workspace.id";
}
