// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@89aae438b3b3b0a8dd33003c9d70592baf7dbd0d
// Schema: https://opentelemetry.io/schemas/1.43.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

#nullable enable

namespace Qyl.OpenTelemetry.SemanticConventions.Incubating.Attributes.State;

/// <summary>State Attributes (incubating).</summary>
public static class StateAttributes
{
    /// <summary>
    /// Deprecated, use <c>db.client.connection.state</c> instead.
    /// </summary>
    [global::System.Obsolete("Replaced by db.client.connection.state.", false)]
    public const string State = "state";

    /// <summary>
    /// Values for the <c>State</c> attribute.
    /// </summary>
    public static class StateValues
    {
        /// <summary>
        /// idle.
        /// </summary>
        public const string Idle = "idle";

        /// <summary>
        /// used.
        /// </summary>
        public const string Used = "used";
    }
}
