// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@89aae438b3b3b0a8dd33003c9d70592baf7dbd0d
// Schema: https://opentelemetry.io/schemas/1.43.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

#nullable enable

namespace Qyl.Telemetry.SemanticConventions.Incubating.Attributes.Dotnet;

/// <summary>Dotnet Attributes (incubating).</summary>
public static class DotnetAttributes
{
    /// <summary>
    /// Name of the garbage collector managed heap generation.
    /// </summary>
    public const string GcHeapGeneration = "dotnet.gc.heap.generation";

    /// <summary>
    /// Values for the <c>GcHeapGeneration</c> attribute.
    /// </summary>
    public static class GcHeapGenerationValues
    {
        /// <summary>
        /// Generation 0.
        /// </summary>
        public const string Gen0 = "gen0";

        /// <summary>
        /// Generation 1.
        /// </summary>
        public const string Gen1 = "gen1";

        /// <summary>
        /// Generation 2.
        /// </summary>
        public const string Gen2 = "gen2";

        /// <summary>
        /// Large Object Heap.
        /// </summary>
        public const string Loh = "loh";

        /// <summary>
        /// Pinned Object Heap.
        /// </summary>
        public const string Poh = "poh";
    }
}
