// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@e10a930844c6951757a43b849d364f7d056ac32b
// Schema: https://opentelemetry.io/schemas/1.44.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

#nullable enable

namespace Qyl.Telemetry.SemanticConventions.Attributes.Server;

/// <summary>Server Attributes.</summary>
public static class ServerAttributes
{
    /// <summary>
    /// Server domain name if available without reverse DNS lookup; otherwise, IP address or UNIX domain socket name.
    /// </summary>
    /// <remarks>
    /// When observed from the client side, and when communicating through an intermediary, <c>server.address</c> SHOULD represent the server address behind any intermediaries, for example proxies, if it's available.
    /// </remarks>
    public const string Address = "server.address";

    /// <summary>
    /// Server port number.
    /// </summary>
    /// <remarks>
    /// When observed from the client side, and when communicating through an intermediary, <c>server.port</c> SHOULD represent the server port behind any intermediaries, for example proxies, if it's available.
    /// </remarks>
    public const string Port = "server.port";
}
