//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Qyl.OpenTelemetry.SemanticConventions.Analyzers {
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class CodeFixResources {

        private static ResourceManager resourceMan;

        private static CultureInfo resourceCulture;

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CodeFixResources() {
        }

        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (Equals(null, resourceMan)) {
                    ResourceManager temp = new ResourceManager("Qyl.OpenTelemetry.SemanticConventions.Analyzers.CodeFixResources", typeof(CodeFixResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static string QYL0102CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0102CodeFixTitle", resourceCulture);
            }
        }

        internal static string QYL0106CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0106CodeFixTitle", resourceCulture);
            }
        }

        internal static string QYL0107CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0107CodeFixTitle", resourceCulture);
            }
        }

        internal static string QYL0108CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0108CodeFixTitle", resourceCulture);
            }
        }

        internal static string QYL0109CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0109CodeFixTitle", resourceCulture);
            }
        }

        internal static string QYL0305CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0305CodeFixTitle", resourceCulture);
            }
        }

        internal static string QYL0404CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0404CodeFixTitle", resourceCulture);
            }
        }

        internal static string QYL0405CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0405CodeFixTitle", resourceCulture);
            }
        }

        internal static string QYL0500CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0500CodeFixTitle", resourceCulture);
            }
        }

        internal static string QYL0501CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0501CodeFixTitle", resourceCulture);
            }
        }
    }
}
