//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Qyl.OpenTelemetry.SemanticConventions.Analyzers {
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class CodeFixResources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CodeFixResources() {
        }
        
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (Equals(null, resourceMan)) {
                    ResourceManager temp = new ResourceManager("ANcpLua.Analyzers.CodeFixes.CodeFixResources", typeof(CodeFixResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AL0002CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0002CodeFixTitle", resourceCulture);
            }
        }
        
        internal static string AL0004CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0004CodeFixTitle", resourceCulture);
            }
        }
        
        internal static string AL0005CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0005CodeFixTitle", resourceCulture);
            }
        }
        
        internal static string AR0001RefactoringTitle {
            get {
                return ResourceManager.GetString("AR0001RefactoringTitle", resourceCulture);
            }
        }
        
        internal static string AL0008CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0008CodeFixTitle", resourceCulture);
            }
        }
        
        internal static string AL0010CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0010CodeFixTitle", resourceCulture);
            }
        }
        
        internal static string AL0012CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0012CodeFixTitle", resourceCulture);
            }
        }
        
        internal static string AL0015CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0015CodeFixTitle", resourceCulture);
            }
        }
        
        internal static string AL0016CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0016CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL0025CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0025CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL0011CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0011CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL0026CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0026CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL0028CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0028CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL0031CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0031CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL0031CodeFixTitleTryGetConstantValue {
            get {
                return ResourceManager.GetString("QYL0031CodeFixTitleTryGetConstantValue", resourceCulture);
            }
        }

        internal static string AL0027CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0027CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL0029CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0029CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL0030ImplementsCodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0030ImplementsCodeFixTitle", resourceCulture);
            }
        }

        internal static string AL0030InheritsFromCodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0030InheritsFromCodeFixTitle", resourceCulture);
            }
        }

        internal static string AL0039CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0039CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL0032CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0032CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL0033CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0033CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL0034CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0034CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL0035CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0035CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL0036CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0036CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL0037CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0037CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL0040CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0040CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL0045CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0045CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL0046CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0046CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL0047CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0047CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL0048CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0048CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL0049CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0049CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL0050CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0050CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL0051CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0051CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL0071CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0071CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL0072CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0072CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL0073CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0073CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL0074CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0074CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL0103CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0103CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL0107CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0107CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL0108CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0108CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL0109CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0109CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL0110CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0110CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL0121CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0121CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL0122CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0122CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL0124CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0124CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL0126CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0126CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL0134CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0134CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL0135CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0135CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL0137CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0137CodeFixTitle", resourceCulture);
            }
        }

        internal static string AL0138CodeFixTitle {
            get {
                return ResourceManager.GetString("QYL0138CodeFixTitle", resourceCulture);
            }
        }
    }
}
