//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Qyl.OpenTelemetry.SemanticConventions.Analyzers {
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (Equals(null, resourceMan)) {
                    ResourceManager temp = new ResourceManager("Qyl.OpenTelemetry.SemanticConventions.Analyzers.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static string AL0001AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0001AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0001AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0001AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0001AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0001AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0002AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0002AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0002AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0002AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0002AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0002AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0003AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0003AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0003AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0003AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0003AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0003AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0004AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0004AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0004AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0004AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0004AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0004AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0005AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0005AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0005AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0005AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0005AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0005AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0006AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0006AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0006AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0006AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0006AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0006AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0007AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0007AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0007AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0007AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0007AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0007AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0008AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0008AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0008AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0008AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0008AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0008AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0009AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0009AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0009AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0009AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0009AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0009AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0010AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0010AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0010AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0010AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0010AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0010AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0011AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0011AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0011AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0011AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0011AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0011AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0012AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0012AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0012AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0012AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0012AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0012AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0013AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0013AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0013AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0013AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0013AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0013AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0017AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0017AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0017AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0017AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0017AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0017AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0018AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0018AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0018AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0018AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0018AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0018AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0019AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0019AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0019AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0019AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0019AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0019AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0020AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0020AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0020AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0020AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0020AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0020AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0021AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0021AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0021AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0021AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0021AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0021AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0022AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0022AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0022AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0022AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0022AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0022AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0023AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0023AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0023AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0023AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0023AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0023AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0024AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0024AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0024AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0024AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0024AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0024AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0025AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0025AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0025AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0025AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0025AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0025AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0026AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0026AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0026AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0026AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0026AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0026AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0027AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0027AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0027AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0027AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0027AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0027AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0028AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0028AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0028AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0028AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0028AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0028AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0029AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0029AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0029AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0029AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0029AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0029AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0030AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0030AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0030AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0030AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0030AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0030AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0031AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0031AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0031AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0031AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0031AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0031AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0032AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0032AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0032AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0032AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0032AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0032AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0033AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0033AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0033AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0033AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0033AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0033AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0034AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0034AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0034AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0034AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0034AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0034AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0035AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0035AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0035AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0035AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0035AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0035AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0036AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0036AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0036AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0036AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0036AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0036AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0037AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0037AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0037AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0037AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0037AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0037AnalyzerTitle", resourceCulture);
            }
        }
internal static string AL0039AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0039AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0039AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0039AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0039AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0039AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0040AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0040AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0040AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0040AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0040AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0040AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0041AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0041AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0041AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0041AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0041AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0041AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0042AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0042AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0042AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0042AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0042AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0042AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0043AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0043AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0043AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0043AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0043AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0043AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0044AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0044AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0044AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0044AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0044AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0044AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0045AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0045AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0045AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0045AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0045AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0045AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0046AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0046AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0046AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0046AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0046AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0046AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0047AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0047AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0047AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0047AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0047AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0047AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0048AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0048AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0048AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0048AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0048AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0048AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0049AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0049AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0049AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0049AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0049AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0049AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0050AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0050AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0050AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0050AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0050AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0050AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0051AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0051AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0051AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0051AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0051AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0051AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0052AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0052AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0052AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0052AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0052AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0052AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0053AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0053AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0053AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0053AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0053AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0053AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0054AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0054AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0054AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0054AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0054AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0054AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0055AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0055AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0055AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0055AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0055AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0055AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0056AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0056AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0056AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0056AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0056AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0056AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0057AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0057AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0057AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0057AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0057AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0057AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0058AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0058AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0058AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0058AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0058AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0058AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0059AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0059AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0059AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0059AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0059AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0059AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0060AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0060AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0060AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0060AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0060AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0060AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0061AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0061AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0061AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0061AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0061AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0061AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0062AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0062AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0062AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0062AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0062AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0062AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0063AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0063AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0063AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0063AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0063AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0063AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0064AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0064AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0064AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0064AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0064AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0064AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0065AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0065AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0065AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0065AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0065AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0065AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0066AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0066AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0066AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0066AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0066AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0066AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0067AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0067AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0067AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0067AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0067AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0067AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0068AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0068AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0068AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0068AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0068AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0068AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0069AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0069AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0069AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0069AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0069AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0069AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0070AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0070AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0070AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0070AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0070AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0070AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0071AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0071AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0071AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0071AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0071AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0071AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0072AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0072AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0072AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0072AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0072AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0072AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0073AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0073AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0073AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0073AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0073AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0073AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0074AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0074AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0074AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0074AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0074AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0074AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0075AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0075AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0075AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0075AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0075AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0075AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0076AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0076AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0076AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0076AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0076AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0076AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0077AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0077AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0077AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0077AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0077AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0077AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0078AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0078AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0078AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0078AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0078AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0078AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0079AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0079AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0079AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0079AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0079AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0079AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0080AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0080AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0080AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0080AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0080AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0080AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0081AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0081AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0081AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0081AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0081AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0081AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0082AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0082AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0082AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0082AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0082AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0082AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0083AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0083AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0083AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0083AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0083AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0083AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0084AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0084AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0084AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0084AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0084AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0084AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0085AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0085AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0085AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0085AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0085AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0085AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0086AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0086AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0086AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0086AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0086AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0086AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0087AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0087AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0087AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0087AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0087AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0087AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0088AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0088AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0088AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0088AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0088AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0088AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0089AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0089AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0089AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0089AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0089AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0089AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0090AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0090AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0090AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0090AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0090AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0090AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0091AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0091AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0091AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0091AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0091AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0091AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0092AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0092AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0092AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0092AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0092AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0092AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0093AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0093AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0093AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0093AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0093AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0093AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0094AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0094AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0094AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0094AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0094AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0094AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0095AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0095AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0095AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0095AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0095AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0095AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0096AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0096AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0096AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0096AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0096AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0096AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0101AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0101AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0101AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0101AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0101AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0101AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0102AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0102AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0102AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0102AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0102AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0102AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0104AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0104AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0104AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0104AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0104AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0104AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0105AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0105AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0105AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0105AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0105AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0105AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0106AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0106AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0106AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0106AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0106AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0106AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0107AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0107AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0107AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0107AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0107AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0107AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0108AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0108AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0108AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0108AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0108AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0108AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0109AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0109AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0109AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0109AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0109AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0109AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0110AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0110AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0110AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0110AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0110AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0110AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0111AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0111AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0111AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0111AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0111AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0111AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0112AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0112AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0112AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0112AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0112AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0112AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0113AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0113AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0113AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0113AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0113AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0113AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0114AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0114AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0114AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0114AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0114AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0114AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0115AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0115AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0115AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0115AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0115AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0115AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0116AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0116AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0116AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0116AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0116AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0116AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0117AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0117AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0117AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0117AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0117AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0117AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0118AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0118AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0118AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0118AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0118AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0118AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0119AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0119AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0119AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0119AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0119AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0119AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0120AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0120AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0120AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0120AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0120AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0120AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0121AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0121AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0121AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0121AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0121AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0121AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0122AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0122AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0122AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0122AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0122AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0122AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0123AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0123AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0123AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0123AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0123AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0123AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0124AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0124AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0124AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0124AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0124AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0124AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0125AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0125AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0125AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0125AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0125AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0125AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0126AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0126AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0126AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0126AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0126AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0126AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0127AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0127AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0127AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0127AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0127AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0127AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0128AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0128AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0128AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0128AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0128AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0128AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0129AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0129AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0129AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0129AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0129AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0129AnalyzerTitle", resourceCulture);
            }
        }
        internal static string AL0130AnalyzerDescription {
            get {
                return ResourceManager.GetString("QYL0130AnalyzerDescription", resourceCulture);
            }
        }
        internal static string AL0130AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("QYL0130AnalyzerMessageFormat", resourceCulture);
            }
        }
        internal static string AL0130AnalyzerTitle {
            get {
                return ResourceManager.GetString("QYL0130AnalyzerTitle", resourceCulture);
            }
        }
    }
}
