// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@89aae438b3b3b0a8dd33003c9d70592baf7dbd0d
// Schema: https://opentelemetry.io/schemas/1.43.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

#nullable enable

namespace Qyl.Telemetry.SemanticConventions.Incubating.Attributes.Thread;

/// <summary>Thread Attributes (incubating).</summary>
public static class ThreadAttributes
{
    /// <summary>
    /// Current "managed" thread ID (as opposed to OS thread ID).
    /// </summary>
    /// <remarks>
    /// Examples of where the value can be extracted from:
    /// <para/>
    /// | Language or platform | Source |
    /// | JVM | <c>Thread.currentThread().threadId()</c> |
    /// | .NET | <c>Thread.CurrentThread.ManagedThreadId</c> |
    /// | Python | <c>threading.current_thread().ident</c> |
    /// | Ruby | <c>Thread.current.object_id</c> |
    /// | C++ | <c>std::this_thread::get_id()</c> |
    /// | Erlang | <c>erlang:self()</c> |
    /// </remarks>
    public const string Id = "thread.id";

    /// <summary>
    /// Current thread name.
    /// </summary>
    /// <remarks>
    /// Examples of where the value can be extracted from:
    /// <para/>
    /// | Language or platform | Source |
    /// | JVM | <c>Thread.currentThread().getName()</c> |
    /// | .NET | <c>Thread.CurrentThread.Name</c> |
    /// | Python | <c>threading.current_thread().name</c> |
    /// | Ruby | <c>Thread.current.name</c> |
    /// | Erlang | <c>erlang:process_info(self(), registered_name)</c> |
    /// </remarks>
    public const string Name = "thread.name";
}
