// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@e10a930844c6951757a43b849d364f7d056ac32b
// Schema: https://opentelemetry.io/schemas/1.44.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

#nullable enable

namespace Qyl.Telemetry.SemanticConventions.Incubating.Attributes.Cpython;

/// <summary>Cpython Attributes (incubating).</summary>
public static class CpythonAttributes
{
    /// <summary>
    /// Value of the garbage collector collection generation.
    /// </summary>
    public const string GcGeneration = "cpython.gc.generation";

    /// <summary>
    /// Values for the <c>GcGeneration</c> attribute.
    /// </summary>
    public static class GcGenerationValues
    {
        /// <summary>
        /// Generation 0.
        /// </summary>
        public const string Generation0 = "0";

        /// <summary>
        /// Generation 1.
        /// </summary>
        public const string Generation1 = "1";

        /// <summary>
        /// Generation 2.
        /// </summary>
        public const string Generation2 = "2";
    }
}
