// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@89aae438b3b3b0a8dd33003c9d70592baf7dbd0d
// Schema: https://opentelemetry.io/schemas/1.43.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

#nullable enable

namespace Qyl.OpenTelemetry.SemanticConventions.Attributes.System;

/// <summary>System Attributes.</summary>
public static class SystemAttributes
{
    /// <summary>
    /// Deprecated, use <c>cpu.logical_number</c> instead.
    /// </summary>
    [global::System.Obsolete("Replaced by cpu.logical_number.", false)]
    public const string CpuLogicalNumber = "system.cpu.logical_number";

    /// <summary>
    /// Deprecated, use <c>cpu.mode</c> instead.
    /// </summary>
    [global::System.Obsolete("Replaced by cpu.mode.", false)]
    public const string CpuState = "system.cpu.state";

    /// <summary>
    /// Deprecated, use <c>network.connection.state</c> instead.
    /// </summary>
    [global::System.Obsolete("Replaced by network.connection.state.", false)]
    public const string NetworkState = "system.network.state";

    /// <summary>
    /// Deprecated, use <c>system.paging.fault.type</c> instead.
    /// </summary>
    [global::System.Obsolete("Replaced by system.paging.fault.type.", false)]
    public const string PagingType = "system.paging.type";

    /// <summary>
    /// Deprecated, use <c>process.state</c> instead.
    /// </summary>
    [global::System.Obsolete("Replaced by process.state.", false)]
    public const string ProcessStatus = "system.process.status";

    /// <summary>
    /// Deprecated, use <c>process.state</c> instead.
    /// </summary>
    [global::System.Obsolete("Replaced by process.state.", false)]
    public const string ProcessesStatus = "system.processes.status";
}
