// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@e10a930844c6951757a43b849d364f7d056ac32b
// Schema: https://opentelemetry.io/schemas/1.44.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

#nullable enable

namespace Qyl.Telemetry.SemanticConventions.Incubating.Attributes.Az;

/// <summary>Az Attributes (incubating).</summary>
public static class AzAttributes
{
    /// <summary>
    /// Deprecated, use <c>azure.resource_provider.namespace</c> instead.
    /// </summary>
    [global::System.Obsolete("Replaced by azure.resource_provider.namespace.", false)]
    public const string Namespace = "az.namespace";

    /// <summary>
    /// Deprecated, use <c>azure.service.request.id</c> instead.
    /// </summary>
    [global::System.Obsolete("Replaced by azure.service.request.id.", false)]
    public const string ServiceRequestId = "az.service_request_id";
}
