// <auto-generated/>
#nullable enable
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// <auto-generated />

#nullable enable

using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;

#if !NETCOREAPP3_0_OR_GREATER && !NETSTANDARD2_1_OR_GREATER

namespace System;

/// <summary>
///     Backport of <c>Range</c> for .NET Standard 2.0 and .NET Framework.
/// </summary>
[ExcludeFromCodeCoverage]
internal readonly struct Range : IEquatable<Range>
{
    /// <summary>Gets the inclusive start index of the range.</summary>
    public Index Start { get; }

    /// <summary>Gets the exclusive end index of the range.</summary>
    public Index End { get; }

    /// <summary>Initializes a new instance of the <c>Range</c> struct.</summary>
    public Range(Index start, Index end)
    {
        Start = start;
        End = end;
    }

    /// <inheritdoc />
    public override bool Equals(object? obj)
    {
        return obj is Range other && other.Start.Equals(Start) && other.End.Equals(End);
    }

    /// <inheritdoc />
    public bool Equals(Range other)
    {
        return other.Start.Equals(Start) && other.End.Equals(End);
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        return Start.GetHashCode() * 31 + End.GetHashCode();
    }

    /// <summary>Returns the string representation of this range in C# syntax.</summary>
    public override string ToString()
    {
        return Start + ".." + End;
    }

    /// <summary>Creates a range starting at the specified index and ending at the end of the collection.</summary>
    public static Range StartAt(Index start)
    {
        return new Range(start, Index.End);
    }

    /// <summary>Creates a range starting at the beginning and ending at the specified index.</summary>
    public static Range EndAt(Index end)
    {
        return new Range(Index.Start, end);
    }

    /// <summary>Gets a range representing the entire collection.</summary>
    public static Range All => new(Index.Start, Index.End);

    /// <summary>Calculates the start offset and length of this range for a collection of the specified length.</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public (int Offset, int Length) GetOffsetAndLength(int length)
    {
        var start = Start.GetOffset(length);
        var end = End.GetOffset(length);
        if ((uint)end > (uint)length || (uint)start > (uint)end) throw new ArgumentOutOfRangeException(nameof(length));
        return (start, end - start);
    }
}
#endif