// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@89aae438b3b3b0a8dd33003c9d70592baf7dbd0d
// Schema: https://opentelemetry.io/schemas/1.43.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

#nullable enable

namespace Qyl.OpenTelemetry.SemanticConventions.Incubating.Attributes.Dns;

/// <summary>Dns Attributes (incubating).</summary>
public static class DnsAttributes
{
    /// <summary>
    /// The list of IPv4 or IPv6 addresses resolved during DNS lookup.
    /// </summary>
    public const string Answers = "dns.answers";

    /// <summary>
    /// The name being queried.
    /// </summary>
    /// <remarks>
    /// The name represents the queried domain name as it appears in the DNS query without any additional normalization.
    /// </remarks>
    public const string QuestionName = "dns.question.name";
}
