// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@89aae438b3b3b0a8dd33003c9d70592baf7dbd0d
// Schema: https://opentelemetry.io/schemas/1.43.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

#nullable enable

namespace Qyl.OpenTelemetry.SemanticConventions.Attributes.Android;

/// <summary>Android Attributes.</summary>
public static class AndroidAttributes
{
    /// <summary>
    /// Deprecated. Use <c>android.app.state</c> attribute instead.
    /// </summary>
    [global::System.Obsolete("Replaced by android.app.state.", false)]
    public const string State = "android.state";
}
