// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@e10a930844c6951757a43b849d364f7d056ac32b
// Schema: https://opentelemetry.io/schemas/1.44.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

#nullable enable

namespace Qyl.Telemetry.SemanticConventions.Attributes.Rpc;

/// <summary>Rpc Attributes.</summary>
public static class RpcAttributes
{
    /// <summary>
    /// Deprecated, use <c>rpc.response.status_code</c> attribute instead.
    /// </summary>
    [global::System.Obsolete("Replaced by rpc.response.status_code.", false)]
    public const string ConnectRpcErrorCode = "rpc.connect_rpc.error_code";

    /// <summary>
    /// Deprecated, use <c>rpc.request.metadata</c> instead.
    /// </summary>
    [global::System.Obsolete("Replaced by rpc.request.metadata.", false)]
    public const string ConnectRpcRequestMetadata = "rpc.connect_rpc.request.metadata";

    /// <summary>
    /// Deprecated, use <c>rpc.response.metadata</c> instead.
    /// </summary>
    [global::System.Obsolete("Replaced by rpc.response.metadata.", false)]
    public const string ConnectRpcResponseMetadata = "rpc.connect_rpc.response.metadata";

    /// <summary>
    /// Deprecated, use <c>rpc.request.metadata</c> instead.
    /// </summary>
    [global::System.Obsolete("Replaced by rpc.request.metadata.", false)]
    public const string GrpcRequestMetadata = "rpc.grpc.request.metadata";

    /// <summary>
    /// Deprecated, use <c>rpc.response.metadata</c> instead.
    /// </summary>
    [global::System.Obsolete("Replaced by rpc.response.metadata.", false)]
    public const string GrpcResponseMetadata = "rpc.grpc.response.metadata";

    /// <summary>
    /// Deprecated, use string representation on the <c>rpc.response.status_code</c> attribute instead.
    /// </summary>
    [global::System.Obsolete("Use string representation of the gRPC status code on the `rpc.response.status_code` attribute.", false)]
    public const string GrpcStatusCode = "rpc.grpc.status_code";

    /// <summary>
    /// Deprecated, use string representation on the <c>rpc.response.status_code</c> attribute instead.
    /// </summary>
    [global::System.Obsolete("Use string representation of the error code on the `rpc.response.status_code` attribute.", false)]
    public const string JsonrpcErrorCode = "rpc.jsonrpc.error_code";

    /// <summary>
    /// Deprecated, use the span status description when reporting JSON-RPC spans.
    /// </summary>
    [global::System.Obsolete("Use the span status description when reporting JSON-RPC spans.", false)]
    public const string JsonrpcErrorMessage = "rpc.jsonrpc.error_message";

    /// <summary>
    /// Deprecated, use <c>jsonrpc.request.id</c> instead.
    /// </summary>
    [global::System.Obsolete("Replaced by jsonrpc.request.id.", false)]
    public const string JsonrpcRequestId = "rpc.jsonrpc.request_id";

    /// <summary>
    /// Deprecated, use <c>jsonrpc.protocol.version</c> instead.
    /// </summary>
    [global::System.Obsolete("Replaced by jsonrpc.protocol.version.", false)]
    public const string JsonrpcVersion = "rpc.jsonrpc.version";

    /// <summary>
    /// Compressed size of the message in bytes.
    /// </summary>
    [global::System.Obsolete("Removed, no replacement.", false)]
    public const string MessageCompressedSize = "rpc.message.compressed_size";

    /// <summary>
    /// MUST be calculated as two different counters starting from <c>1</c> one for sent messages and one for received message.
    /// </summary>
    /// <remarks>
    /// This way we guarantee that the values will be consistent between different implementations.
    /// </remarks>
    [global::System.Obsolete("Removed, no replacement.", false)]
    public const string MessageId = "rpc.message.id";

    /// <summary>
    /// Whether this is a received or sent message.
    /// </summary>
    [global::System.Obsolete("Removed, no replacement.", false)]
    public const string MessageType = "rpc.message.type";

    /// <summary>
    /// Uncompressed size of the message in bytes.
    /// </summary>
    [global::System.Obsolete("Removed, no replacement.", false)]
    public const string MessageUncompressedSize = "rpc.message.uncompressed_size";

    /// <summary>
    /// Deprecated, use fully-qualified <c>rpc.method</c> instead.
    /// </summary>
    [global::System.Obsolete("Value should be included in `rpc.method` which is expected to be a fully-qualified name.", false)]
    public const string Service = "rpc.service";

    /// <summary>
    /// Deprecated, use <c>rpc.system.name</c> attribute instead.
    /// </summary>
    [global::System.Obsolete("Replaced by rpc.system.name.", false)]
    public const string System = "rpc.system";
}
