// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@e10a930844c6951757a43b849d364f7d056ac32b
// Schema: https://opentelemetry.io/schemas/1.44.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

#nullable enable

namespace Qyl.Telemetry.SemanticConventions.Attributes.Ios;

/// <summary>Ios Attributes.</summary>
public static class IosAttributes
{
    /// <summary>
    /// Deprecated. Use the <c>ios.app.state</c> attribute.
    /// </summary>
    /// <remarks>
    /// The iOS lifecycle states are defined in the <a href="https://developer.apple.com/documentation/uikit/uiapplicationdelegate">UIApplicationDelegate documentation</a>, and from which the <c>OS terminology</c> column values are derived.
    /// </remarks>
    [global::System.Obsolete("Replaced by ios.app.state.", false)]
    public const string State = "ios.state";
}
