// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@89aae438b3b3b0a8dd33003c9d70592baf7dbd0d
// Schema: https://opentelemetry.io/schemas/1.43.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

#nullable enable

namespace Qyl.OpenTelemetry.SemanticConventions.Incubating.Attributes.OncRpc;

/// <summary>OncRpc Attributes (incubating).</summary>
public static class OncRpcAttributes
{
    /// <summary>
    /// ONC/Sun RPC procedure name.
    /// </summary>
    public const string ProcedureName = "onc_rpc.procedure.name";

    /// <summary>
    /// ONC/Sun RPC procedure number.
    /// </summary>
    public const string ProcedureNumber = "onc_rpc.procedure.number";

    /// <summary>
    /// ONC/Sun RPC program name.
    /// </summary>
    public const string ProgramName = "onc_rpc.program.name";

    /// <summary>
    /// ONC/Sun RPC program version.
    /// </summary>
    public const string Version = "onc_rpc.version";
}
