// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@89aae438b3b3b0a8dd33003c9d70592baf7dbd0d
// Schema: https://opentelemetry.io/schemas/1.43.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

#nullable enable

namespace Qyl.Telemetry.SemanticConventions.Incubating.Attributes.Pool;

/// <summary>Pool Attributes (incubating).</summary>
public static class PoolAttributes
{
    /// <summary>
    /// Deprecated, use <c>db.client.connection.pool.name</c> instead.
    /// </summary>
    [global::System.Obsolete("Replaced by db.client.connection.pool.name.", false)]
    public const string Name = "pool.name";
}
