// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@89aae438b3b3b0a8dd33003c9d70592baf7dbd0d
// Schema: https://opentelemetry.io/schemas/1.43.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

#nullable enable

namespace Qyl.OpenTelemetry.SemanticConventions.Incubating.Attributes.Server;

/// <summary>Server Attributes (incubating).</summary>
public static class ServerAttributes
{
    /// <summary>
    /// Server domain name if available without reverse DNS lookup; otherwise, IP address or Unix domain socket name.
    /// </summary>
    /// <remarks>
    /// When observed from the client side, and when communicating through an intermediary, <c>server.address</c> SHOULD represent the server address behind any intermediaries, for example proxies, if it's available.
    /// </remarks>
    public const string Address = "server.address";

    /// <summary>
    /// Server port number.
    /// </summary>
    /// <remarks>
    /// When observed from the client side, and when communicating through an intermediary, <c>server.port</c> SHOULD represent the server port behind any intermediaries, for example proxies, if it's available.
    /// </remarks>
    public const string Port = "server.port";
}
