// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@89aae438b3b3b0a8dd33003c9d70592baf7dbd0d
// Schema: https://opentelemetry.io/schemas/1.43.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

#nullable enable

namespace Qyl.Telemetry.SemanticConventions.Incubating.Attributes.Zos;

/// <summary>Zos Attributes (incubating).</summary>
public static class ZosAttributes
{
    /// <summary>
    /// The System Management Facility (SMF) Identifier uniquely identified a z/OS system within a SYSPLEX or mainframe environment and is used for system and performance analysis.
    /// </summary>
    public const string SmfId = "zos.smf.id";

    /// <summary>
    /// The name of the SYSPLEX to which the z/OS system belongs too.
    /// </summary>
    public const string SysplexName = "zos.sysplex.name";
}
