// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@89aae438b3b3b0a8dd33003c9d70592baf7dbd0d
// Schema: https://opentelemetry.io/schemas/1.43.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

#nullable enable

namespace Qyl.OpenTelemetry.SemanticConventions.Attributes.K8s;

/// <summary>K8s Attributes.</summary>
public static class K8sAttributes
{
    /// <summary>
    /// The name of the cluster.
    /// </summary>
    public const string ClusterName = "k8s.cluster.name";

    /// <summary>
    /// A pseudo-ID for the cluster, set to the UID of the <c>kube-system</c> namespace.
    /// </summary>
    /// <remarks>
    /// K8s doesn't have support for obtaining a cluster ID. If this is ever
    /// added, we will recommend collecting the <c>k8s.cluster.uid</c> through the
    /// official APIs. In the meantime, we are able to use the <c>uid</c> of the
    /// <c>kube-system</c> namespace as a proxy for cluster ID. Read on for the
    /// rationale.
    /// <para/>
    /// Every object created in a K8s cluster is assigned a distinct UID. The
    /// <c>kube-system</c> namespace is used by Kubernetes itself and will exist
    /// for the lifetime of the cluster. Using the <c>uid</c> of the <c>kube-system</c>
    /// namespace is a reasonable proxy for the K8s ClusterID as it will only
    /// change if the cluster is rebuilt. Furthermore, Kubernetes UIDs are
    /// UUIDs as standardized by
    /// <a href="https://www.itu.int/ITU-T/studygroups/com17/oid.html">ISO/IEC 9834-8 and ITU-T X.667</a>.
    /// Which states:
    /// <para/>
    /// If generated according to one of the mechanisms defined in Rec.
    /// ITU-T X.667 | ISO/IEC 9834-8, a UUID is either guaranteed to be
    /// different from all other UUIDs generated before 3603 A.D., or is
    /// extremely likely to be different (depending on the mechanism chosen).
    /// <para/>
    /// Therefore, UIDs between clusters should be extremely unlikely to
    /// conflict.
    /// </remarks>
    public const string ClusterUid = "k8s.cluster.uid";

    /// <summary>
    /// The name of the Container from Pod specification, must be unique within a Pod. Container runtime usually uses different globally unique name (<c>container.name</c>).
    /// </summary>
    public const string ContainerName = "k8s.container.name";

    /// <summary>
    /// Number of times the container was restarted. This attribute can be used to identify a particular container (running or stopped) within a container spec.
    /// </summary>
    public const string ContainerRestartCount = "k8s.container.restart_count";

    /// <summary>
    /// The cronjob annotation placed on the CronJob, the <c>&lt;key&gt;</c> being the annotation name, the value being the annotation value.
    /// </summary>
    /// <remarks>
    /// Examples:
    /// <para/>
    /// - An annotation <c>retries</c> with value <c>4</c> SHOULD be recorded as the
    ///   <c>k8s.cronjob.annotation.retries</c> attribute with value <c>"4"</c>.
    /// - An annotation <c>data</c> with empty string value SHOULD be recorded as
    ///   the <c>k8s.cronjob.annotation.data</c> attribute with value <c>""</c>.
    /// </remarks>
    public const string CronjobAnnotation = "k8s.cronjob.annotation";

    /// <summary>
    /// The label placed on the CronJob, the <c>&lt;key&gt;</c> being the label name, the value being the label value.
    /// </summary>
    /// <remarks>
    /// Examples:
    /// <para/>
    /// - A label <c>type</c> with value <c>weekly</c> SHOULD be recorded as the
    ///   <c>k8s.cronjob.label.type</c> attribute with value <c>"weekly"</c>.
    /// - A label <c>automated</c> with empty string value SHOULD be recorded as
    ///   the <c>k8s.cronjob.label.automated</c> attribute with value <c>""</c>.
    /// </remarks>
    public const string CronjobLabel = "k8s.cronjob.label";

    /// <summary>
    /// The name of the CronJob.
    /// </summary>
    public const string CronjobName = "k8s.cronjob.name";

    /// <summary>
    /// The UID of the CronJob.
    /// </summary>
    public const string CronjobUid = "k8s.cronjob.uid";

    /// <summary>
    /// The annotation placed on the DaemonSet, the <c>&lt;key&gt;</c> being the annotation name, the value being the annotation value, even if the value is empty.
    /// </summary>
    /// <remarks>
    /// Examples:
    /// <para/>
    /// - An annotation <c>replicas</c> with value <c>1</c> SHOULD be recorded
    ///   as the <c>k8s.daemonset.annotation.replicas</c> attribute with value <c>"1"</c>.
    /// - An annotation <c>data</c> with empty string value SHOULD be recorded as
    ///   the <c>k8s.daemonset.annotation.data</c> attribute with value <c>""</c>.
    /// </remarks>
    public const string DaemonsetAnnotation = "k8s.daemonset.annotation";

    /// <summary>
    /// The label placed on the DaemonSet, the <c>&lt;key&gt;</c> being the label name, the value being the label value, even if the value is empty.
    /// </summary>
    /// <remarks>
    /// Examples:
    /// <para/>
    /// - A label <c>app</c> with value <c>guestbook</c> SHOULD be recorded
    ///   as the <c>k8s.daemonset.label.app</c> attribute with value <c>"guestbook"</c>.
    /// - A label <c>injected</c> with empty string value SHOULD be recorded as
    ///   the <c>k8s.daemonset.label.injected</c> attribute with value <c>""</c>.
    /// </remarks>
    public const string DaemonsetLabel = "k8s.daemonset.label";

    /// <summary>
    /// The name of the DaemonSet.
    /// </summary>
    public const string DaemonsetName = "k8s.daemonset.name";

    /// <summary>
    /// The UID of the DaemonSet.
    /// </summary>
    public const string DaemonsetUid = "k8s.daemonset.uid";

    /// <summary>
    /// The annotation placed on the Deployment, the <c>&lt;key&gt;</c> being the annotation name, the value being the annotation value, even if the value is empty.
    /// </summary>
    /// <remarks>
    /// Examples:
    /// <para/>
    /// - An annotation <c>replicas</c> with value <c>1</c> SHOULD be recorded
    ///   as the <c>k8s.deployment.annotation.replicas</c> attribute with value <c>"1"</c>.
    /// - An annotation <c>data</c> with empty string value SHOULD be recorded as
    ///   the <c>k8s.deployment.annotation.data</c> attribute with value <c>""</c>.
    /// </remarks>
    public const string DeploymentAnnotation = "k8s.deployment.annotation";

    /// <summary>
    /// The label placed on the Deployment, the <c>&lt;key&gt;</c> being the label name, the value being the label value, even if the value is empty.
    /// </summary>
    /// <remarks>
    /// Examples:
    /// <para/>
    /// - A label <c>app</c> with value <c>guestbook</c> SHOULD be recorded
    ///   as the <c>k8s.deployment.label.app</c> attribute with value <c>"guestbook"</c>.
    /// - A label <c>injected</c> with empty string value SHOULD be recorded as
    ///   the <c>k8s.deployment.label.injected</c> attribute with value <c>""</c>.
    /// </remarks>
    public const string DeploymentLabel = "k8s.deployment.label";

    /// <summary>
    /// The name of the Deployment.
    /// </summary>
    public const string DeploymentName = "k8s.deployment.name";

    /// <summary>
    /// The UID of the Deployment.
    /// </summary>
    public const string DeploymentUid = "k8s.deployment.uid";

    /// <summary>
    /// The annotation placed on the Job, the <c>&lt;key&gt;</c> being the annotation name, the value being the annotation value, even if the value is empty.
    /// </summary>
    /// <remarks>
    /// Examples:
    /// <para/>
    /// - An annotation <c>number</c> with value <c>1</c> SHOULD be recorded
    ///   as the <c>k8s.job.annotation.number</c> attribute with value <c>"1"</c>.
    /// - An annotation <c>data</c> with empty string value SHOULD be recorded as
    ///   the <c>k8s.job.annotation.data</c> attribute with value <c>""</c>.
    /// </remarks>
    public const string JobAnnotation = "k8s.job.annotation";

    /// <summary>
    /// The label placed on the Job, the <c>&lt;key&gt;</c> being the label name, the value being the label value, even if the value is empty.
    /// </summary>
    /// <remarks>
    /// Examples:
    /// <para/>
    /// - A label <c>jobtype</c> with value <c>ci</c> SHOULD be recorded
    ///   as the <c>k8s.job.label.jobtype</c> attribute with value <c>"ci"</c>.
    /// - A label <c>automated</c> with empty string value SHOULD be recorded as
    ///   the <c>k8s.job.label.automated</c> attribute with value <c>""</c>.
    /// </remarks>
    public const string JobLabel = "k8s.job.label";

    /// <summary>
    /// The name of the Job.
    /// </summary>
    public const string JobName = "k8s.job.name";

    /// <summary>
    /// The UID of the Job.
    /// </summary>
    public const string JobUid = "k8s.job.uid";

    /// <summary>
    /// The annotation placed on the Namespace, the <c>&lt;key&gt;</c> being the annotation name, the value being the annotation value, even if the value is empty.
    /// </summary>
    /// <remarks>
    /// Examples:
    /// <para/>
    /// - An annotation <c>ttl</c> with value <c>0</c> SHOULD be recorded
    ///   as the <c>k8s.namespace.annotation.ttl</c> attribute with value <c>"0"</c>.
    /// - An annotation <c>data</c> with empty string value SHOULD be recorded as
    ///   the <c>k8s.namespace.annotation.data</c> attribute with value <c>""</c>.
    /// </remarks>
    public const string NamespaceAnnotation = "k8s.namespace.annotation";

    /// <summary>
    /// The label placed on the Namespace, the <c>&lt;key&gt;</c> being the label name, the value being the label value, even if the value is empty.
    /// </summary>
    /// <remarks>
    /// Examples:
    /// <para/>
    /// - A label <c>kubernetes.io/metadata.name</c> with value <c>default</c> SHOULD be recorded
    ///   as the <c>k8s.namespace.label.kubernetes.io/metadata.name</c> attribute with value <c>"default"</c>.
    /// - A label <c>data</c> with empty string value SHOULD be recorded as
    ///   the <c>k8s.namespace.label.data</c> attribute with value <c>""</c>.
    /// </remarks>
    public const string NamespaceLabel = "k8s.namespace.label";

    /// <summary>
    /// The name of the namespace that the pod is running in.
    /// </summary>
    public const string NamespaceName = "k8s.namespace.name";

    /// <summary>
    /// The annotation placed on the Node, the <c>&lt;key&gt;</c> being the annotation name, the value being the annotation value, even if the value is empty.
    /// </summary>
    /// <remarks>
    /// Examples:
    /// <para/>
    /// - An annotation <c>node.alpha.kubernetes.io/ttl</c> with value <c>0</c> SHOULD be recorded as
    ///   the <c>k8s.node.annotation.node.alpha.kubernetes.io/ttl</c> attribute with value <c>"0"</c>.
    /// - An annotation <c>data</c> with empty string value SHOULD be recorded as
    ///   the <c>k8s.node.annotation.data</c> attribute with value <c>""</c>.
    /// </remarks>
    public const string NodeAnnotation = "k8s.node.annotation";

    /// <summary>
    /// The label placed on the Node, the <c>&lt;key&gt;</c> being the label name, the value being the label value, even if the value is empty.
    /// </summary>
    /// <remarks>
    /// Examples:
    /// <para/>
    /// - A label <c>kubernetes.io/arch</c> with value <c>arm64</c> SHOULD be recorded
    ///   as the <c>k8s.node.label.kubernetes.io/arch</c> attribute with value <c>"arm64"</c>.
    /// - A label <c>data</c> with empty string value SHOULD be recorded as
    ///   the <c>k8s.node.label.data</c> attribute with value <c>""</c>.
    /// </remarks>
    public const string NodeLabel = "k8s.node.label";

    /// <summary>
    /// The name of the Node.
    /// </summary>
    public const string NodeName = "k8s.node.name";

    /// <summary>
    /// The UID of the Node.
    /// </summary>
    public const string NodeUid = "k8s.node.uid";

    /// <summary>
    /// The annotation placed on the Pod, the <c>&lt;key&gt;</c> being the annotation name, the value being the annotation value.
    /// </summary>
    /// <remarks>
    /// Examples:
    /// <para/>
    /// - An annotation <c>kubernetes.io/enforce-mountable-secrets</c> with value <c>true</c> SHOULD be recorded as
    ///   the <c>k8s.pod.annotation.kubernetes.io/enforce-mountable-secrets</c> attribute with value <c>"true"</c>.
    /// - An annotation <c>mycompany.io/arch</c> with value <c>x64</c> SHOULD be recorded as
    ///   the <c>k8s.pod.annotation.mycompany.io/arch</c> attribute with value <c>"x64"</c>.
    /// - An annotation <c>data</c> with empty string value SHOULD be recorded as
    ///   the <c>k8s.pod.annotation.data</c> attribute with value <c>""</c>.
    /// </remarks>
    public const string PodAnnotation = "k8s.pod.annotation";

    /// <summary>
    /// Specifies the hostname of the Pod.
    /// </summary>
    /// <remarks>
    /// The K8s Pod spec has an optional hostname field, which can be used to specify a hostname.
    /// Refer to <a href="https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-hostname-and-subdomain-field">K8s docs</a>
    /// for more information about this field.
    /// <para/>
    /// This attribute aligns with the <c>hostname</c> field of the
    /// <a href="https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.34/#podspec-v1-core">K8s PodSpec</a>.
    /// </remarks>
    public const string PodHostname = "k8s.pod.hostname";

    /// <summary>
    /// IP address allocated to the Pod.
    /// </summary>
    /// <remarks>
    /// This attribute aligns with the <c>podIP</c> field of the
    /// <a href="https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.34/#podstatus-v1-core">K8s PodStatus</a>.
    /// </remarks>
    public const string PodIp = "k8s.pod.ip";

    /// <summary>
    /// The label placed on the Pod, the <c>&lt;key&gt;</c> being the label name, the value being the label value.
    /// </summary>
    /// <remarks>
    /// Examples:
    /// <para/>
    /// - A label <c>app</c> with value <c>my-app</c> SHOULD be recorded as
    ///   the <c>k8s.pod.label.app</c> attribute with value <c>"my-app"</c>.
    /// - A label <c>mycompany.io/arch</c> with value <c>x64</c> SHOULD be recorded as
    ///   the <c>k8s.pod.label.mycompany.io/arch</c> attribute with value <c>"x64"</c>.
    /// - A label <c>data</c> with empty string value SHOULD be recorded as
    ///   the <c>k8s.pod.label.data</c> attribute with value <c>""</c>.
    /// </remarks>
    public const string PodLabel = "k8s.pod.label";

    /// <summary>
    /// Deprecated, use <c>k8s.pod.label</c> instead.
    /// </summary>
    [global::System.Obsolete("Replaced by k8s.pod.label.", false)]
    public const string PodLabels = "k8s.pod.labels";

    /// <summary>
    /// The name of the Pod.
    /// </summary>
    public const string PodName = "k8s.pod.name";

    /// <summary>
    /// The start timestamp of the Pod.
    /// </summary>
    /// <remarks>
    /// Date and time at which the object was acknowledged by the Kubelet.
    /// This is before the Kubelet pulled the container image(s) for the pod.
    /// <para/>
    /// This attribute aligns with the <c>startTime</c> field of the
    /// <a href="https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.34/#podstatus-v1-core">K8s PodStatus</a>,
    /// in ISO 8601 (RFC 3339 compatible) format.
    /// </remarks>
    public const string PodStartTime = "k8s.pod.start_time";

    /// <summary>
    /// The UID of the Pod.
    /// </summary>
    public const string PodUid = "k8s.pod.uid";

    /// <summary>
    /// The annotation placed on the ReplicaSet, the <c>&lt;key&gt;</c> being the annotation name, the value being the annotation value, even if the value is empty.
    /// </summary>
    /// <remarks>
    /// Examples:
    /// <para/>
    /// - An annotation <c>replicas</c> with value <c>0</c> SHOULD be recorded
    ///   as the <c>k8s.replicaset.annotation.replicas</c> attribute with value <c>"0"</c>.
    /// - An annotation <c>data</c> with empty string value SHOULD be recorded as
    ///   the <c>k8s.replicaset.annotation.data</c> attribute with value <c>""</c>.
    /// </remarks>
    public const string ReplicasetAnnotation = "k8s.replicaset.annotation";

    /// <summary>
    /// The label placed on the ReplicaSet, the <c>&lt;key&gt;</c> being the label name, the value being the label value, even if the value is empty.
    /// </summary>
    /// <remarks>
    /// Examples:
    /// <para/>
    /// - A label <c>app</c> with value <c>guestbook</c> SHOULD be recorded
    ///   as the <c>k8s.replicaset.label.app</c> attribute with value <c>"guestbook"</c>.
    /// - A label <c>injected</c> with empty string value SHOULD be recorded as
    ///   the <c>k8s.replicaset.label.injected</c> attribute with value <c>""</c>.
    /// </remarks>
    public const string ReplicasetLabel = "k8s.replicaset.label";

    /// <summary>
    /// The name of the ReplicaSet.
    /// </summary>
    public const string ReplicasetName = "k8s.replicaset.name";

    /// <summary>
    /// The UID of the ReplicaSet.
    /// </summary>
    public const string ReplicasetUid = "k8s.replicaset.uid";

    /// <summary>
    /// The annotation placed on the StatefulSet, the <c>&lt;key&gt;</c> being the annotation name, the value being the annotation value, even if the value is empty.
    /// </summary>
    /// <remarks>
    /// Examples:
    /// <para/>
    /// - An annotation <c>replicas</c> with value <c>1</c> SHOULD be recorded
    ///   as the <c>k8s.statefulset.annotation.replicas</c> attribute with value <c>"1"</c>.
    /// - An annotation <c>data</c> with empty string value SHOULD be recorded as
    ///   the <c>k8s.statefulset.annotation.data</c> attribute with value <c>""</c>.
    /// </remarks>
    public const string StatefulsetAnnotation = "k8s.statefulset.annotation";

    /// <summary>
    /// The label placed on the StatefulSet, the <c>&lt;key&gt;</c> being the label name, the value being the label value, even if the value is empty.
    /// </summary>
    /// <remarks>
    /// Examples:
    /// <para/>
    /// - A label <c>app</c> with value <c>guestbook</c> SHOULD be recorded
    ///   as the <c>k8s.statefulset.label.app</c> attribute with value <c>"guestbook"</c>.
    /// - A label <c>injected</c> with empty string value SHOULD be recorded as
    ///   the <c>k8s.statefulset.label.injected</c> attribute with value <c>""</c>.
    /// </remarks>
    public const string StatefulsetLabel = "k8s.statefulset.label";

    /// <summary>
    /// The name of the StatefulSet.
    /// </summary>
    public const string StatefulsetName = "k8s.statefulset.name";

    /// <summary>
    /// The UID of the StatefulSet.
    /// </summary>
    public const string StatefulsetUid = "k8s.statefulset.uid";
}
