// <auto-generated/>
// Generated by qyl's Weaver pipeline from open-telemetry/semantic-conventions@e10a930844c6951757a43b849d364f7d056ac32b
// Schema: https://opentelemetry.io/schemas/1.44.0
// Licensed under Apache-2.0 (inherited from OpenTelemetry upstream)
// </auto-generated>

// Copyright (c) 2025-2026 ancplua

#nullable enable

namespace Qyl.Telemetry.SemanticConventions.Attributes.Message;

/// <summary>Message Attributes.</summary>
public static class MessageAttributes
{
    /// <summary>
    /// Deprecated, no replacement at this time.
    /// </summary>
    [global::System.Obsolete("Removed, no replacement.", false)]
    public const string CompressedSize = "message.compressed_size";

    /// <summary>
    /// Deprecated, no replacement at this time.
    /// </summary>
    [global::System.Obsolete("Removed, no replacement.", false)]
    public const string Id = "message.id";

    /// <summary>
    /// Deprecated, no replacement at this time.
    /// </summary>
    [global::System.Obsolete("Removed, no replacement.", false)]
    public const string Type = "message.type";

    /// <summary>
    /// Deprecated, no replacement at this time.
    /// </summary>
    [global::System.Obsolete("Removed, no replacement.", false)]
    public const string UncompressedSize = "message.uncompressed_size";
}
